### ISSUE TITLE
Formula with range

### ISSUE THREAD

**Issue by imacreste2** [PHPOffice/PHPExcel#1006]
I have a formula with range.
Attempting to read the result with: getCalculatedValue

I get the following error:
```
Fatal error: Uncaught exception 'PHPExcel_Calculation_Exception' with message 'GENERAL_Autocompletado!F58 -> GENERAL_Autocompletado!B34 -> Valoracíon GENERAL!E9 -> Valoracíon GENERAL!E2 -> Valoracíon GENERAL!C2 -> Cardiovascular!J4 -> Cardiovascular!H4 -> Cardio-Hábitos!P3 -> Cardio-Hábitos!N3 -> Cardio-Hábitos!M3 -> Cardio-Hábitos!G3 -> Cardio-Hábitos!E5 -> Cardio-Hábitos!D5 -> Cardiovascular!D3 -> internal error' in /var/www/vhosts/herrian.com/httpdocs/pruebas/Classes/PHPExcel/Cell.php:291 Stack trace: #0 /var/www/XXX/XXX.es/httpdocs/XXX/XXX.php(223): PHPExcel_Cell->getCalculatedValue() #1 {main} thrown in /var/www/vhosts/herrian.com/httpdocs/pruebas/Classes/PHPExcel/Cell.php on line 291
```
DEBUG FILE:
    [191] => GENERAL_Autocompletado!F58 -> GENERAL_Autocompletado!B34 -> Valoracíon GENERAL!E9 -> Valoracíon GENERAL!E2 -> Valoracíon GENERAL!C2 -> Cardiovascular!J4 -> Cardiovascular!H4 -> Cardio-Hábitos!P3 -> Cardio-Hábitos!N3 -> Cardio-Hábitos!M3 -> Cardio-Hábitos!G3 -> Cardio-Hábitos!E5 -> Cardio-Hábitos!D5 -> Cardiovascular!D3 => Evaluation Result for cell **DU00004** is a NULL value

DU00004 -> Range

THANKS

**Comment by PowerKiKi** [comment]
Please provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) of code that exhibits this issue. And don't forget to mention what version of this project you are using. That way there will be more chance for the issue to be solved.
