### ISSUE TITLE
Can PHPExcel be used in client-side?

### ISSUE THREAD

**Issue by chengtie** [PHPOffice/PHPExcel#1009]
If it is written in PHP, I guess it is supposed to be used only in server-side?

Cheers

Tie

**Comment by lahdekorpi** [comment]
What do you mean by client-side? The browser?
Then obviously you can't.

A standalone application? You could theoretically pack it in with PHP and the required extensions. But probably there is a better library for that use case.

**Comment by chengtie** [comment]
I mean "standalone application" or "desktop application". Will that be complicated to do with PHPExcel? Do you have any better library to recommend?

Cheers
