### ISSUE TITLE
After composer install there is a problem

### ISSUE THREAD

**Issue by tasselchof** [PHPOffice/PHPExcel#1011]
Hello!

Fatal error: Cannot declare class PHPExcel_IOFactory, because the name is already in use in /home/***/domains/***/vendor/phpoffice/phpexcel/Classes/PHPExcel/IOFactory.php on line 37

**Comment by PowerKiKi** [comment]
what was that sentences about composer remove and require ?

do you `require()` any PHPExcel files in your code ?

**Comment by tasselchof** [comment]
Removed comment about require.

No, I am using only composer to autoload classes.

**Comment by tasselchof** [comment]
Seems like I used branch with other namespaces and it's making a conflict.

**Comment by PowerKiKi** [comment]
If you want namespace, you should use https://github.com/PHPOffice/PhpSpreadsheet, but you'll have to setup a custom repo for composer since that version is not yet released. Otherwise you'll have to use latest stable, 1.8.1, not a branch.
