### ISSUE TITLE
Rework date/currency-formating, currently only English format is given

### ISSUE THREAD

**Issue by Quix0r** [PHPOffice/PHPExcel#1016]
Currently only English formats are supported and all date-formatted columns are being converted to a numeric representation. This causes some problems if you rely on such values.

I would recommend rewriting this to a more flexible approach (e.g. over PHP's DateFormatter class) to avoid such data loses.

I currently get the value with `$cell->getValue()`, maybe I can try to use `$cell->getFormattedValue()` and pre-set "my custom" date format (it is the German format dd.mm.YYYY) before getting the value.

**Comment by MarkBaker** [comment]
Minimum requirements for the IntlDateFormatter class: `(PHP 5 >= 5.3.0, PHP 7, PECL intl >= 1.0.0)` which requires forcing PHPExcel minimum version to 5.3, and ensuring that the relevant extensions are enabled

**Comment by Quix0r** [comment]
Then let's dump those old versions of PHP <5.3 as they are EOL anyway: http://php.net/eol.php

**Comment by MarkBaker** [comment]
Talking about dropping support for PHP 5.2 is the type of thing that gets me death threats (seriously).... though you may be aware that we've been porting all the code across to PHPSpreadsheet, and rewriting swathes of it for PHP >= 5.5

**Comment by Quix0r** [comment]
Here are some test files:
https://owncloud.mxchange.org/index.php/s/us4RBigNqaqMdiO

Try to convert them with PHPExcel to XLSX (none of them has that format) as I basically do here and compare the results with the original files.

**Comment by Quix0r** [comment]
So PHPExcel is out-dated? I may then have 2 options:
- write a work-around that keeps track of each column's type and format so it can be set correctly again (bad, hard to maintain)
- rewrite my whole application to PHPSpreadsheet (may take really long to become as before)

Is there any other advantage than having a more updated code? E.g. speed improvement or memory footprint?

**Comment by Quix0r** [comment]
Here is my work-around:
- added database column (`tinyint(1)`): 1= is date, 0= is other <- this tracks which column is a date and needs converting
- used regex to check for German date-format
- if valid, handle it over to `PHPExcel_Shared_Date::stringToExcel()` for converting
- if no German date (such as the same float value `stringToExcel()` returns) use the value directly for next step:
- save coordinate, value and format where to change format

A bit hacky but works (with my testing files I linked here).

**Comment by Quix0r** [comment]
That work-around of mine seems to work. Now only removal of leading zeros (e.g. ZIP code or phone numbers have leading zeros, like here in Germany) is left (OT).

**Comment by PowerKiKi** [comment]
PHPExcel will be out-dated when [PhpSpreadsheet](https://github.com/PHPOffice/phpspreadsheet) will be released. But it's not quite ready yet. Porting to PhpSpreadsheet should mostly be renaming class names (to include namespaces), so it should not be too much work.

**Comment by Quix0r** [comment]
Thank you for clarification. It whould be still good to have a migration guideline (how to switch) for an easy (and hopefully painless) move.

**Comment by PowerKiKi** [comment]
Sure, we might even have a basic tool to help with some part of migration. But it's still a bit early for that...

**Comment by Quix0r** [comment]
Looks like the migration tool has been written. And I have taken @MarkBaker 's advice to write an own (custom) value binder, works nicely now. Closing ticket (please set proper status, maybe "WONT FIX"?)
