### ISSUE TITLE
Problema con apache y Windows Server 2012 R2 Standard

### ISSUE THREAD

**Issue by jorddyrojas** [PHPOffice/PHPExcel#1020]
**Cuando intento arrancar apache24** en **Windows Server 2012 R2 Standard (x64)** me lanza un error 
> api-ms-win-crt-runtime-l1-1-0.dll no esta en el equipo
ya instale la reciente actualización para Microsoft Visual C++ 2015 Redistributable (x64), pero este al final de la instalación me lanzo un código de error 0x80240017
No se que hacer llevo tiempo buscando la solucion y nada!
Tambien intente con vcredist_x64 y nada.

**Comment by PowerKiKi** [comment]
This seems unrelated to this project

**Comment by jorddyrojas** [comment]
Tienes razón me equivoque! PowerKiKi
