### ISSUE TITLE
Problem with tildes

### ISSUE THREAD

**Issue by miguelangelss4** [PHPOffice/PHPExcel#1027]
Hello,
I have download this library and I'm not able to do work it with tildes.

for example, this example line:
`$objPHPExcel->setActiveSheetIndex(0)->setCellValue('R5', 'éàèùâêîôûëïüÿäöüç');`

Makes my R5 cell with the value of 'FALSE', and with all my other tries to use tiles it's the same...

thanks.

UPDATE: if you use utf8_decode($string), i can obtain the string with the tildes replaced by ? signs. That is closer I am to achive the tildes..

**Comment by NestorAcevedo** [comment]
I'd use `setlocale(LC_ALL, 'es_CO');` for instance before setCellValue or before assign a value to a string variable.

**Comment by MarkBaker** [comment]
Always use UTF-8; if the text isn't UTF-8 then use PHP's `iconv()` or `mb_*` functions to convert it to UTF-8

**Comment by miguelangelss4** [comment]
Thanks you both!
I solved my problem by using `$mysqli->set_charset('utf8');` before query for my data to be printed in the Excel, maybe I must change to your answers.
