### ISSUE TITLE
getDefaultStyle() and brothers are deprecated in favor of..... what?

### ISSUE THREAD

**Issue by igorsantos07** [PHPOffice/PHPExcel#1029]
I've noticed for quite some time that `getDefaultStyle()` got deprecated... I tried to find in the source or changelog alternative methods to set some common styles for the entire sheet, but it seems there's nothing similar, nor a tip on what to do.

Please, when functions get deprecated, describe in the PHPDoc the reason / what should be done instead. This kind of thing just leave the users lost. Just dropping a `@deprecated` is of little help :(

**Comment by PowerKiKi** [comment]
Instead of:
```php
$sheet->getDefaultStyle();
```

Use:
```php
$sheet->getParent()->getDefaultStyle();
```

Or more directly:
```php
$workbook->getDefaultStyle();
```
