### ISSUE TITLE
chart with excel 2016 not working

### ISSUE THREAD

**Issue by bombjack22** [PHPOffice/PHPExcel#1062]
Hello,

Since I have excel 2016, the charts not working.
Have you got any solution?

Thx

**Comment by PowerKiKi** [comment]
Please provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) of code that exhibits this issue. And don't forget to mention what version of this project you are using. That way there will be more chance for the issue to be solved.
