### ISSUE TITLE
[BUG] | Allowed memory size of 134217728 bytes exhausted

### ISSUE THREAD

**Issue by dannyZhou** [PHPOffice/PHPExcel#1067]
Env:
- PHP version: 5.6.13 
- OS: linux  

File: 
[Excel.zip](https://github.com/PHPOffice/PHPExcel/files/603051/a.zip)
Please extract it. 

Some useful information 
![screenshot from 2016-11-21 16-41-01](https://cloud.githubusercontent.com/assets/6329191/20475922/40af6ef0-b009-11e6-96ce-c38f010c610d.png)

Exception:
- [exception 'yii\base\ErrorException' with message 'Allowed memory size of 134217728 bytes exhausted (tried to allocate 72 bytes)' in /home/danny/projects/src/vendor/phpoffice/phpexcel/Classes/PHPExcel/Cell.php:857]

**Comment by MarkBaker** [comment]
PHPExcel uses PHP memory, which is limited by your php.ini file settings. It cannot magically load more data from a file than memory permits, although there are methods provided for caching cell data that reduce the memory requirements. Which of those methods are you using?

**Comment by dannyZhou** [comment]
@MarkBaker  this is patch. Please review. 

```patch

From 9d8794eb8d4ba8f3b47a210f355a45db37bd4d8f Mon Sep 17 00:00:00 2001
From: "danny.zhou" <dannyzhou@augmentum.com.cn>
Date: Mon, 21 Nov 2016 20:00:15 +0800
Subject: [PATCH] Fix sometimes memory exhausted

---
 Classes/PHPExcel/Worksheet.php | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/Classes/PHPExcel/Worksheet.php b/Classes/PHPExcel/Worksheet.php
index 483aa00..d712f78 100644
--- a/Classes/PHPExcel/Worksheet.php
+++ b/Classes/PHPExcel/Worksheet.php
@@ -2797,7 +2797,7 @@ class PHPExcel_Worksheet implements PHPExcel_IComparable
         $maxRow = $this->getHighestRow();
         $maxCol = PHPExcel_Cell::columnIndexFromString($maxCol);
 
-        $rangeBlocks = explode(' ', $range);
+        $rangeBlocks = explode(' ', str_replace('$', '', strtoupper($range)));
         foreach ($rangeBlocks as &$rangeSet) {
             $rangeBoundaries = PHPExcel_Cell::getRangeBoundaries($rangeSet);
 
-- 
2.10.2

```

**Comment by dannyZhou** [comment]
@MarkBaker Reference: https://github.com/PHPOffice/PHPExcel/blob/1.8/Classes/PHPExcel/Cell.php#L868

**Comment by MarkBaker** [comment]
I can understand what this does; but what is it actually a fix for?

**Comment by dannyZhou** [comment]
![screenshot from 2016-11-21 16-41-01](https://cloud.githubusercontent.com/assets/6329191/20482277/c86240e4-b026-11e6-96d2-38ca1c549b8c.png)

Actually I only have one cell data. (See [Excel.zip](https://github.com/PHPOffice/PHPExcel/files/603051/a.zip) )

See `sqref` of  `dataValidation`, when it has `$` for example like this, `F$1:F$1048576` , `Worksheet.php::shrinkRangeToFit` cannot compare with `maxRow` and `maxCol`.

`Worksheet.php::shrinkRangeToFit` will return `F$1:F$1048576` directly.

After this

In `Call::extractAllCellReferencesInRange`  https://github.com/PHPOffice/PHPExcel/blob/1.8/Classes/PHPExcel/Cell.php#L896
has a loop, it will loop from `1 -> 1048576`

**Comment by dannyZhou** [comment]
@MarkBaker  I am sorry I forget to tell you what methods I am using. 

```php
$phpreader = new \PHPExcel_Reader_Excel2007();
$phpexcel = $phpreader->load($filePath);
```

When execute `load`, memory exhausted occur.
