### ISSUE TITLE
PHPExcel_Shared_Date::PHPToExcel - Allow DateTimeImmutable Input

### ISSUE THREAD

**Issue by Alamei** [PHPOffice/PHPExcel#1070]
Would it be possible to modify the PHPToExcel function to support DateTimeImmutable as well as DateTime objects? I find myself working with the former more often than the latter, and their output interfaces (via the ->format function) are identical, so it only requires adjusting the check routine to allow instances of DateTime or DateTimeImmutable.

I know this is a minor feature request, since there are plenty of workarounds in place, but it's also relatively easy to implement.

**Comment by PowerKiKi** [comment]
This has been solved in [PhpSpreadsheet](https://github.com/PHPOffice/PhpSpreadsheet). It works with `\DateTimeInterface`, making possible the use of both `\DateTimeImmutable` or `\DateTime`.
