### ISSUE TITLE
XLSX files with japanese filenames are identified as HTML

### ISSUE THREAD

**Issue by a-n-dcruz** [PHPOffice/PHPExcel#1071]
I'm encountering a similar issue to [Issue#443](https://github.com/PHPOffice/PHPExcel/issues/443) but since it's already closed, I am creating a new thread. PHPExcel can read xls files with no issues but when it comes to xlsx files I encounter a weird behavior. 

I created a file using MS Excel 2013 then saved it twice. The first save I named "aaaa.xlsx" the second I named "画面.xlsx". Now when I try to read "aaaa.xlsx", it works okay but every time I try to read "画面.xlsx", I get the error: **DOMDocument::loadHTML():Invalid char in CADATA 0x3 in Entity, line: 1** When checking the output for the identify function, "aaaa.xlsx" is identified as type Excel2007 while "画面.xlsx" is identified as HTML. Basically they were created using the same program and they have the same contents, the only difference is the filename.

Additional info:
PHP version 7
PHPExcel version 1.8.1

Can someone give me suggestions in resolving this? Most of the files my project would be reading have japanese filenames. I've spent the last 3 days already figuring out why this is happening with no results.

**Comment by PowerKiKi** [comment]
Can't reproduce with only renaming the file name, it always get read correctly. Did you try saving as "aaaa.xlsx", rename the file as "画面.xlsx" and then read that ? Or the other way around ?

My guess is the filename doesn't matter, but the file content generated differs when saving with a different name for some reason. You should be able to identify if the file are exactly the same by producing a MD5 sum of them. On Linux/OSX, that would be the command:

```
md5sum aaaa.xlsx 画面.xlsx
```

**Comment by a-n-dcruz** [comment]
Yes, I tried renaming them both and the file renamed as aaaa.xlsx is read but 画面.xlsx still returns the same error. I've ran the md5sum command for both files and they are exactly the same so I still don't know what is going on.

**Comment by a-n-dcruz** [comment]
Further info, not sure if it helps:

I try to upload the xlsx files first into a folder called uploads then read the uploaded file. I am using UploadedFile extension on Yii2 Framework.

**Comment by PowerKiKi** [comment]
I assume you use `PHPExcel_IOFactory::load($pFilename);` to load your file. Did you double-check the value of `$pFilename` ? Is it actually correct and does `var_dump(is_readable($pFilename));` return `true` ?

Also what OS/filesystem are you on ?

**Comment by a-n-dcruz** [comment]
Yes, here's the exact snippet from my code:
`$encoded_filename = iconv('UTF-8', 'CP932', $filename);`
`$inputFileType = \PHPExcel_IOFactory::identify('uploads/' . $encoded_filename);`
`$objReader = \PHPExcel_IOFactory::createReader($inputFileType);`
`$objPHPExcel = $objReader->load('uploads/' . $encoded_filename);`

`var_dump(is_readable($pFilename));` -- Yes, this returns true.

My OS is Windows 7 64-bit.

**Comment by PowerKiKi** [comment]
I am suspicious about `$encoded_filename = iconv('UTF-8', 'CP932', $filename);`, I would argue that you shouldn't need it and keep everything UTF-8 at all times. But I don't enough about filesystem encoding to know for sure...

By default PHPExcel will use [PHP's ZipArchive](http://php.net/manual/en/ziparchive.open.php) to read XLSX files. There are several bug reports about filename encoding **within** the archive. This is not the same as you see here, but still, maybe changing the ZIP handler could help...

You should be able to do that with:

```php
\PHPExcel_Settings::setZipClass(\PHPExcel_Settings::PCLZIP);
```

**Comment by a-n-dcruz** [comment]
I used the iconv snippet for retaining the original filename when uploading the file. Without it, the filename turns to garbage characters.

Anyway, it seems that the encoding within the archive was the issue as well on my part. `\PHPExcel_Settings::setZipClass(\PHPExcel_Settings::PCLZIP);` fixed it.

Thanks!
