### ISSUE TITLE
Special Chars in filename and path

### ISSUE THREAD

**Issue by KedyCZ** [PHPOffice/PHPExcel#1078]
Hello

At first let me say, that PHPExcel is very usefull tool and i really like him.

Few hours ago i found a problem.
If I am trying to open files or directories, which names contains special characters used in my language, i've got this error: 

>  Fatal error: Uncaught exception 'PHPExcel_Reader_Exception' with message 'Could not open \\server-cz\01_pcz\14_Odkladaci_prostor\Lukáš Mouca\FO-R-03-048_Průvodka_dílu.xlsx for reading! File does not exist.'

Code is:
```
$path = '\\\\server-cz\\01_pcz\\14_Odkladaci_prostor\\Lukáš Mouca\\FO-R-03-048_Průvodka_dílu.xlsx';
$excel = PHPExcel_IOFactory::createReader('Excel2007');
$excel = $excel->load($path);
```

You can see that both, path and filename contains special chars like á, š, ů, í.
I am under company infrastructure, so i don't have any option, how to change file names or path names.

Is there any other way how to load file to PHPExcel even when i have special charachters?

Thanks for response.

**Comment by PowerKiKi** [comment]
I don't think this an a issue specific to PHPExcel, but rather an issue of filesystem encoding. As long as `file_exists($path);` returns `false`, PHPExcel can't do anything. You have to find out what encoding you should use in order for PHP to access the file properly. Then start worrying about PHPExel.

**Comment by KedyCZ** [comment]
Thank you for your advice, I've used iconv() to translate path from utf-8 to windows-1250. It seems this solved the problem.

My corrected code:
```
$path = '\\\\server-cz\\01_pcz\\14_Odkladaci_prostor\\Lukáš Mouca\\FO-R-03-048_Průvodka_dílu.xlsx';
$encodedPath = iconv("UTF-8", "Windows-1250", $path);
$excel = PHPExcel_IOFactory::createReader('Excel2007');
$excel = $excel->load($encodedPath);
```

Thank you very much. :-)
