### ISSUE TITLE
Read data from PDF

### ISSUE THREAD

**Issue by hrnmodi** [PHPOffice/PHPExcel#1082]
How to read data from PDF or is there anyway i can convert PDF to excel and then read data using PHPExcel Pls help me, I have attached PDF file from where I want to read data
[Ann Underdown.pdf](https://github.com/PHPOffice/PHPExcel/files/641475/Ann.Underdown.pdf)
?

**Comment by PowerKiKi** [comment]
There is now way to read PDF with PHPExcel.

**Comment by hrnmodi** [comment]
Is there any demo or example I can convert PDF to excel? after that I'll manage

**Comment by PowerKiKi** [comment]
No, there isn't, because there is no way to read PDF with PHPExcel.
