### ISSUE TITLE
break in functions file without a loop generating error

### ISSUE THREAD

**Issue by tombombadilll** [PHPOffice/PHPExcel#1084]
\PHPExcel\Calculation\Functions.php
There is a break on row 580 in this file that is an error:

} elseif(is_array($value)) {
	return 64;
	break;
}

**Comment by MarkBaker** [comment]
Look at the latest develop branch, this has been resolved there for quite some time

**Comment by tombombadilll** [comment]
My bad then, downloaded the code from https://phpexcel.codeplex.com/ and saw the same version on github and didn't find any issue with the error.
Thanks!

**Comment by PowerKiKi** [comment]
@MarkBaker don't you have a way to manually remove all content from codeplex ? or at the very least the homepage ? it seems to bring more confusion than anything else...

**Comment by MarkBaker** [comment]
Sadly not; I've tried several times (it errors if I try it myself), and I've asked the codeplex people to do it as well, all without success... I'll try chasing them up again, see if perhaps I'll find somebody willing to do it this time

**Comment by PowerKiKi** [comment]
I meant more like edit it out, replace the text with blank lines. I suppose you still have editing access ?
