### ISSUE TITLE
getHighestDataColumn not doing whats expected?

### ISSUE THREAD

**Issue by SpringsTea** [PHPOffice/PHPExcel#1086]
I'm counting how many columns are in a sheet for validation purposes, heres the code:

`$highestColumn = $objWorksheet->getHighestDataColumn();`
`$highestNum = PHPExcel_Cell::columnIndexFromString( $highestColumn );`

I'v come across a few files that have invisible columns for whatever reason.
Heres an example offender:
[AMJ  UBD.xlsx](https://github.com/PHPOffice/PHPExcel/files/650184/AMJ.UBD.xlsx)

The file should have 4 columns to be valid, but theres an invisible fifth offender. Converting the file to a csv and opening in a text editor confirms the issue, where rows look like this:

`7 94213 10003 8,SUNSHINE BURGERS Garden Herb,365,180,,`

What data is in this file is getHighestDataColumn getting?
Is there any way around this besides highlighting the column and clearing it manually?

**Comment by MarkBaker** [comment]
It's getting an empty string, in the fifth column, which is still valid cell content as far as MS Excel is concerned

**Comment by SpringsTea** [comment]
My confusion comes from reading somewhere that "getHighestDataColumn() returns the highest column that contains actual data in the cell". If not for situations like this, when does this actually produce different results than getHighestColumn().

I guess I just don't know about how excel stores it's data. This would mean you can have a cell exist, but have no data, ie no empty string?

**Comment by MarkBaker** [comment]
That's correct. MS Excel treats an empty string, or a null as data in a cell, even though it looks empty to a human, it isn't empty to excel

**Comment by MarkBaker** [comment]
As for when `getHighestColumn()` and `getHighestDataColumn()` return different results... load your file and test the returned values of both functions, then add new data in cell `Z1` show the return values from both functions again

**Comment by SpringsTea** [comment]
ahh, I understand.
Ok, well thats lame. I guess I'll just check the cell data for blanks to verify.

**Comment by MarkBaker** [comment]
Another difference is that a cell in a loaded excel file can have styling, or be referenced in a print range or similar, but still be truly empty.... `getHighestColumn()` and `getHighestDataColumn()` can return different results in this case as well, because `getHighestColumn()` includes the reference, while `getHighestDataColumn()` ignores references, and looks to see if the cell actually exists
