### ISSUE TITLE
PHPExcel_Calculation_Exception whit STDEV.S function

### ISSUE THREAD

**Issue by DiegoDVG** [PHPOffice/PHPExcel#1092]
Hi, I have a prible with this Exception

`Fatal error: Uncaught exception 'PHPExcel_Calculation_Exception' with message 'DATOS!F4 -> internal error' in C:\xampp\htdocs\Classes\PHPExcel\Cell.php:291 Stack trace: #0 consulta.php(37): PHPExcel_Cell->getCalculatedValue() #1 {main} thrown in Classes\PHPExcel\Cell.php on line 291`

STDEV.S function 

https://support.office.com/en-us/article/STDEV-S-function-7d69cf97-0c1f-4acf-be27-f3e83904cc23?ui=en-US&rs=en-US&ad=US

**Comment by PowerKiKi** [comment]
Unfortunately STDEVS is not implemented in PHPExcel/PhpSpreadsheet as you can see there: http://phpspreadsheet.readthedocs.io/en/develop/references/function-list-by-name/#s. 

If you are willing to contribute an implementation for that, please do so in [PhpSpreadsheet project](github.com/PHPOffice/phpspreadsheet).
