### ISSUE TITLE
PHP7

### ISSUE THREAD

**Issue by gintsmurans** [PHPOffice/PHPExcel#1093]
Hi!

There seems to be a naming issue with String class. I am getting this error: Cannot use PhpOffice\PhpWord\Shared\String as String because 'String' is a special class name in .. Vendor/phpoffice/phpword/src/PhpWord/TemplateProcessor.php on line 23

**Comment by PowerKiKi** [comment]
This is the wrong project, please report to [PHPWord](https://github.com/PHPOffice/PHPWord).

**Comment by gintsmurans** [comment]
Ooh, sorry about that..
