### ISSUE TITLE
Hardcoded value in PHPExcel_Style_Border::getStyleArray()

### ISSUE THREAD

**Issue by Squee3P0** [PHPOffice/PHPExcel#1094]
The function PHPExcel_Style_Border::getStyleArray() currently looks like this:

```public function getStyleArray($array)
    {
        switch ($this->parentPropertyName) {
            case 'allBorders':
            case 'bottom':
            case 'diagonal':
            case 'horizontal':
            case 'inside':
            case 'left':
            case 'outline':
            case 'right':
            case 'top':
            case 'vertical':
                $key = strtolower('vertical');
                break;
        }
        return $this->parent->getStyleArray(array($key => $array));
    }
```

which causes code like:
`$phpexcel->getActiveSheet()->getStyle('A1:B1')->getBorders()->getBottom()->setBorderStyle(PHPExcel_Style_Border::BORDER_MEDIUM)`
 to set medium vertical borders instead of bottom borders.  This can be fixed by making the following change to the function:

```public function getStyleArray($array)
    {
        switch ($this->parentPropertyName) {
            case 'allBorders':
            case 'bottom':
            case 'diagonal':
            case 'horizontal':
            case 'inside':
            case 'left':
            case 'outline':
            case 'right':
            case 'top':
            case 'vertical':
                $key = strtolower($this->parentPropertyName);
                break;
        }
        return $this->parent->getStyleArray(array($key => $array));
    }
```

It appears that issues #959 and #836 are both caused by this problem.  A work around is to use code like:
`$phpexcel->getActiveSheet()->getStyle('A1:B1')->getBorders()->applyFromArray(array('bottom' => array('style' => PHPExcel_Style_Border::BORDER_MEDIUM)))`
which bypasses the faulty function above.  Note however that you must call applyFromArray() after getBorders() and not getBorders()->getBottom() because the latter **WILL** result in a call to the faulty function above.

**Comment by PowerKiKi** [comment]
In latest version, `PHPExcel_Style_Border::getStyleArray()` [doesn't look like what you described](https://github.com/PHPOffice/PHPExcel/blob/372c7cbb695a6f6f1e62649381aeaa37e7e70b32/Classes/PHPExcel/Style/Border.php#L150-L175).

Please downgrade to a stable release, or if you really need bleeding edge, upgrade to [PhpSpreadsheet](https://github.com/PHPOffice/phpspreadsheet#phpexcel-vs-phpspreadsheet-).
