### ISSUE TITLE
PHP7 compability bug (minor)

### ISSUE THREAD

**Issue by freiwerk** [PHPOffice/PHPExcel#1095]
Hi there,

I just upgraded my webspace to PHP7 and got the following error:

> Fatal error: 'break' not in the 'loop' or 'switch' context in PHPExcel/Calculation/Functions.php on line 581

Indeed, the break statement should not be there and older PHP versions probably ignored this issue. I simply removed the break statement and the issue was gone... Just wanted to let you know.

Thanks for your work in this great software,
freiwerk

PS: My Firefox showed a virus affection when downloading the new version of PHPExcel from here... Probably there is a way to avoid this...

**Comment by PowerKiKi** [comment]
#642

**Comment by freiwerk** [comment]
Thanks. Just wanted to let you know that the default branch is 1.8. here - would be good if it would be 1.8.1 (this is why the upgrade to the "latest" version didnt solve my issue)...

**Comment by PowerKiKi** [comment]
You should only use in production [tagged releases](https://github.com/PHPOffice/PHPExcel/releases), or better yet use composer to install your dependencies.
