### ISSUE TITLE
Phpexcel doesn't update related data in another worksheet

### ISSUE THREAD

**Issue by sdespont** [PHPOffice/PHPExcel#1099]
I am using PHPExcel 1.8 with 2 worksheets.

Worksheet number 1 is a summary page and worksheet 2 a list of articles with details and amounts.

Worksheet 1 has several references on specifics cells in worksheet 2.

When using `insertNewRowBefore` methods in worksheet 2 to create the list of articles, the references on related cells in worksheet 1 is not updated.

Cells references are well updated in the same worksheet, but it seems that a limitation exists if cells are referenced in other worksheet.

[Documentation ](http://www.osakac.ac.jp/labs/koeda/tmp/phpexcel/Documentation/API/PHPExcel_Worksheet/PHPExcel_Worksheet.html#methodinsertNewRowBefore) says that all possible related data are updated.

Is it a bug? A limitation? Or is there a way to do it?

**Comment by MarkBaker** [comment]
It's a limitation at the moment... it' a fairly intensive and slow piece of processing to check and do those updates on the same worksheet, so a conscious decision was made not to do so on all worksheets when it would really slow performance

**Comment by sdespont** [comment]
Ok, I understand. 

You should specify this limitation in the documentation.

Thank you for your quick answer.

**Comment by PowerKiKi** [comment]
@sdespont please submit a PR to improve the documentation as you see fit on [PhpSpreadsheet](https://github.com/PHPOffice/phpspreadsheet#phpexcel-vs-phpspreadsheet-) project.
