### ISSUE TITLE
extra row at the end of the generated document

### ISSUE THREAD

**Issue by kedwin** [PHPOffice/PHPExcel#1102]
Writer/HTML.php

function generateSheetData

$html .= $this->extendRowsForChartsAndImages($sheet, $row);

this adds extra row to the end of the document
resulting an empty bordered cell if you export it in pdf

<tr><td></td></tr>

![screenshot from 2017-01-03 16-23-19](https://cloud.githubusercontent.com/assets/10922690/21612325/fa6a1e4c-d1d0-11e6-8e48-6076f0268e30.png)

**Comment by PowerKiKi** [comment]
Please provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) of code that exhibits this issue. And don't forget to mention what version of this project you are using. That way there will be more chance for the issue to be solved.
