### ISSUE TITLE
Issues upgrade PHP 7.0 to 7.1

### ISSUE THREAD

**Issue by LambrechtsGregory** [PHPOffice/PHPExcel#1103]
We're having some issues with our excel generation after upgrading from PHP 7.0 to 7.1. It seems that the problem locates somewhere in the stringFromColumnIndex (line 835 in 1.8) method. Our best guess is that there might be an issue with the chr method on decimal numbers in 7.1 but not completely sure unfortunately. We've downgraded to 7.0 and we got the functionality working again. Is there anyone who had this problem before and might have found a solution? Thank you in advance!

![screen shot 2017-01-03 at 16 33 25](https://cloud.githubusercontent.com/assets/5636968/21612754/b9c1c28a-d1d2-11e6-8774-6bf809e6a936.png)

**Comment by PowerKiKi** [comment]
Not the answer you are looking for but PHPExcel does not and will never support PHP 7.1. Instead you might want to try [PhpSpreadsheet](https://github.com/PHPOffice/phpspreadsheet#phpexcel-vs-phpspreadsheet-). But even that one has a few tests that does not pass on PHP 7.1. Any help is welcome though...

**Comment by mnvx** [comment]
@MarkBaker Are there really no plans to support PHP 7.1?

**Comment by PowerKiKi** [comment]
@mnvx, no there is no plan, PHPExcel is not supported anymore

**Comment by mnvx** [comment]
@PowerKiKi Thanks for information. Also I found that new branch of Maatwebsite/Laravel-Excel use PhpSpreadsheet: https://github.com/Maatwebsite/Laravel-Excel/blob/3.0/composer.json#L25
