### ISSUE TITLE
PHPExcel and office 2016

### ISSUE THREAD

**Issue by max21** [PHPOffice/PHPExcel#1107]
I'm currently using PHPExcel (v1.8.0) to generate an xlxs file with datas and graph. But when I open my generated document in office I get an error. I've tried to precise the orientation with the "setPlotDirection" method, and delete the y axis label.

This is the code :

```php
$categories = array(
                new \PHPExcel_Chart_DataSeriesValues('String', "'".$this->oSheet->getTitle()."'!\$A$5:\$A$31", null, 1)
            );
            $values = array(
                new \PHPExcel_Chart_DataSeriesValues('Number', "'".$this->oSheet->getTitle()."'!\$BA$5:\$BA$31", null, 1),
            );
            $this->createChart($categories, $values, 'Title', 'Xlegend', 'YLegend', 'A34', 'K50');
    
    function createChart($categories, $values, $title, $xLegnd, $yLegend, $topLeft, $bottomRight)
        {
            $series = new \PHPExcel_Chart_DataSeries(
                \PHPExcel_Chart_DataSeries::TYPE_BARCHART,
                \PHPExcel_Chart_DataSeries::GROUPING_STANDARD,
                range(0, count($values) - 1),
                null,
                $categories,
                $values
            );
    
            $series->setPlotDirection(PHPExcel_Chart_DataSeries::DIRECTION_VERTICAL);
    
            $layout = new PHPExcel_Chart_Layout();
            $layout->setShowVal(true);
    
            $plotArea = new \PHPExcel_Chart_PlotArea(null, array($series));
            $title = new \PHPExcel_Chart_Title($title);
            $yAxisLabel = new \PHPExcel_Chart_Title($yLegend);
            $xAxisLabel = new \PHPExcel_Chart_Title($xLegnd);
            $chart = new \PHPExcel_Chart(
                $title,
                $title,
                null,
                $plotArea,
                true,
                0,
                null,
                $yAxisLabel
            );
    
            $chart->setTopLeftPosition($topLeft);
            $chart->setBottomRightPosition($bottomRight);
            $this->oSheet->addChart($chart);
        }
```

All works fine with Excel 2010/2011 and Libre Office. But I get this error with Excel 2016 :

`
    <recoveryLog>
        <logFileName>error066200_01.xml</logFileName>
        <summary>Des erreurs ont été détectées dans le fichier « C:\Users\Altays\Desktop\Test excel rs enedis\RS Bilan RPCM - Campagne Pré campagne - 2017-01-11 17-33.xlsx »</summary>
        <removedParts>
            <removedPart>Partie supprimée: /xl/drawings/drawing3.xml partie.  (Forme de dessin)</removedPart>
        </removedParts>
    </recoveryLog>
`

Any idea ?
Thanks

**Comment by PowerKiKi** [comment]
Could you update to latest 1.8.1 and see if it still happens ?

And if it does please provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) of code that exhibits this issue. That way there will be more chance for the issue to be solved.

**Comment by max21** [comment]
I found the solution. The following line was the problem, anyone know why ?

`setlocale(LC_ALL, array('fr', 'fr_FR', 'french', 'fra', 'fra_FRA', 'fr_FR.utf8', 'fr_FR.utf-8', 'fra_FRA.utf8', 'fra_FRA.utf-8'));`

Thanks :)

**Comment by PowerKiKi** [comment]
Can you compare the broken file with the working file (after unzipping them) ? you may find the answer to your question...

**Comment by max21** [comment]
Thanks for your help.
All float in xml draws files are written with coma instead of dot.

For example with the setlocale :

` <c:pageMargins b="0,75" footer="0,3" header="0,3" l="0,7" r="0,7" t="0,75"/>`

Without the setlocale :

`<c:pageMargins b="0.75" footer="0.3" header="0.3" l="0.7" r="0.7" t="0.75"/>`
