### ISSUE TITLE
xlsx identified as html

### ISSUE THREAD

**Issue by hawkthor** [PHPOffice/PHPExcel#1115]
PHPexcel v1.8.1
PHP v5.4.43
Apache/2.2.31
CENTOS 6.8 x86_64 virtuozzo

PXPExcel identifying  xlsx files as html (PHPExcel_IOFactory::identify($book1.xlsx)).
Runninig:
$objPHPExcel = PHPExcel_IOFactory::load("Book1.xlsx");
gives the error:
"DOMDocument::loadHTML(): Invalid char in CDATA 0x4 in Entity, line: 1 in .../PHPExcel/Reader/HTML.php on line 495"

It was all working fine and about a week ago several PHP scripts on the same sever started failing for the reason described above.  It all works fine with .xls

The files that the different scripts are trying to read is created with unknown MS excel version so I created a test xlsx file in MS Office Professional Plus 2010 and it gives the same error. the test file is uploaded here (book1.xlsx

Does this look familiar to anyone? Do you Need more information to see what can be wrong?

All help is appriciated.

Thanks,

[Book1.xlsx](https://github.com/PHPOffice/PHPExcel/files/719924/Book1.xlsx)

**Comment by PowerKiKi** [comment]
Would you please try develop branch of https://github.com/PHPOffice/PhpSpreadsheet and see if latest commits changed anything for you ? I don't guarantee anything, but it is worth a try...

**Comment by hawkthor** [comment]
Unfortunately there was no time for more debugging, it was a production system that needed a fast fix and I switched to SpreadsheetReader.

I'm looking forward to the release of PHPSpreadsheet.
