### ISSUE TITLE
How do I can get data in number format not scientific notation format?

### ISSUE THREAD

**Issue by kepingatp** [PHPOffice/PHPExcel#1117]
Thanks for this awesome library, and your fast respond for my previous issue.  👍 

I've a **Transaction Id** column that contain data in _General_ format cell.
I've attach a screenshoot of my Excel file: 
![Excel File](https://cloud.githubusercontent.com/assets/20182181/22190308/0ffd533a-e155-11e6-8212-c4e998cf9ed6.PNG)

You can see above, if I input 15 characters of number and put two dots inside it. It will display normal number look like my input. 
**_First Ex_**: Input => 800.003.151476962 in cell showed as 
![image](https://cloud.githubusercontent.com/assets/20182181/22190410/968e1fd8-e155-11e6-9811-49603832b48b.png) 
and in **Formula Bar** showed as 
![image](https://cloud.githubusercontent.com/assets/20182181/22190416/a4a38a40-e155-11e6-9b88-a5c8eaae37fa.png)

But if input 15 characters of number without dots inside, it will displayed as **Scientific Notation** data format. **_Second Ex_**: Input => 800003151476925 in cell showed as
![image](https://cloud.githubusercontent.com/assets/20182181/22190486/0c2f68f0-e156-11e6-844c-2d2c35d536bf.png) => **Scientific Notation** data format
and in **Formula Bar** showed as
![image](https://cloud.githubusercontent.com/assets/20182181/22190529/4c19c6ea-e156-11e6-8c6b-ce4d10582598.png)

When I'm trying to read the data from my PHP, my PHP will read the **_Second Ex_** data as **Scientific Notation** format.
**How do I can get the _Second Ex_ data as _800003151476925_ not _8.00003E+14_ from my PHP?**

Thanks :)

**Comment by MarkBaker** [comment]
If you put 2 dots (decimal points) in a value, then it can only be a string; so MS Excel will format it `General` (the default cell formatting for MS Excel) as a string. With a single dot (decimal point), PHPExcel will treat it as a number, and set the datatype accordingly; and MS Excel will see it as a floating point number, and MS Excel `General` formatting rules will format it using scientific formatting if it is greater than a standard 32-bit integer size, treating it as a float.

If you want to force string formatting, then you need to do so explicitly, either by setting it as a string datatype using `setCellValueExplicit()` to force it to be set as a string; or set a format mask other than `General` such as `0.00`

**Comment by kepingatp** [comment]
Thanks for the knowledge  👍 
I've try your suggestion, but I got nothing. Actually I'm not sure where I have to add the code.
If you want to check my code on [github,](https://github.com/kepingatp/vatOut/blob/master/backend/controllers/FakturOutController.php) may be you can tell me in which line number is the right line for add the code.
And if I `echo` the data of column A9 above, it will display 8.0000315147692E+14.

Thanks :)

**Comment by nathanc85** [comment]
Thanks @MarkBaker the ```
$worksheet->getStyle($entire_column)
      ->getNumberFormat()
      ->setFormatCode('0');
``` worked for me

**Comment by budhapirthi** [comment]
Thanks so much @MarkBaker.
