### ISSUE TITLE
Call ZipArchive on a project with phpexcel vendor throw notice

### ISSUE THREAD

**Issue by cirovargas** [PHPOffice/PHPExcel#1123]
On my project i have phpexcel installed as vendor;

In a moment i want to work with ZipArquive php class and with a 'new \ZIPArquive()' throw this notice:

> Use of undefined constant PHPEXCEL_ROOT - assumed 'PHPEXCEL_ROOT' in /var/www/project/vendor/phpoffice/phpexcel/Classes/PHPExcel/Shared/ZipArchive.php:31

I'm not work with phpexcel on this block code/controller

This is a Symfony3 project.

That's looks crazy lol

**Comment by PowerKiKi** [comment]
This should have been fixed in PhpSpreadsheet, because PHPEXCEL_ROOT was entirely removed to rely on composer autoloader instead. You should try it, but be aware that it is not stable yet.

**Comment by sebardo** [comment]
Same problem here ...
I update "liuggio/excelbundle" from 2.0 to 2.1 and all work well ... zip and excel.

Version 2.0 of "liuggio/excelbundle" use an old version of phpexcel with ZipArchive inside and PHPEXCEL_ROOT constant .

Thank for your help @cirovargas
