### ISSUE TITLE
Named Cell on coordinateFromString

### ISSUE THREAD

**Issue by alandoyle95** [PHPOffice/PHPExcel#1125]
coordinateFromString will error due to a named cell that contains a sheet name..

example:
error = `PHPExcel_Cell::coordinateFromString(''FLOW TABLE')`
 
cell name = 
`$'Flow Table, Mold and Caliper'.$C$8`
or
`$'Flow Table, Mold and Caliper'.$B$104:$I$130`

if you want an example file let me know.

**Comment by PowerKiKi** [comment]
I think it has been fixed in PhpSpreadsheet develop branch. Please give it a try and open an issue in PhpSpreadsheet with code to reproduce the error if it still persist.
