### ISSUE TITLE
Your requested sheet index: 0 is out of bounds. The actual number of sheets is 0  at version 1.8.1

### ISSUE THREAD

**Issue by xuefengyang** [PHPOffice/PHPExcel#1127]
this is exception 

An uncaught Exception was encountered

Type: PHPExcel_Exception

Message: Your requested sheet index: 0 is out of bounds. The actual number of sheets is 0.

**Comment by PowerKiKi** [comment]
It seems you are trying to access a sheet that does not exists. Probably when you are creating a Spreadsheet from scratch. Please provide more details on what you are trying to do, and I'll re-open the issue.
