### ISSUE TITLE
insertNewRowBefore(..., 0) causes error [v1.8.0]

### ISSUE THREAD

**Issue by elieux** [PHPOffice/PHPExcel#1128]
`insertNewRowBefore(..., 0)` causes the error below with v1.8.0, not sure if bug-worthy, feel free to close.

`Fatal error: Call to a member function detach() on a non-object in [...]/PHPExcel/PHPExcel/CachedObjectStorage/CacheBase.php on line 155`

**Comment by PowerKiKi** [comment]
We don't have time to support old versions unfortunately, closing.
