### ISSUE TITLE
PHP 7.0 compatibility

### ISSUE THREAD

**Issue by eehmke** [PHPOffice/PHPExcel#1129]
I use the wordpress plugin Status Tracking [(https://wordpress.org/support/plugin/order-tracking/)](url)
that has included PHPExcel 1.8.0. When running a PHP 7.0 compatibility checker on the plugin, several errors and warnings are reported. 
Next I replaced the PHPExel subdirectory in the plugin by the release 1.8.1. Most errors are not reported anymore, so have been resolved in version 1.8.1. Replacing the Calculation/Database.php file by the actual version solves one more error.

```
Here is what's left:
FILE: ../PHPExcel/Classes/PHPExcel/CachedObjectStorage/SQLite.php
FOUND 9 ERRORS AFFECTING 9 LINES
  63 | ERROR | Extension 'sqlite' is removed since PHP 5.4
  64 | ERROR | Extension 'sqlite' is removed since PHP 5.4
 108 | ERROR | Extension 'sqlite' is removed since PHP 5.4
 142 | ERROR | Extension 'sqlite' is removed since PHP 5.4
 166 | ERROR | Extension 'sqlite' is removed since PHP 5.4
 211 | ERROR | Extension 'sqlite' is removed since PHP 5.4
 236 | ERROR | Extension 'sqlite' is removed since PHP 5.4
 274 | ERROR | Extension 'sqlite' is removed since PHP 5.4
 276 | ERROR | Extension 'sqlite' is removed since PHP 5.4

```
```
FILE: ../PHPExcel/Classes/PHPExcel/Shared/OLE/PPS/Root.php
FOUND 0 ERRORS AND 1 WARNING AFFECTING 1 LINE
 1 | WARNING | File has mixed line endings; this may cause incorrect results

```

**Comment by PowerKiKi** [comment]
Can you please let me know what tool you used to check compatibility ?

**Comment by eehmke** [comment]
That is the PHP compatibility checker plugin in the WordPress plugin collection. 

Am 11. Februar 2017 04:29:35 MEZ schrieb Adrien Crivelli <notifications@github.com>:
>Can you please let me know what tool you used to check compatibility ?
>
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/PHPOffice/PHPExcel/issues/1129#issuecomment-279117825

-- 
Diese Nachricht wurde von meinem Android-Mobiltelefon mit K-9 Mail gesendet.

**Comment by PowerKiKi** [comment]
Can you please give a link to said plugin page ?

**Comment by eehmke** [comment]
https://de.wordpress.org/plugins/php-compatibility-checker/
Excuse me, I was on the road today.

**Comment by PowerKiKi** [comment]
Thank you, the underlying tool used is https://github.com/wimg/PHPCompatibility. We [dropped support for SQLite 2 in PhpSpreadsheet](https://github.com/PHPOffice/PhpSpreadsheet/commit/6e247c30d9e23e36072adef2d9ea265be9192b09). That should solve all remaining issues.
