### ISSUE TITLE
value of A in the cells instead of DB value

### ISSUE THREAD

**Issue by mattiasghodsian** [PHPOffice/PHPExcel#1133]
Im trying to create a .xls file but row A is not getting the data from the DB, all i get is value of A in the cells

```php
$this->objPHPExcel->setActiveSheetIndex(0)
    ->setCellValue('A1', 'ID')
    ->setCellValue('B1', 'Product Name')
    ->setCellValue('C1', 'Brand')
    ->setCellValue('D1', 'Option 1')
    ->setCellValue('E1', 'Option 2')
    ->setCellValue('F1', 'Option 3')
    ->setCellValue('G1', 'Stock')
    ->setCellValue('H1', 'Status');

$i = 2;
foreach ($this->get_products($data) as $key => $item) {
    foreach ($item['parent'] as $key => $parent) {
        $this->objPHPExcel->getActiveSheet()->setCellValue("A$i", utf8_encode($parent['ID']));
    }
    $i++;
}
```

**Comment by PowerKiKi** [comment]
From the description, it is not clear what result you are expecting, and what result you are actually seeing. Please clarify and provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) of code that exhibits the issue. Unfortunately the code provided cannot be run by itself.

**Comment by mattiasghodsian** [comment]
I updated my first post

**Comment by PowerKiKi** [comment]
Unfortunately, I still cannot run your code, please provide a **complete** code example that can be copy/pasted and run.
