### ISSUE TITLE
Invalid row at the end

### ISSUE THREAD

**Issue by jishvi** [PHPOffice/PHPExcel#1140]
An invalid row with a single cell is created while converting an excel to pdf using tcpdf as the renderer.
There is no problem when converting to any other formats. I have tried mpdf. But it didn't solve the issue.
![screenshot from 2017-03-01 17-57-01](https://cloud.githubusercontent.com/assets/10036266/23460009/ef3f6068-fea8-11e6-8b35-9a17abd6e16e.png)

**Comment by PowerKiKi** [comment]
Most likely fixed by https://github.com/PHPOffice/PhpSpreadsheet/commit/de5a04e4cbc83d6e1a7a4cdb1427873d07d861ae (because HTML is used to generate PDF)

**Comment by jishvi** [comment]
Thanks for the quick reply. As you said, HTML file generated is also having an extra cell. I can not use PHPSpreadsheet. It is not stable yet. So how do I integrate this code change into PHPExcel?

**Comment by jishvi** [comment]
It worked. Thanks.
