### ISSUE TITLE
Is it normal reading file process need time more than a minute?

### ISSUE THREAD

**Issue by kepingatp** [PHPOffice/PHPExcel#1141]
Hi.
I've an issue in my apps. If I have an Excel file that contain data with the highestcolumn = AA, and the highestrow = 2001, is it normal if the reading file execution time is 1 minute 35 seconds?

This is the code that I used to read:
```php
for ($row = 1; $row <= $highestRow; ++$row) {
                $rowData = $sheet->rangeToArray('A' . $row . ':' . $highestColumn . $row, NULL, TRUE, FALSE);
                if (!is_null($rowData[0][$col])) {
                    $arrayData[] = array_map(function($values) {
                        $tempArrayKey = [];
                        foreach ($values as $key => $value) {
                            $newKey = $key + 1;
                            $tempArrayKey[] = $newKey . '_' . $value;
                        }
                        return $tempArrayKey;
                    }, $rowData);                    
                }
            }
```

Thanks for this awesome lib :)
Thanks

**Comment by PowerKiKi** [comment]
It seems to me that you are calling `rangeToArray` way too many times. Either drop the `for` loop and keep `rangeToArray('A' . $row . ':' . $highestColumn . $row, ...)`, or keep the `for` loop and read only one row at a time with `rangeToArray('A' . $row . ':' . $row . $row, ...)`.

**Comment by PowerKiKi** [comment]
Also don't [cross-post](http://stackoverflow.com/questions/42546111/does-count-of-row-column-of-an-excel-file-that-contain-data-affect-its-read-fil). For support use only StackOverflow, not this issue tracker.
