### ISSUE TITLE
PHPExcel - Display each sheet on HTML output

### ISSUE THREAD

**Issue by lando212** [PHPOffice/PHPExcel#1143]
Hi,

Here's the scenario, a person uploads their spreadsheet to the website, I then want a 'Review Stage', where the user can look through the document on a webpage to just verify what they are uploading, but the uploads always contain more than one worksheet. Also, I need to be able to keep the formatting (cell colours, etc) and calculated values.

I'm trying to use PHPExcel to cycle through each sheet of the uploaded Workbook then display each sheet within an HTML page, but having a lot of problems.

It either displays all the sheets in one HTML page and you have to scroll through them all, or it just prints the first page the amount of times there is a sheet present.

I would post my current code, but I don't see much point as I've been going back and forth with different solutions and I've just ended up back to a basic upload where one sheet is shown.

Has anyone tried to do this and if so, did you manage to get it to work?

Any help would be greatly appreciated.

Thanks in advance!

**Comment by MarkBaker** [comment]
Are you using PHPExcel's HTML Writer at all? If so, how?

**Comment by lando212** [comment]
Hi Mark, 

Yes, I should have pointed out I'm very new to this, so I've not altered the HTML Writer, I was just using it as such...

`            $i = 0;
                while ($objPHPExcel->setActiveSheetIndex($i)){

                $objWorksheet = $objPHPExcel->getActiveSheet();
                $objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'HTML');
                $objWriter->save('php://output');
                $i++;

            }`

**Comment by MarkBaker** [comment]
Why don't you tell the HTML Writer to write all sheets in one output:
```php
$objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'HTML');
$objWriter->writeAllSheets();
$objWriter->save('php://output');
```
rather than looping through the individual sheets

**Comment by lando212** [comment]
Hi Mark, thanks for this, but won't that just write all the sheets to one HTML page, which would be fine if I had some way to separate them, with a tab or something.

Even if there was some way to separate each sheet into a separate DIV I could then handle them separately within the page I think?

**Comment by MarkBaker** [comment]
Yes, it will write them all to one page, but in an integrated manner (tabbed, like MS Excel shows them); unlike writing each sheet individually in a loop, which display them one after the other..... but why don't you simply try it for yourself and see if it's what you want.

**Comment by lando212** [comment]
Ok, I'll give that a try and let you know, thanks very much for your help Mark.

**Comment by lando212** [comment]
Hi Mark, just to give you a quick update, that's a lot closer to what I'm looking for, but it's still putting all the sheets on the same page, but it just puts a list of hyperlinks at the top of the page so you can jump to the correct sheet. 

But you've definitely pointed me in the right direction as I assume I can now edit the HTML.php file to display the output the way I'd like it.

Thanks again for your help!

**Comment by MarkBaker** [comment]
Personally, I'd create my own custom writer based on the HTML Writer (perhaps extending it, so you still have access to the core logic), rather than editing the existing HTML Writer

**Comment by ReinierB** [comment]
Hi Lando212,
I worked on the same requirement yesterday. 

I found the solution on: 
https://docs.typo3.org/typo3cms/extensions/phpexcel_library/1.7.4/manual.html#_Toc237519966

My testing code in Laravel 5.4:

    Route::get('/xls', function() {
        //this works (native PHPExcel), it does not work with the maatwebsite object:
        $template = base_path().'/excel_templates/report.xlsx';

        $ReadObj = new PHPExcel_Reader_Excel2007();
        $objPHPExcel = $ReadObj->load($template);

        $sheet = $objPHPExcel->getActiveSheet();
        $sheet->getCell('B2')->setValue('Reinier');
        $sheet->getCell('B3')->setValue('Bastiaan');
        $sheet->getCell('G7')->setValue('Same text');

        $objPHPExcel->setActiveSheetIndexByName('data');
        $sheet = $objPHPExcel->getActiveSheet();
        $sheet->getCell('B2')->setValue('DATA');
        $sheet->getCell('B3')->setValue('More information here');
        $sheet->getCell('G7')->setValue('Say hi');

        $writeObj = new PHPExcel_Writer_HTML($objPHPExcel);
        //to do: define in system vars the sheet names to report to the customer
        //$writeObj->writeAllSheets();
        //$output = $writeObj->generateHTMLHeader();
        $output  = "Here is a first line of text<br><br>";
        $writeObj->setSheetIndex(0);
        $output .= $writeObj->generateStyles(true);  // write <style> and </style>
        $output .= $writeObj->generateSheetData();        //$writeObj->save('php://output');
        $output .= "Another line of text<br><br>";
        $writeObj->setSheetIndex(1);
        //$output .= $writeObj->generateStyles(true);  // write <style> and </style>
        $output .= $writeObj->generateSheetData();
        //$writeObj->save('php://output');
        $output .= "This is the last line of text";
      //  $output = htmlspecialchars($output);
        //$output .= $writeObj->generateHTMLFooter();

        return view('report.output',array('output'=> $output));
    });

I have this issue to resolve: the generateStyles(true) seems to use the style of the SheetIndex(0) (the first), the second generateStyles() does not take the formatting of the second sheet. Furthermore, the CSS code of the master blade overrides the CSS code that in the $output.
