### ISSUE TITLE
cannot generate excel  file

### ISSUE THREAD

**Issue by junphp** [PHPOffice/PHPExcel#1144]
Hi

when i generate excel file, i just get screen like this.
(around 1000 rows I can generate excel file , but more than 7000 rows this issue occurred)
Please help.

�hPv��±��u�j���R������}�Cv��PKecJ�78�K_rels/.rels���j�0��{ �{���1F�^ʠ�2��l�$���-}�y����Î��O��v�y�;�؋Ӱ.JP��޵^�����Yű�3G�Ww�g)���>�qQC��D���b!�]�i$L��3����2n���oT�:Z �h����[��4�ი��]��yN�,ە�>�>�j -' V�)�#��EF^6��n���8q"K��H��>_ׄ����eƏ�<⇄�Ud�v�� T�PKecJ�$�V��xl/_rels/workbook.xml.rels���j�0D�� ��ZvZJ)�s)�\[����LlIh7m��UH��Ĭؙ�H���8�OL���*J�M���|4��g��[=� &$��w�74�r}$�M<)p��EJ2GME���MҨ9��ɨ�^w(We�$���O�� ��V �)��C��_�9���J�$���/�:dG]d���WK�s��s��<�[�V�tB��)?�����0_!��!��4�E�ǩy���PKe

this is my code

       // Create new PHPExcel object
         $objPHPExcel = new PHPExcel();
         $objDrawing = new PHPExcel_Worksheet_Drawing();

     // Set properties
        $objPHPExcel->getProperties()->setCreator("test")
                             ->setLastModifiedBy("test")
                             ->setTitle("test")
                             ->setSubject("test")
                             ->setDescription("test")
                             ->setKeywords("test")
                             ->setCategory("test");

       $objPHPExcel->setActiveSheetIndex()
            ->setCellValue("A1", "Season")
            ->setCellValue("B1", "Whse")
            ->setCellValue("C1", "Cust")
            ->setCellValue("D1", "DIV")
            ->setCellValue("E1", "Item")
            ->setCellValue("F1", "Style");
       $i=2;
       foreach(.....as r1 ){

        $objPHPExcel->setActiveSheetIndex()
                        ->setCellValue("A$i", "$picture_link")
                        ->setCellValue("B$i", "$r1[whse_cod]")
                        ->setCellValue("C$i", "$r1[item_team_cod]")
                        ->setCellValue("D$i", "$r1[item_div_cod]");
          $i++;
      }

       $objPHPExcel->getActiveSheet()->setTitle("test");

      // Set active sheet index to the first sheet, so Excel opens this as the first sheet
        $objPHPExcel->setActiveSheetIndex();

       header('Content-Disposition: attachment;filename="list.xlsx"');
       header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
      header('Cache-Control: max-age=0');
       ob_clean();
       $objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel2007');
       $objWriter->save('php://output');
      exit;

**Comment by TaurusQ** [comment]
I have the same problem,is there any solution?

**Comment by PowerKiKi** [comment]
This may be PHP timing out before it could send everything. Try to increase PHP `max_execution_time` or speed up the file generation somehow (less data, or more efficient).

**Comment by junphp** [comment]
check white space in your code. error reads your code white space make xml error.
