### ISSUE TITLE
Units in PHPExcel / excel do not match / unknown coversions happening ?

### ISSUE THREAD

**Issue by startas** [PHPOffice/PHPExcel#1146]
What kinds of units is PHPExcel using for various measurements ? I.e., print margins, column width units do not match with excel, i set print left margin to 0.2 in PHPExcel, and in excel it shows me 0.5 (this one might be inches versus centimeters ?), and i set column width to 5, and in excel it shows me 4.29 ?

**Comment by EnVy28** [comment]
Hello fellow human,

Are you also experiencing some random column width resize?
Also what version of excel are you using? (I'll guess, office 365?)

PS: I'm not a contributor or something, I'm also looking for answers, in fact.

**Comment by MarkBaker** [comment]
There's a section of the [PHPExcel Docs ](https://github.com/PHPOffice/PHPExcel/blob/develop/Documentation/markdown/Overview/08-Recipes.md#setting-a-columns-width)that tries to explain the units used for measurements

**Comment by PowerKiKi** [comment]
([see here](http://phpspreadsheet.readthedocs.io/en/develop/topics/recipes/#setting-a-columns-width) for a slightly better formatting)
