### ISSUE TITLE
Out of Memory with XLSM

### ISSUE THREAD

**Issue by AdriWild** [PHPOffice/PHPExcel#1150]
Every time I try to load a file XLSM, creates and Out of Memory exception, I set the memory limit on 1Gb, but nothing happens.

**Comment by PowerKiKi** [comment]
Did you try that https://github.com/PHPOffice/PHPExcel/blob/1.8/Documentation/markdown/Overview/04-Configuration-Settings.md#cell-caching ?

**Comment by AdriWild** [comment]
Yes I've tried all of them but the problem is when they contains macros, if I open the file with Excel, and I save it as a .xls works perfectly. Then I guess it is a problem of file excel version.
