### ISSUE TITLE
Corrupt XLSX when generating large files

### ISSUE THREAD

**Issue by codreanulaurentiu** [PHPOffice/PHPExcel#1153]
Whenever I try to generate a large file (>6k rows and 30 columns, 10 of which are drop down lists), Microsoft Excel detects it as being corrupt. I have tried to set formulas as plain text (e.g. 'Item A,Item B,Item C') or a range A6:10, as well as defining a namedRange. Without data validation, the xlsx file is alright.

**Comment by PowerKiKi** [comment]
Is it a PHP timeout issue ?

**Comment by codreanulaurentiu** [comment]
Unfortunately no, actually i increased the memory using a swp file to write on the disk just to avoid oom problems (and this is done asynchronous so the browser doesn't cut my connection either). The problem from I can tell is the fact that XLS doesn't know how to handle >60k data validations and i haven't found a way to use cell ranges for data validations instead of single cells

**Comment by Khigashiguchi** [comment]
having same problem

**Comment by irusev** [comment]
I have similar and very interesting problem. PHPExcel was generating a corrupted file few days ago against out production database and now it's generating a valid, readable file agains the same database with more records (increased during the last few days). 

I've looked at any possible writings talking about corrupted XLS file produced by PHPExcel, but all the suggestions like putting exit; ob_clean(); different content-length or content-type didn't work.

Say we had 35000 records at Jan 15 and I was getting the corrupted file. I tried to filter the report, producing only 34000 of them and it worked fine. I tried the other 1000 and it also worked fine. Few days later, I had 36000 and they also worked fine - without filtering. However, if I restore a backup of the time then I had exactly those 35000, it is still failing.

Not sure what's going on, but I'm pretty confident it's a bug in PHPExcel, which is showing under very specific circumstances. If anyone has suggestions how to debug or troubleshoot that, let me know - I have a consistent reproducible pattern.

**Comment by PowerKiKi** [comment]
@irusev switch to HTML writer, comment out `header()` and triple-check that the HTML is valid and does not contains any PHP notice/warning/error.

Also consider moving to PhpSpreadsheet. This will probably not solve your issue, but you should anyway at some point...

**Comment by irusev** [comment]
Thanks for the answer, @PowerKiKi. The html didn't show any php warnings/errors. I'll follow your advice and move to PhpSpreadsheet at some point :)
