### ISSUE TITLE
Excel 2007 reader incorrect changing number format

### ISSUE THREAD

**Issue by msukhov** [PHPOffice/PHPExcel#1155]
Following code change the number format incorrectly in some cases:
```
if ((int)$xf["numFmtId"] < 164) {
   $numFmt = PHPExcel_Style_NumberFormat::builtInFormatCode((int)$xf["numFmtId"]);
}
```

For example I've the currency suffix 'р.' in sheet, but mentioned code change the suffix to '$'.
Please see XLSX attached for details.
[crn_suffix.xlsx](https://github.com/PHPOffice/PHPExcel/files/854986/crn_suffix.xlsx)

**Comment by PowerKiKi** [comment]
It seems like your excel file _may_ have been wrongly generated. Where does it come from ?

**Comment by MarkBaker** [comment]
The formal standard for OfficeOpenXML reserves all number format Ids below 164 for Microsoft use only, but not all of those are used, and there are some third party writers that abuse this and use those "gaps"... this is already covered in develop branch code, where the lines you quote have been replaced by

```
// We shouldn't override any of the built-in MS Excel values (values below id 164)
//  But there's a lot of naughty homebrew xlsx writers that do use "reserved" id values that aren't actually used
//  So we make allowance for them rather than lose formatting masks
if ((int)$xf["numFmtId"] < 164 && PHPExcel_Style_NumberFormat::builtInFormatCode((int)$xf["numFmtId"]) !== '') {
    $numFmt = PHPExcel_Style_NumberFormat::builtInFormatCode((int)$xf["numFmtId"]);
}
```

**Comment by msukhov** [comment]
Most probably this file wrongly generated (unable to check this point)...
But MS Excel 2013 displays the suffix from XLSX-file, instead of standart one.
OO Calc displays 'р.' as well.

**Comment by PowerKiKi** [comment]
Closing as per Mark's comment (he was talking about 818413e). The solution being to use PhpSpreadsheet develop branch for now
