### ISSUE TITLE
Parsing the currency format issue

### ISSUE THREAD

**Issue by msukhov** [PHPOffice/PHPExcel#1156]
`$format` argument of toFormattedString in NumberFormat.php may contains UTF characters.

For example:
`_-* #,##0.00_р_._-`

When the spacing characters removed from this argument by code 
```
$format = preg_replace('/_./', '', $format);
```
, we may get wrong UTF-8 string in `$format`. So following `preg_replace( '/.../u' ... )` may return NULL instead correct result.

Will it be correct to change the code line above to:
```
$format = preg_replace('/_./u', '', $format);
```
?

**Comment by PowerKiKi** [comment]
Please consider contributing a PR to PhpSpreadsheet develop branch. PHPExcel is not maintained anymore, and all debugging/contributing should be done with PhpSpreadsheet instead.

**Comment by msukhov** [comment]
Ok
