### ISSUE TITLE
Error loading file "phpoYGi50": Cell coordinate can not be zero-length string

### ISSUE THREAD

**Issue by patelleena57** [PHPOffice/PHPExcel#1159]
Hello all,

I am trying to Import excel file using PHPExcel.

It is working fine in some cases.

But when i import excel file which is exported from datatable It gives this error.
Error loading file "phpoYGi50": Cell coordinate can not be zero-length string

Any help to figure out the issue and solution will be appreciated.

Thanks in advance
Leena

**Comment by PowerKiKi** [comment]
Will be hard to help without more info. It may be because the file is
wrongly generated. You may also try PhpSpreadsheet develop branch, that
*may* have fixed some bugs. But your description is way too vague to know
more. You'll probably do dig in the code and debug by yourself.
