### ISSUE TITLE
PHPExcel

### ISSUE THREAD

**Issue by shinijaQB** [PHPOffice/PHPExcel#1177]
Invalid year 1990 is shown when we give dob as 25-05-1988 in excel.  Any solutions?

**Comment by PowerKiKi** [comment]
Please provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) of code that exhibits this issue. And don't forget to mention what version of this project you are using. That way there will be more chance for the issue to be solved.

**Comment by shinijaQB** [comment]
Am using php 7.1 and excel 2007 version.

**Comment by PowerKiKi** [comment]
Please provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) of code that exhibits this issue.

**Comment by shinijaQB** [comment]
When I add dob in my excel as 12/01/1890 saving DOB in the table as the year 1990. 1900-01-05. Why this is happening?


In my code 

//  Get worksheet dimensions
                $sheet = $objPHPExcel->getSheet(0);
                $highestRow = $sheet->getHighestRow();
                $highestColumn = $sheet->getHighestColumn();
                //  Loop through each row of the worksheet in turn
                $headers = $sheet->rangeToArray('A' . 1 . ':' . $highestColumn . 1, NULL, TRUE, FALSE);
                if (!isset($headers[0][8]) || $headers[0][8] == "") {
                    $this->session->set_flashdata('field_empty_message', $this->lang->line('excel_field_empty_error'));
                    redirect('/excel/excel_upload');
                }
                $rowData = array();
                for ($row = 2; $row <= $highestRow; $row++) {
                    //  Read a row of data into an array
                    $rowData[] = $sheet->rangeToArray('A' . $row . ':' . $highestColumn . $row, NULL, TRUE, FALSE);
                }
                //  Insert row data array into your database of choice here
                $count = 1;
                $error_count = 0;
                foreach ($rowData as $row) {
                    $_tmp = array();
                    $cw_id = $_tmp['member_cw_id'] = $post['cw_id'];
                    $_tmp['membership_id'] = $row[0][0];
                    $_tmp['member_firstname'] = isset($row[0][1]) ? trim($row[0][1]) : '';
                    $_tmp['member_lastname'] = isset($row[0][2]) ? trim($row[0][2]) :'';
                    $_tmp['member_id'] = $row[0][3];
                    $dob = isset($row[0][4]) ? $row[0][4] : '';
                    if (isset($dob) && $dob != '' && $dob != NULL) {
                     $_tmp['member_dob'] = date('Y-m-d', PHPExcel_Shared_Date::ExcelToPHP($dob));

**Comment by PowerKiKi** [comment]
I cannot run this code because it depends on other variables and functions that do no exist. Can you please simplify your code to be **minimal** but complete ?

**Comment by MarkBaker** [comment]
MS EXcel doesn't support dates prior to 1st January 1900 (or 1904 if using the Excel for Mac Calendar)
