### ISSUE TITLE
Out of memory error

### ISSUE THREAD

**Issue by sijpkes** [PHPOffice/PHPExcel#1178]
I'm using the 1.8.1 tagged branch, PHP 5.6.30 and am getting an out of memory error in 

`/Classes/PHPExcel/Style/Supervisor.php on line 117 `

So this this is happening in the __clone function of the Supervisor class.  I've got 128M assigned.

The problem goes away when upping the memory to 256M but I'd prefer to stay at the default.  

Any tips on how to optimise my code so that this memory issue does not re-occur?

**Comment by PowerKiKi** [comment]
Have a look there: https://github.com/PHPOffice/PHPExcel/blob/1.8/Documentation/markdown/Overview/04-Configuration-Settings.md#cell-caching
