### ISSUE TITLE
memory  increase  throuth a loops

### ISSUE THREAD

**Issue by digjack** [PHPOffice/PHPExcel#1179]
```php
public function   getFile($fileFullPath){
               echo round(memory_get_usage()/1024/1024,2).'MB'.PHP_EOL;
		$PHPReader = PHPExcel_IOFactory::createReaderForFile($fileFullPath);
		if(! $PHPReader){
			return false;
		}
		$PHPExcel = $PHPReader->load($fileFullPath);
		$currentSheet = $PHPExcel->getActiveSheet();
                 return $currentSheet
}
```

the function is  called  by   a   while   loop .     and  when running   the  program,   the  memory  is  increase  constantly .    the output info   like this : 

```
➜  crontab git:(f_*****) ✗ php worker.php program_name.php

1.64MB
8MB
10.56MB
12.99MB
15.68MB
18.11MB
20.54MB
23.47MB
25.91MB
28.34MB
30.77MB
``` 

how can I   init   the cache    between    every   while    loop   and   stop the increase of the memory  using.

**Comment by PowerKiKi** [comment]
You are loading a new sheet from a new file into memory. It is normal that the memory increase every time that the function is called.

**Comment by chenyongwei** [comment]
@PowerKiKi so how to free the memory after we read the excel?

**Comment by PowerKiKi** [comment]
Destroying the object should free the memory (`unset($PHPReader);`). But then you can't access it anymore...

**Comment by digjack** [comment]
@PowerKiKi   I have try to unset the object . it doesn't work . seem  the most memory doesn't costed by  the object,   but the cache it take  inner  the object.  . I   have find a function it provide named disconnect()  to  free most memory  between every loop .  but not free all,   after many loops , it still  reach  the machine  limitation.

**Comment by zouhuigang** [comment]
+1@digjack
