### ISSUE TITLE
Class 'PHPExcel' not found in Excel5.php

### ISSUE THREAD

**Issue by rajmohanvy** [PHPOffice/PHPExcel#1194]
Hi team,
I got this error and i installed all package that required. but still the error occur. 
**Uncaught Error: Class 'PHPExcel' not found in PHPExcel/Reader/Excel5.php:625** 

PHP Version : 7.0.8

**Comment by PowerKiKi** [comment]
Upgrade to PHPExcel 1.8.1, and try again.

There is [no code at all on line 625 in PHPExcel 1.8.1](https://github.com/PHPOffice/PHPExcel/blob/1.8.1/Classes/PHPExcel/Reader/Excel5.php#L625).
