### ISSUE TITLE
parseFormula exception on mbstring

### ISSUE THREAD

**Issue by Dfred** [PHPOffice/PHPExcel#1195]
As confirmed by @MarkBaker, _PHPExcel_Calculation::parseFormula()_ should handle multibyte strings. However the following call fails:

`PHPExcel_Calculation::getInstance()->parseFormula("=cliché");`

It throws a `PHPExcel_Calculation_Exception` with message 
> Formula Error: An unexpected error occured

**Comment by PowerKiKi** [comment]
Your formula is invalid because it misses quotes. This will work:

```php
var_dump(PHPExcel_Calculation::getInstance()->parseFormula('="cliché"'));
```

and correctly output:

```
array(1) {
  [0] =>
  array(3) {
    'type' =>
    string(5) "Value"
    'value' =>
    string(9) ""cliché""
    'reference' =>
    NULL
  }
}
```

**Comment by Dfred** [comment]
Sorry, I missed an essential part of the bug report: cliché is actually a named range, thus should not have double quotes.

**Comment by Dfred** [comment]
I guess this bug report will remain closed, so I've filed another one with explicit mention of a mbstring named range.
