### ISSUE TITLE
Href is lost when opening as xml and saving as xlsx

### ISSUE THREAD

**Issue by drentha** [PHPOffice/PHPExcel#1196]
The below XML opens in Excel and retains the url.
Using PHPExcel to convert from xml to xlsx the url is lost when opening the xlsx in Excel.

-----
**php**

require __DIR__.'/vendor/autoload.php';
$objPHPExcel = PHPExcel_IOFactory::load("test.xml");
$objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel2007');
$objWriter->save('test.xlsx');

-----
**xml**
XML copied from:
https://www.ibm.com/developerworks/library/os-phpexcel/

**Comment by PowerKiKi** [comment]
Hyperlinks are [not supported in XML reader](http://phpspreadsheet.readthedocs.io/en/develop/references/features-cross-reference/). If you need please consider submitting a PR against PhpSpreadsheet develop branch.
