### ISSUE TITLE
parseFormula exception on mbstring named range

### ISSUE THREAD

**Issue by Dfred** [PHPOffice/PHPExcel#1197]
As confirmed by @MarkBaker, _PHPExcel_Calculation::parseFormula()_ should handle multibyte  **named ranges**. However the following call fails (_cliché_ is a named range):

`PHPExcel_Calculation::getInstance()->parseFormula('=cliché');`

It throws a `PHPExcel_Calculation_Exception` with message 
> Formula Error: An unexpected error occured

**Comment by PowerKiKi** [comment]
Could you provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) of code that exhibits this issue without the use of external file please ?

**Comment by Dfred** [comment]
Is this good enough?
```
$objPHPExcel = new PHPExcel();
$objPHPExcel->setActiveSheetIndex(0);
$objPHPExcel->getActiveSheet()->setCellValue('A1', 'kiki');
$objPHPExcel->addNamedRange( new PHPExcel_NamedRange(html_entity_decode('clich&eacute;'), $objPHPExcel->getActiveSheet(), 'A1'));
PHPExcel_Calculation::getInstance($objPHPExcel)->parseFormula(html_entity_decode('=clich&eacute;'));
```

**Comment by PowerKiKi** [comment]
thanks ! I can reproduce it even in PhpSpreadsheet:

```php
require __DIR__ . '/vendor/autoload.php';

use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\NamedRange;
use PhpOffice\PhpSpreadsheet\Calculation;

$objPHPExcel = new Spreadsheet();
$objPHPExcel->getActiveSheet()->setCellValue('A1', 'kiki');
$name = html_entity_decode('clich&eacute;');
$objPHPExcel->addNamedRange(new NamedRange($name, $objPHPExcel->getActiveSheet(), 'A1'));
$res = Calculation::getInstance($objPHPExcel)->parseFormula('=' . $name);
var_dump($res);
```

**Comment by Dfred** [comment]
Good job with PhpSpreadsheet by the way, any release date in sight?

**Comment by Dfred** [comment]
@PowerKiKi Did you file a bug report on PhpSpreadsheet as well? If so, can you provide a link ?

**Comment by PowerKiKi** [comment]
No, I didn't file an issue on PhpSpreadsheet. I wish we could move issue across projects...

A beta release is planned "soon"...

**Comment by Dfred** [comment]
I copied this bug-report to PhpSpreadsheet, see it there: https://github.com/PHPOffice/PhpSpreadsheet/issues/179

**Comment by PowerKiKi** [comment]
Closing here
