### ISSUE TITLE
Symfony error

### ISSUE THREAD

**Issue by Bigg-Mike** [PHPOffice/PHPExcel#1204]
Hi :)

I try to download some files on my website and i use this to create an archive:
`$zip = new \ZipArchive();`

but i have this error... i don't know how to resolve it... thanks from France!

`Error: Uncaught Symfony\Component\Debug\Exception\ContextErrorException: Notice: Use of undefined constant PHPEXCEL_ROOT - assumed 'PHPEXCEL_ROOT' in /var/www/teewii/vendor/phpoffice/phpexcel/Classes/PHPExcel/Shared/ZipArchive.php:31
Stack trace:
#0 /var/www/teewii/vendor/phpoffice/phpexcel/Classes/PHPExcel/Shared/ZipArchive.php(31): Symfony\Component\Debug\ErrorHandler->handleError(8, 'Use of undefine...', '/var/www/teewii...', 31, Array)
#1 /var/www/teewii/vendor/symfony/symfony/src/Symfony/Component/Debug/FatalErrorHandler/ClassNotFoundFatalErrorHandler.php(188): require_once('/var/www/teewii...')
#2 /var/www/teewii/vendor/symfony/symfony/src/Symfony/Component/Debug/FatalErrorHandler/ClassNotFoundFatalErrorHandler.php(143): Symfony\Component\Debug\FatalErrorHandler\ClassNotFoundFatalErrorHandler->convertFileToClass('/var/www/teewii...', '/var/www/teewii...', 'PHPExcel')
#3 /var/www/teewii/vendor/symfony/symfony/src/Symfony/Component/Debug/FatalErrorHandler/ClassNotFoundFatalErrorHandler.php(111): Symfony\Componen`

> in vendor/phpoffice/phpexcel/Classes/PHPExcel/Shared/ZipArchive.php at line 31   -
if (!defined('PCLZIP_TEMPORARY_DIR')) {
    define('PCLZIP_TEMPORARY_DIR', PHPExcel_Shared_File::sys_get_temp_dir() . DIRECTORY_SEPARATOR);
}
require_once PHPEXCEL_ROOT . 'PHPExcel/Shared/PCLZip/pclzip.lib.php';

If i understand, it's PHPEXCEL_ROOT constant the problem, why? thank you

**Comment by PowerKiKi** [comment]
You must bootstrap PHPExcel properly with something like:

```php
require_once 'vendor/phpoffice/phpexcel/Classes/PHPExcel.php';
```

**Comment by Bigg-Mike** [comment]
I already tried but doesn't work.

**Comment by PastisD** [comment]
I have this in my Symfony application

```
<?php

namespace My\Bundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;

**\PhpOffice\PhpWord\Autoloader::register();**

class MyController extends Controller
{
}
```

**Comment by Bigg-Mike** [comment]
I solved this problem in my prod server:
- sudo apt-get install zip php-7.0-zip
^^' ....

**Comment by digitalmanagerit** [comment]
Excuse me so does this have to do with the PHP version?

**Comment by PowerKiKi** [comment]
@digitalmanagerit not exactly a PHP version, but a PHP extension. If you want to use `\ZipArchive();` you must install PHP `zip` extension. Unfortunately PHPExcel also have a class named `ZipArchive` that might conflict with the extension if not used properly.

**Comment by digitalmanagerit** [comment]
Fixed it easily :) Just added the extension in the PHP Version area in cPanel. Thanks.

**Comment by flistefliste** [comment]
@Flo-Slv $ sudo apt-get install php7.0-zip (no dash after php) ;)

**Comment by jamesexperts** [comment]
Just update
  PHPExcel_Settings::setZipClass(PHPExcel_Settings::PCLZIP);
  to
  PHPExcel_Settings::setZipClass(PHPExcel_Settings::ZIPARCHIVE);
