### ISSUE TITLE
Max excel version with v1.7.9

### ISSUE THREAD

**Issue by Tuan-T-Nguyen** [PHPOffice/PHPExcel#1205]
How can I detect or know what the max excel version for phpExcel v1.7.9?
And what the problems if I update phpExcel to last version?
Thanks.

**Comment by PowerKiKi** [comment]
Read the [changelog](https://github.com/PHPOffice/PHPExcel/blob/1.8.1/changelog.txt) to know about changes to 1.8.1.

The best you can hope for PHPExcel 1.7.0, which was released on 2013-06-02, is PHP 5.5 which was released 2013-06-20. Anything newer than that cannot be guaranteed.
