### ISSUE TITLE
Manage rules in phpExcel

### ISSUE THREAD

**Issue by Tuan-T-Nguyen** [PHPOffice/PHPExcel#1206]
When I use manage rules in template excel and export it with read data. The manage rules was not show.
Thanks

**Comment by Hectic247** [comment]
I gather you are referring to Conditional Formatting Rules in Excel? I had the same same problem reading/writing the Excel5 format. Switched to Excel2007 (Office Open XML) instead of Excel5 and it resolved it.

**Comment by PowerKiKi** [comment]
Indeed [conditional formatting in XLS is not supported](http://phpspreadsheet.readthedocs.io/en/develop/references/features-cross-reference/).
