### ISSUE TITLE
RESOLVED: Attempted to load class "ZipArchive" from the global namespace.

### ISSUE THREAD

**Issue by moughaouiViseo** [PHPOffice/PHPExcel#1208]
Hello,

When I try to export an Excel file I get the following error: 

```
Attempted to load class "ZipArchive" from the global namespace.
Did you forget a "use" statement for "PHPExcel_Shared_ZipArchive"?
```
`in vendor/phpoffice/phpexcel/Classes/PHPExcel/Writer/Excel2007.php at line 227  -

                // Create new ZIP file and open it for writing
                $zipClass = PHPExcel_Settings::getZipClass();
                $objZip = new $zipClass();
                //    Retrieve OVERWRITE and CREATE constants from the instantiated zip class
                //    This method of accessing constant values from a dynamic class should work with all appropriate v`
I use php7 with PHPExcel 1.8 on Ubuntu
I fixed the problem by changing line 43 of the file 

> phpoffice/phpexcel/Classes/PHPExcel/Settings.php

Old line: `const ZIPARCHIVE = 'ZipArchive';`
New: `const ZIPARCHIVE = PHPExcel_Shared_ZipArchive;`

Is it normal ?

Thank you

**Comment by moughaouiViseo** [comment]
Bug resolved
I installed php7.0-zip, now it works:

`$ sudo apt-get install php7.0-zip`

Thank you

**Comment by adatta02** [comment]
This is still broken from an operational perspective. 

The package should really have the zip extension as a dependency since you wouldn't know you're missing it until trying to use any code that uses the loaders.

**Comment by PowerKiKi** [comment]
This is the case since https://github.com/PHPOffice/PhpSpreadsheet/commit/ea5663bc005bcd0277ca18e563b305fe3151b3a4

**Comment by Amidd** [comment]
MyEtherWallet (MEW) and Emerald Wallet are both client side applications to access ETC. A MEW user can easily migrate to Emerald Wallet by simply importing their ETC account's keystore file or private key in the Emerald Wallet.

Video links: 
myetherwallet.com
github.com/etcdevteam/emerald-wallet
docs.etcdevteam.com

ETCDEV:
Our Team: https://etcdevteam.com/
Our Projects: https://github.com/etcdevteam/
Follow us on Twitter: https://twitter.com/etcdev
Become a DApp Developer: https://docs.etcdevteam.com/

More ETC:
ETC HQ: https://ethereumclassic.org/
Join ETC: https://joinetc.tech
