### ISSUE TITLE
setAutoFilter produces Warning on php > 7.1

### ISSUE THREAD

**Issue by Bhoft** [PHPOffice/PHPExcel#1212]
setAutoFilter produces warnings with php version greater then 7.1.
Tested with  latest version 185bf41 Version so 1.8.x

- PHP 7.0 (works)
- PHP 7.1 (produces warnings)
- PHP 7.1.4 (produces warnings)

These warnings prevent file generation with streamed output, therefore no downloaded files.

Tested with Examples/10autofilter.php

    14:01:35 Create new PHPExcel object
    14:01:35 Set document properties
    14:01:35 Add data
    14:01:35 Set title row bold
    14:01:35 Set autofilter
    14:01:35 Write to Excel2007 format
    14:01:35 File written to 10autofilter.xlsx
    Call time to write Workbook was 0.1220 seconds
    14:01:35 Current memory usage: 2 MB
    14:01:35 Write to Excel5 format
    
    Warning: A non-numeric value encountered in D:\wamp\www\test\phpexcel\Classes\PHPExcel\Cell.php on line 843
    
    Warning: A non-numeric value encountered in D:\wamp\www\test\phpexcel\Classes\PHPExcel\Cell.php on line 843

    Warning: A non-numeric value encountered in D:\wamp\www\test\phpexcel\Classes\PHPExcel\Cell.php on line 843

    Warning: A non-numeric value encountered in D:\wamp\www\test\phpexcel\Classes\PHPExcel\Cell.php on line 843
    14:01:35 File written to 10autofilter.xls
    Call time to write Workbook was 0.1160 seconds
    14:01:35 Current memory usage: 2 MB
    14:01:35 Peak memory usage: 2 MB
    14:01:35 Done writing files
    Files have been created in phpexcel\Examples

I guess this is a normal php 7 compatibility issue.

**Comment by Bhoft** [comment]
`Cell::stringFromColumnIndex()` is somwhere called with an $pColumnIndex which is already an Named Column index e.g. ('A'). In this case pColumnIndex is not an integer.

if the function is extended with

    if (!is_int($pColumnIndex)) {
            return $pColumnIndex;
    }

The issue seems to be fixed or the check is added where the function is called.

**Comment by Bhoft** [comment]
found the error 
https://github.com/PHPOffice/PHPExcel/blob/1.8/Classes/PHPExcel/Writer/Excel5.php#L372

    $endCoordinates = PHPExcel_Cell::stringFromColumnIndex(PHPExcel_Cell::stringFromColumnIndex($iInc - 1));

should only be:

     $endCoordinates = PHPExcel_Cell::stringFromColumnIndex($iInc - 1);

**Comment by PowerKiKi** [comment]
Migrate to PhpSpreadsheet for support of PHP 7.1

**Comment by Bhoft** [comment]
So you say that wrong code isn't fixed in PHPExcel any more at all?

I mean this line is wrong if it is executed in php5 or php7.
Wrong is wrong in my opinion.


It is also only 1 line of code and it is clearly visible that the function shouldn't be called twice.
But i understand that all efforts are put into PHPSpreadsheet, but how much effort is it to change this one line. I could also do a pull request if its to much work.

I would be pleased if this line is fixed because many used extensions still using PHPExcel.
I haven't looked into PHPSpreadsheet myself because it is still marked as unstable, so i don't know how much effort it take to switch the libary.

As it is written on the github page itself.
 `However PhpSpreadsheet is still unstable and not yet released.`

**Comment by PowerKiKi** [comment]
Yes, unfortunately PHPExcel will not be updated anymore. At least not by me. Sorry for the inconvenience.
