### ISSUE TITLE
Does PHPExcel support reading Excel with thousand rows?

### ISSUE THREAD

**Issue by kepingatp** [PHPOffice/PHPExcel#1224]
I've an app that upload Excel file into app.
The flow is "Upload->save the file into local dir->get the file from dir->read the file using PHPExcel"

This is my code:
```php
$middleName = substr(md5(microtime() * 100000), rand(0, 9), 5);          

    if ($fileMaster !== null) {
    $nameMaster = $userId . '_MP' . '_' . $middleName . '_' . date('Y-m-d') . '_' .  $fileMaster[0]->getBaseName() . "." . $fileMaster[0]->getExtension();
    $pathMaster = Yii::getAlias('@webroot/trash/trash_app/') . $nameMaster;             
    $fileMaster[0]->saveAs($pathMaster);
            } else {
                $error[] = "Choose an " . "<strong>" . " Excel " . "</strong>" . "file first.";
                $result = [
                    'error' => $error
                ];
            }
            echo '<pre>';
            print_r($fileMaster);
            die();
```

if the the excel only has rows of data less than 8.000 rows, it return `error => 0` like this
![screenshot_7](https://cloud.githubusercontent.com/assets/20182181/26723817/7d22bf32-47c0-11e7-9797-c3e2eff7413d.png)
and the excel successfully save into local dir.

But when I use an excel file that contain 89.900 rows, it return `error => 1` like this
![screenshot_6](https://cloud.githubusercontent.com/assets/20182181/26723864/c3408ec2-47c0-11e7-9c1f-78e792f2a367.png)

**How does I can process an Excel file that contain 89K of rows?**

**Comment by PowerKiKi** [comment]
Read about reading large files there: http://phpspreadsheet.readthedocs.io/en/develop/topics/reading-files/#spreadsheet-reader-options (same concepts apply to PHPExcel)
