### ISSUE TITLE
Time execution issue

### ISSUE THREAD

**Issue by ngocongcan** [PHPOffice/PHPExcel#1226]
Dear contributors,

I'm using this library to export XLS and CSV from my site. I really love it. But I have a problem about the time execution when export about (6000 rows x 50 columns) , it takes about 20 minutes . Do you have any solutions to resolve this problem ?

Thanks!

**Comment by phpexcel** [comment]
That's strange. It should export within a minute.

**Comment by s1lver** [comment]
Really!

Given:
```
Excel ~ 6mb
570 rows, columns A through BZ
```
php 5.6 ~ 10 min
php 7.1 ~ 2min

Right now there is no way to update. But I really want to somehow speed up the process.

Thanks!
