### ISSUE TITLE
PHPExcel_Settings::setPdfRenderer keeps telling me "Please set the $rendererName and $rendererLibraryPath values..."

### ISSUE THREAD

**Issue by tuna-mms-dev-2k16** [PHPOffice/PHPExcel#1227]
ok I am totally confused now. I have tried all I can to implement PDF feature. I have followed exactly everything instructed in the document and examples but still failed in step "PHPExcel_Settings::setPdfRenderer".

Please review for me what am I doing wrong?
    
    public function exportToPDF($data, $filename)
    {
        global $CFG;
        require_once($CFG->libdir. '/phpexcel/PHPExcel.php');
        $objPHPExcel = new PHPExcel();
        $rowNumber = 1;
        $column = 321; // column 'A'
        $objPHPExcel->setActiveSheetIndex(0);

        foreach ($data as $user) {
            $vars = get_object_vars($user);
            foreach ($vars as $property => $value) {
                $columnName = chr($column);
                $objPHPExcel->setActiveSheetIndex(0)->setCellValue($columnName . $rowNumber, $property);
                $column++;
            }
            $rowNumber++;
            break;
        }

        foreach ($data as $user) {
            $column = 321; // column 'A'
            $userArr = get_object_vars($user);
            foreach ($userArr as $property => $value) {
                $columnName = chr($column);
                $objPHPExcel->setActiveSheetIndex(0)->setCellValue($columnName . $rowNumber, $value);
                $column++;
            }
            $rowNumber++;
        }

        $objPHPExcel->getActiveSheet()->setTitle('Logged_in_users');
        $objPHPExcel->setActiveSheetIndex(0);

        $rendererName = PHPExcel_Settings::PDF_RENDERER_MPDF;
        $rendererLibrary = 'mPDF';
        $extension = ".php";
        $rendererLibraryPath = $CFG->libdir. '/phpexcel/PHPExcel/Writer/PDF/' . $rendererLibrary . $extension;
        $rendererLibraryPath = str_replace("\\","/",$rendererLibraryPath);
        $rendererLibraryPath = $this->getRelativePath(dirname(__FILE__), $rendererLibraryPath);
        $rendererLibraryPath = substr($rendererLibraryPath,0, 0 - strlen("$extension"));//remove ".php"
        //$rendererLibraryPath = str_replace($rendererLibrary,"mPDF5.4",$rendererLibraryPath);

        if (!PHPExcel_Settings::setPdfRenderer(
            $rendererName,
            $rendererLibraryPath
        )) {
            die(
                'Please set the $rendererName and $rendererLibraryPath values' .
                PHP_EOL .
                ' as appropriate for your directory structure' .
                PHP_EOL .
                "Render name: " . $rendererName .
                PHP_EOL .
                "Render path: " . $rendererLibraryPath .
                PHP_EOL// .
                //"Dir path: " . dirname(__FILE__) .
                //PHP_EOL
            );
        }

        require_once($CFG->libdir. '/phpexcel/PHPExcel/Writer/PDF.php');
        $objWriter = new PHPExcel_Writer_PDF($objPHPExcel);
        $objWriter->writeAllSheets();
        $objWriter->save($filename.".pdf");

        header("Content-type:application/pdf");
        header('Content-Disposition: attachment;filename="'.$filename.'.pdf"');
        header('Cache-Control: max-age=0');

        exit;
    }

    function getRelativePath($from, $to)
    {
        // some compatibility fixes for Windows paths
        $from = is_dir($from) ? rtrim($from, '\/') . '/' : $from;
        $to   = is_dir($to)   ? rtrim($to, '\/') . '/'   : $to;
        $from = str_replace('\\', '/', $from);
        $to   = str_replace('\\', '/', $to);

        $from     = explode('/', $from);
        $to       = explode('/', $to);
        $relPath  = $to;

        foreach($from as $depth => $dir) {
            // find first non-matching dir
            if($dir === $to[$depth]) {
                // ignore this directory
                array_shift($relPath);
            } else {
                // get number of remaining dirs to $from
                $remaining = count($from) - $depth;
                if($remaining > 1) {
                    // add traversals up to first matching dir
                    $padLength = (count($relPath) + $remaining - 1) * -1;
                    $relPath = array_pad($relPath, $padLength, '..');
                    break;
                } else {
                    $relPath[0] = './' . $relPath[0];
                }
            }
        }
        return implode('/', $relPath);
    }`

When I run the code, I got this error message.

> Please set the $rendererName and $rendererLibraryPath values as appropriate for your directory structure

I printed the values of  $rendererName and $rendererLibraryPath and got 

> Render name: mPDF 
Render path: ../../lib/phpexcel/PHPExcel/Writer/PDF/mPDF

The path is correct (according on my project's folder structure). Surely I can't use an absolute path, because my project is hosted on xampp (on Windows platform) so I have to convert it into relative path. Can anyone please tell me what do I miss? Thank you very much.

**Comment by MarkBaker** [comment]
`Render path: ../../lib/phpexcel/PHPExcel/Writer/PDF/mPDF` isn't pointing to your instance of mPDF.... it's pointing to the PHPExcel wrapper for mPDF..... you need to have mPDF itself installed on your server, and use the `$rendererLibraryPath` argument for `PHPExcel_Settings::setPdfRenderer()` to tell PHPExcel where the library has been installed

**Comment by tuna-mms-dev-2k16** [comment]
Can you please explain for me what do you mean by

>  you need to have mPDF itself installed on your server

?

Is there anything else that I should do to get this works? Please explain more for me. Thanks.

**Comment by tuna-mms-dev-2k16** [comment]
By the way, can you please reopen this ticket for me? I asked my questions because I need help in using the library.
