### ISSUE TITLE
set border bug

### ISSUE THREAD

**Issue by liakong** [PHPOffice/PHPExcel#1236]
key code:
`$objActSheet->getStyle("B12:F12")->getBorders()->getBottom()->setBorderStyle(PHPExcel_Style_Border::BORDER_THIN);`

before updating to 1.8, it outputs:
![image](https://user-images.githubusercontent.com/5061162/27267868-13712972-54de-11e7-9c59-b9683dff213a.png)
after updating to 1.8, it outputs:
![image](https://user-images.githubusercontent.com/5061162/27267883-3051945a-54de-11e7-9c36-f48f5bc16ced.png)

the bottom border set becomes right border set.

**Comment by liakong** [comment]
anyone can help?

**Comment by msvendsen** [comment]
Same bug for getTop() :-(
I found that when instead using code like below, it works:

$objPHPExcel->getActiveSheet()->getStyle('A1:U1')->applyFromArray(
	array('borders' => array('top' => array('style' => PHPExcel_Style_Border::BORDER_MEDIUM))));

I have tried to see if I can locate the bug, but I'm quite new to PHPExcel so haven't been able to..

**Comment by liakong** [comment]
@msvendsen thanks very much for you suggestion. I will try it.

**Comment by liakong** [comment]
@msvendsen I have tried and it works. Thanks very much.
