### ISSUE TITLE
Non numeric error for Excel5 Writer (PHP 7.x)

### ISSUE THREAD

**Issue by kartik-v** [PHPOffice/PHPExcel#1237]
Occurs at `PHP_Excel_Cell::stringFromColumnIndex`  because string `A`, `B` are not treated as integers.

Where it fails is this [line 372 of Writer\Excel5.php](https://github.com/PHPOffice/PHPExcel/blob/1.8/Classes/PHPExcel/Writer/Excel5.php#L372) where the double conversion of string to index returns only a string character which is not parsed as integer in PHP 7.x.

Solution is to add this code below at [Line 839 of Cell.php](https://github.com/PHPOffice/PHPExcel/blob/1.8/Classes/PHPExcel/Cell.php#L839).

```php
        $pColumnIndex = (int) $pColumnIndex;
```

Will submit a separate PR for this.

**Comment by PowerKiKi** [comment]
The double conversion was wrong and has been fixed in PhpSpreadsheet
