### ISSUE TITLE
[BUG] wps-xlsx-load

### ISSUE THREAD

**Issue by 502923093** [PHPOffice/PHPExcel#1242]
when i use microsoft office to create a xlsx file and edit it by wps，then i import it to my program
error happens like this
ERROR: Allowed memory size of 335544320 bytes exhausted (tried to allocate 85 bytes)

**Comment by PowerKiKi** [comment]
See https://github.com/PHPOffice/PHPExcel/issues/119#issuecomment-11996725

**Comment by 502923093** [comment]
@PowerKiKi Thanks ,but It not resolved.i configed it like this: memory_limit = 128M;
but the file is 11KB ,so the proble still happen.

**Comment by 502923093** [comment]
@PowerKiKi i add it in class PHPExcel_Worksheet function: public function shrinkRangeToFit $range = str_replace('$', '', strtoupper($range)); it fixed the bug,but i don't know it can take other bugs?
