### ISSUE TITLE
7.1 warning in Cell.php

### ISSUE THREAD

**Issue by goffyara** [PHPOffice/PHPExcel#1244]
https://github.com/PHPOffice/PHPExcel/blob/1.8/Classes/PHPExcel/Cell.php#L843

http://php.net/manual/en/migration71.other-changes.php#migration71.other-changes.apprise-on-arithmetic-with-invalid-strings

**Comment by PowerKiKi** [comment]
PHPExcel is not compatible with PHP 7.1. Consider migrating to PhpSpreadsheet instead.
