### ISSUE TITLE
Read CSV File

### ISSUE THREAD

**Issue by kepingatp** [PHPOffice/PHPExcel#1250]
Does this lib can read data from CSV file, I've tried and successfully upload the file, but there's a problem when read and convert the data into array.
If it possible, how's the code? 
Thanks

**Comment by felipph** [comment]
This library has no intention to do such think. It's easy:

```
$arq = file("PATH TO YOUR FILE");

            $csv = array_map(function($v) {
                $v = trim($v);    
                return str_getcsv($v, ","); //REPLACE comma with your separator(In PT_BR is semicollon (;)
            }, $arq);
print_r($csv);
```
Regards.

**Comment by PowerKiKi** [comment]
Actually, yes it can: https://github.com/PHPOffice/PHPExcel/blob/1.8/Documentation/markdown/Overview/10-Reading-and-Writing.md#reading-a-csv-file
