### ISSUE TITLE
Docs and Website are… weird

### ISSUE THREAD

**Issue by heiglandreas** [PHPOffice/PHPExcel#1251]
There aren't any online-docs to find on the website. And the link to the Project-website leads to a website that says the project moved to GitHub which then says that more information can be found on the website which then says… You get the picture?

Perhaps remove the link to the website or create a project-website on GitHub.io and link the docs-folder in there. Preferably with MarkDown or HTML-Files…

**Comment by PowerKiKi** [comment]
See http://phpspreadsheet.readthedocs.io/en/develop/ (and [maybe that too](https://github.com/PHPOffice/phpspreadsheet#phpexcel-vs-phpspreadsheet-))
