### ISSUE TITLE
More than 3 sheets in Exccel 2010.

### ISSUE THREAD

**Issue by pelydas** [PHPOffice/PHPExcel#1256]
Hello everybody, first sorry for my english, is elemental. I have a Excel 2010 book with 3 sheets with the days on May,Jun and July. Every ones has 600 rows and 35 columns, the half has values and the other half simple formulas based on SUM(). When i added a new sheet as a copy of one of the others for August the PHP script returns HTTP ERROR 500, however if i add a new sheets only with values, the php script runs normaly. Has PHPExcel library any restriction for num of sheets or data ?. Here part of my code, thanks

```php
$hoymes = strtoupper(strftime("%B"));
$objReader = PHPExcel_IOFactory::createReader("Excel2007");
$objPHPExcel = $objReader->load("Excel/CDM.xlsx");
$objPHPExcel->setActiveSheetIndexByName($hoymes); 
$objActSheet = $objPHPExcel->getActiveSheet();
$sql = "EXEC StoreProdedure";
$resultado=mssql_query($sql);
$total=mssql_num_rows($resultado);
$fila=mssql_fetch_array($resultado); 
while(!empty($fila))
	{
		if ($fila[0] != 0) $objActSheet->setCellValueByColumnAndRow($var,$j,$fila[2]);			
		$j++;
		$fila=mssql_fetch_array($resultado);
	}
mssql_free_result($resultado);

$objWriter = new PHPExcel_Writer_Excel2007($objPHPExcel);
$objWriter->save("Excel/CDM.xlsx");
$objWriter->save('Excel/CDM'.date(dmY).'.xlsx');

unset($objWriter);
unset($objPHPExcel);
```

**Comment by PowerKiKi** [comment]
Try to [enable error reporting](https://stackoverflow.com/a/21429652/37706) on your server and find out in the logs what exception is thrown. That should include a error message and a full stacktrace.

**Comment by pelydas** [comment]
Thanks PowerKiKi, i found the issue adding the code below, first was memory_limit, i changed into php.ini from 128 to 256 but after appearsd another error about max_execution_time that i also changed from 30 to 60 seconds

ini_set('display_errors', 1);
ini_set('display_startup_errors', 1);
error_reporting(E_ALL);
