### ISSUE TITLE
Stop working with SSH2 v0.13

### ISSUE THREAD

**Issue by moosacz** [PHPOffice/PHPExcel#1263]
Redhat package php-5.3.3-49.el6 with SSH2 v 0.13 create issue that PHPExcel stop working. I can create object instance but when I try create/fill xlsx file (template), example:
$objPHPExcel->setActiveSheetIndex(0)
                    ->setCellValue('K4', "somedata").....

 it stop work and Server connection aborted. From hosting provider I have this information:  
results into a segmentation fault: [notice] child pid 8035 exit signal Segmentation fault (11)
Your PHPExcel class is not compatibility with SSH2 v 0.13. With version 0.12 it works.

Please can you help me?
Thx.

**Comment by PowerKiKi** [comment]
Most likely not a bug within PHPExcel itself, but rather PHP the language or something else in in your environnement.

[PHP 5.3 has been unsupported for almost 3 years](http://php.net/eol.php), upgrade to PHP 5.6, or better yet PHP 7.1.
