### ISSUE TITLE
Corrupted XLSX file

### ISSUE THREAD

**Issue by robregonm** [PHPOffice/PHPExcel#1265]
When I export files and the generated files are more than 60kB I get corrupted files in prod but they export fine locally, after compared the exact same export script (even same data, but different environments), the correctly generated file starts like this (generated locally and open without issues):

<pre>
50 4B 03 04 14 00 00 00  08 00 <b><i>D9 5A</i></b> F5 4A 19 39  PK...... ...Z.J.9
E2 60 93 01 00 00 EF <b><i>0C</i></b>  00 00 13 00 00 00 5B 43  .`...... ......[C</pre>

But the corrupted file starts like this:

<pre>
50 4B 03 04 14 00 00 00  08 00 <b><i>97 5C</i></b> F5 4A 19 39  PK...... ...\.J.9
E2 60 93 01 00 00 EF <b><i>20</i></b>  00 00 13 00 00 00 5B 43  .`.....  ......[C
</pre>

The differences are very subtle and are <b><i>highlighted like this</i></b>.

I'm using PHP 7.1 (in both local and prod)
And the installed extensions look similar. The only noticeable differences are the running Ubuntu versions (16.04 in my local environment and 14.04 in production) and the available memory (16GB local env, 512 MB in production)

Thoughts? Ideas?

**Comment by robregonm** [comment]
I tried to open and unzip both files (the good and the corrupted one) and they unzip correctly (which is very curious)

**Comment by PowerKiKi** [comment]
PHP 7.1 is not supported and is likely to break somewhere at some point. You should consider migrating to PhpSpreadsheet develop branch.

**Comment by robregonm** [comment]
After many tests, combination of formats (it was happening with all formats) and debugging, I found that It was due to Cloudflare minification script, it seems that Cloudflare doesn't detect the content of the files based on MIME type headers, but it minifies all the files (it doesn't care the format)
So, I disabled HTML minification and everything is working back again.
