### ISSUE TITLE
PHP7 - PHPexcel export issue

### ISSUE THREAD

**Issue by seemas-grazitti** [PHPOffice/PHPExcel#1268]
```
Notice: Undefined variable: zipClass in /var/www/vhost/timesheet.grazitti.com/html/PHPExcel/Writer/Excel2007.php on line 227
--
 
Fatal error: Uncaught Error: Class name must be a valid object or a string in /var/www/vhost/timesheet.grazitti.com/html/PHPExcel/Writer/Excel2007.php:227 Stack trace: #0 /var/www/vhost/timesheet.grazitti.com/html/admin_report_specific_user.php(764): PHPExcel_Writer_Excel2007->save('/tmp/phpxltmpF0...') #1 {main} thrown in /var/www/vhost/timesheet.grazitti.com/html/PHPExcel/Writer/Excel2007.php on line 227

```

I am getting this issue. Please let me know solution and i am using 1.8.1 version.

**Comment by PowerKiKi** [comment]
You are not using the official PHPExcel 1.8.1, because the variable `$zipClass` cannot be undefined at that line. See [the code for yourself there](https://github.com/PHPOffice/PHPExcel/blob/1.8.1/Classes/PHPExcel/Writer/Excel2007.php#L226-L227).

Upgrade to [PHPExcel 1.8.1](https://github.com/PHPOffice/PHPExcel/releases/tag/1.8.1).

**Comment by seemas-grazitti** [comment]
Now i have used same Upgrade to PHPExcel 1.8.1. code which u have send me link. I am getting following error.

Fatal error: Uncaught Error: Class 'ZipArchive' not found in /var/www/vhost/timesheet.grazitti.com/html/PHPExcel/Writer/Excel2007.php:227 Stack trace: #0 /var/www/vhost/timesheet.grazitti.com/html/admin_report_specific_user.php(765): PHPExcel_Writer_Excel2007->save('/tmp/phpxltmpr3...') #1 {main} thrown in /var/www/vhost/timesheet.grazitti.com/html/PHPExcel/Writer/Excel2007.php on line 227

**Comment by PowerKiKi** [comment]
https://github.com/PHPOffice/PHPExcel/blob/master/Documentation/markdown/Overview/01-Getting-Started.md#php-complains-about-ziparchive-not-being-found
