### ISSUE TITLE
PHP7 - PHPExcel Export data issue

### ISSUE THREAD

**Issue by seemas-grazitti** [PHPOffice/PHPExcel#1270]
Now i have used same Upgrade to [PHPExcel 1.8.1.](https://github.com/PHPOffice/PHPExcel/releases/tag/1.8.1) code .I am still getting following error.

Fatal error: Uncaught Error: Class 'ZipArchive' not found in /var/www/vhost/timesheet.grazitti.com/html/PHPExcel/Writer/Excel2007.php:227 Stack trace: #0 /var/www/vhost/timesheet.grazitti.com/html/admin_report_specific_user.php(765): PHPExcel_Writer_Excel2007->save('/tmp/phpxltmpr3...') #1 {main} thrown in /var/www/vhost/timesheet.grazitti.com/html/PHPExcel/Writer/Excel2007.php on line 227

**Comment by PowerKiKi** [comment]
https://github.com/PHPOffice/PHPExcel/blob/master/Documentation/markdown/Overview/01-Getting-Started.md#php-complains-about-ziparchive-not-being-found
