### ISSUE TITLE
Please help me

### ISSUE THREAD

**Issue by wakikuk** [PHPOffice/PHPExcel#1274]
i try create page with plugin php excel , and itry create page with sheet and the last to html , but i dont know, why my image crash or do not showing ? please help me 
that my conditions
![image](https://user-images.githubusercontent.com/25858135/28741747-ea3467a2-7447-11e7-8250-75e9de23dcf6.png)

**Comment by wakikuk** [comment]
but normal on format xls or save excel 
![image](https://user-images.githubusercontent.com/25858135/28741924-c3fb9c8c-744b-11e7-9877-efe14a728a56.png)

**Comment by Adorfer** [comment]
choosing non-clickbait topics wouldn't scare off who could help. just saying

**Comment by wakikuk** [comment]
sorry this is my first port , what mean of topics on here?

**Comment by PowerKiKi** [comment]
@wakikuk "Please help me" is not an appropriate title. It should be a short description of the problem.

Also you should [read the documentation](https://github.com/PHPOffice/PHPExcel/blob/1c8c2379ccf5ab9dd7cb46be965821d22173bcf4/Documentation/markdown/Overview/10-Reading-and-Writing.md#setting-the-images-root-of-the-html-file) before asking for help.

**Comment by wakikuk** [comment]
i understand , thank you PowerKiKi , i had been read that documentation , just use script html only, for show the image thank you..
![image](https://user-images.githubusercontent.com/25858135/28806179-bea4fda6-7698-11e7-8923-a0ea23565cf5.png)
