### ISSUE TITLE
How to use TemplateProcessor in .xlsx files?

### ISSUE THREAD

**Issue by donriga** [PHPOffice/PHPExcel#1275]
Can something like that?
$templateProcessor = new \PhpOffice\PhpWord\TemplateProcessor($tmpfile);

**Comment by PowerKiKi** [comment]
Wrong project, try over there: https://github.com/PHPOffice/PHPWord

**Comment by donriga** [comment]
Not wrong, i want to use similar functional in PHPExcel, 
TemplateProcessor in .xlsx files
$templateProcessor = new \PhpOffice\PhpExcel\TemplateProcessor($tmpfile);
