### ISSUE TITLE
how to reduce the library file size

### ISSUE THREAD

**Issue by mriyahi** [PHPOffice/PHPExcel#1280]
Hi
I use this library in my joomla component.
the problem is this library size is about 4.8 MB & this size is very big To be added to the Joomla extension.
There is a way we can reduce and optimize the size of this library ?

**Comment by PowerKiKi** [comment]
4.8MB is not that big nowadays, I'm not sure why this would be a problem for any hosts. I often get 50-100MB of vendored libraries in my projects.

However you could manually delete `Documentation/`, `Examples/` and `unitTests/`. Those folders are useless for production environnement.
