### ISSUE TITLE
Looping through First Row

### ISSUE THREAD

**Issue by socialpixe** [PHPOffice/PHPExcel#1294]
Hello there, 

I am really FEDUP with this library, if i am looking for basic PHP Excel writter i always get this and nothing happens and won't solve my problem.

So finally i am writting, can anybody please tell me is there anyway to loop through Top Row of excel.

I need something like this
![loop](https://user-images.githubusercontent.com/24809844/29663863-db170006-88ea-11e7-9783-07ddca894c54.png)

**Comment by socialpixe** [comment]
WORST LIBRARY

**Comment by PowerKiKi** [comment]
Your frustration for not being able to code a loop is certainly not a good indicator of the quality of this library.

```php
<?php

require __DIR__ . '/vendor/autoload.php';

use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;

$spreadsheet = new Spreadsheet();
$sheet = $spreadsheet->getActiveSheet();
foreach (range(1, 10) as $i) {
    $sheet->setCellValueByColumnAndRow($i, 1, $i);
}

$writer = new Xlsx($spreadsheet);
$filename = '/tmp/test.xlsx';
$writer->save($filename);
echo 'saved to: ' . $filename . PHP_EOL;
```
