### ISSUE TITLE
Compile Error: 'break' not in the 'loop' or 'switch' context

### ISSUE THREAD

**Issue by Eldhelion** [PHPOffice/PHPExcel#1296]
I'm trying to create a excel with multiple sheets, but have reached the following error:

Symfony\Component\Debug\Exception\ FatalErrorException
in vendor/phpoffice/phpexcel/Classes/PHPExcel/Calculation/Functions.php (line 581)

                    return 1;
            } elseif(is_bool($value)) {
                    return 4;
            } elseif(is_array($value)) {
                    return 64;
                    break;
            } elseif(is_string($value)) {
                //    Errors
                if ((strlen($value) > 0) && ($value{0} == '#')) {
                    return 16;
                }

**Comment by apurv195** [comment]
Just **COMMENT** the "break;" statement in functions.php file on Line No 581

**Comment by phaniapsr** [comment]
I did not found any break in line 581..

**Comment by mintysam** [comment]
Try 601
