### ISSUE TITLE
comma as Parameter seperator throws an unknown exception

### ISSUE THREAD

**Issue by efinder2** [PHPOffice/PHPExcel#1298]
When I use the following formula '=ROUND(A1;2)' the system throws a unkonwn exception.  It would be nice for all german users when a specific exception would be thrown. (semikolon is the default seperator in german excel translation) 
I had to debug your code for about four hours to find the problem

**Comment by MarkBaker** [comment]
This is quite explicitly [stated in the documentation](https://github.com/PHPOffice/PHPExcel/blob/develop/Documentation/markdown/Overview/08-Recipes.md#write-a-formula-into-a-cell); and PHPExcel has no way of knowing if you are German or English or Japanese
