### ISSUE TITLE
PHP 7.2 compatibility

### ISSUE THREAD

**Issue by cmdmcs** [PHPOffice/PHPExcel#1334]
Next error message appears when reading .xlsx file on server with PHP 7.2:

_PHP Startup: Unable to load dynamic library 'php_mysqli.dll' (tried: /opt/cpanel/ea-php72/root/usr/lib64/php/modules/php_mysqli.dll (/opt/cpanel/ea-php72/root/usr/lib64/php/modules/php_mysqli.dll: cannot open shared object file: No such file or directory), /opt/cpanel/ea-php72/root/usr/lib64/php/modules/php_mysqli.dll. so (/opt/cpanel/ea-php72/root/usr/lib64/php/modules/php_mysqli.dll.so: cannot open shared object file: No such file or directory)) in Unknown on line 0_

**Comment by PowerKiKi** [comment]
PHP 7.2 is not supported and will never be, please consider migrating to PhpSpreadsheet
