### ISSUE TITLE
PHP 7.1 - Non-numeric value encountered : stringFromColumnIndex() : Line 835

### ISSUE THREAD

**Issue by seltix5** [PHPOffice/PHPExcel#1338]
Hi,

PHP is warning about a non-numeric value in the function stringFromColumnIndex() at line 835 :

https://github.com/PHPOffice/PHPExcel/blob/1.8/Classes/PHPExcel/Cell.php#L843

PHPExcel version 1.8.1

After some output, apparently this append when $pColumnIndex has the column letter as value.

Thanks.

**Comment by PowerKiKi** [comment]
PHP 7.1 is not, and will not be, supported. Upgrade to PhpSpreadsheet instead.

**Comment by seltix5** [comment]
Hi,
But this is just a warning duo to directly converting a string to a int, it could be easly fixed. PhpSpreadsheet  has dependencies and uses composer, i do not :/

**Comment by lbr88** [comment]
For anyone else having this problem i just added the following to the function stringFromColumnIndex in PHPExcel/Cell.php

$pColumnIndex = intval($pColumnIndex,0);

And it fixed it for my usecase. But use at your own risk.
