### ISSUE TITLE
HLOOKUP row_index_num fix

### ISSUE THREAD

**Issue by ioulian** [PHPOffice/PHPExcel#1339]
There's a bug in the HLOOKUP function.

There is a check if $index_number is greater than the number of rows and fail if it's greater. Now due to copy pasting (I think) of the VLOOKUP function there is a check on the count of the COLUMNS and not ROWS:

Original:
```php
$index_number > count($lookup_array[$firstRow])
```

We [must check on the count of the rows](https://support.office.com/en-us/article/HLOOKUP-function-a3034eec-b719-4ba3-bb65-e1ad662ed95f) (`row_index_num` and not `col_index_num` as in VLOOKUP) and not on the columns. So by changing the code to this, it works:

```php
$index_number > count($lookup_array)
```

Full line: https://github.com/PHPOffice/PHPExcel/blob/185bf412339526c97a98d959c3c0ecf4b7c80016/Classes/PHPExcel/Calculation/LookupRef.php#L774

must be this:

```php
if ((!is_array($lookup_array[$firstRow])) || ($index_number > count($lookup_array))) {
```

**Comment by PowerKiKi** [comment]
Thank you for reporting in details.

Next time please consider contributing a PR on PhpSpreadsheet develop branch.
