### ISSUE TITLE
Use of lib on .xlsx files (XML) discard the following use of simpleXML

### ISSUE THREAD

**Issue by lcollong** [PHPOffice/PHPExcel#1345]
Hi,
Running php 7.1 stable. Using PHPExcel on a xlsx file (XML), generates an error while opening a file using simpleXML_load_file just after.
I'm using Joomla 3.8 and it seems related to some recent update (Joomla 3.5 -->3.8.1, Apache 2.2 --> 2.4 or PHP 5.6.30 --> 7.1) since all the three of them have been updated since last used).

Here is a simple test to reproduce the situation outside any framework :

```php
<?php
error_reporting(E_ALL);
ini_set('display_errors', TRUE);
ini_set('display_startup_errors', TRUE);

require_once  './libraries/PHPExcel/PHPExcel/IOFactory.php';
$inputFileName = './test.xlsx';	
$inputFileType = PHPExcel_IOFactory::identify($inputFileName);
echo 'file type of ' . $inputFileName . ' is : ' . $inputFileType;

$xml = simplexml_load_file('./language/fr-FR/fr-FR.xml'); // output : << Warning: simplexml_load_file(): I/O warning : failed to load external entity >>
echo 'xml : ';print_r($xml); // nothing of course.
```

if you replace "text.xlsx" by an Excel 2003 "test.xls" file, it works fluently.

it seems related to << libxml_disable_entity_loader >> according to this thread https://github.com/simplesamlphp/simplesamlphp/issues/241

Currently solved by setting it to false after each PHPExcel lib use :
`libxml_disable_entity_loader(false);`

But it should probably be managed from within PHPexcel ?

**Comment by PowerKiKi** [comment]
Was fixed in https://github.com/PHPOffice/PhpSpreadsheet/commit/9767112b23de2f93d4e035bcc468174a8308640e. Also PHPExcel does not support PHP 7.1. Consider upgrading to PhpSpreadsheet

**Comment by lcollong** [comment]
Ok. Thanks. However phpSpreadSheet seems to not be ready for a production site ? Currently only using reader features.
