### ISSUE TITLE
Use of PCLZip includes deprecation warning

### ISSUE THREAD

**Issue by hexmode** [PHPOffice/PHPExcel#1353]
From php 7.1:
> Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; PclZip has a deprecated constructor in .../vendor/phpoffice/phpexcel/Classes/PHPExcel/Shared/PCLZip/pclzip.lib.php on line 190

I would recommend just putting a dependency in to [pclzip/pclzip](https://packagist.org/packages/pclzip/pclzip) instead of bundling your own version.  The problem appears to have been solved upstream.

**Comment by PowerKiKi** [comment]
PHPExcel does not support PHP 7.1, consider upgrading to PhpSpreadsheet instead.
