### ISSUE TITLE
PCLZip:  A non well formed numeric value encountered in PclZip->privOptionDefaultThreshold()

### ISSUE THREAD

**Issue by rachidtarsimi** [PHPOffice/PHPExcel#1355]
Hello,

The calculation of memory limit in the the method `public function privOptionDefaultThreshold(&$p_options)` give a notice when the memory_limit has a suffix.
E.G: 1G or 1024M
The suffix is not stripped.

**Comment by PowerKiKi** [comment]
Fixed in PhpSpreadsheet (because it uses ZipArchive instead), consider upgrading.

**Comment by eko3alpha** [comment]
@rachidtarsimi - This is the same issue as

https://github.com/PHPOffice/PHPExcel/pull/1168

Your only option will be to download and patch this yourself until PhpSpreadsheet is production ready.
