### ISSUE TITLE
getLibXmlLoaderOptions disable load external xml content for script running from start PHPExcel load

### ISSUE THREAD

**Issue by gavrilovm** [PHPOffice/PHPExcel#1357]
Hello!
I try to used PHPExcel 1.8.1 in my little project. I looked bad situation and I have question to you.
Using PHPExcel on more page is good and I have used PHPExcel in phpunitest with getDataSet (PHPUnit_Extensions_Database_DataSet_CompositeDataSet).
This library used function simplexml_file_load. All good, but PHPExcel is set libxml_disable_entity_loader on true and disable external content. It's good for all, it's good for code security, but when Excel document is complete is no to set libxml_disable_entity_loader on enable loading external content. On this unittest have crash on teardown processing. I things this: my code can using simplexml_file_load anywhere and libxml_disable_entity_loader on true maybe can deliver problems.
How I can to resolve this situation does not stoped use PHPExcel ?

**Comment by PowerKiKi** [comment]
Fixed in PhpSpreadsheet, consider upgrading.
