### ISSUE TITLE
PHP extension zip not required

### ISSUE THREAD

**Issue by YetiCGN** [PHPOffice/PHPExcel#1359]
PHPExcel does require php-xml and php-xmlwriter, but not php-zip. However, without it the following error appears with PHP 7.0.22:
`Attempted to load class "ZipArchive" from the global namespace.
Did you forget a "use" statement for e.g. "PHPExcel_Shared_ZipArchive" or "PhpOffice\PhpWord\Shared\ZipArchive"?`

Is there a reason that the ZIP extension is not required in the library's composer.json?

**Comment by PowerKiKi** [comment]
Fixed in https://github.com/PHPOffice/PhpSpreadsheet/blob/1cec98016776338f3c30ef1bbfe66074d6b929aa/composer.json#L47
