### ISSUE TITLE
Opening Password Protected Excel File

### ISSUE THREAD

**Issue by arjereza** [PHPOffice/PHPExcel#1369]
Hi,

Is there a way to open/read/import a password protected excel file using PHPExcel?  I am trying to automate reading an excel file then uploading it to a database.  One of the requirements is to be able to open a password protected file.

Any help will be appreciated.

Thanks.

**Comment by arjereza** [comment]
Anyone?

Thanks.

**Comment by PowerKiKi** [comment]
Duplicate of #942
