### ISSUE TITLE
Syntax Error in functions.php line 581 -->  'break' not in the 'loop' or 'switch' context 

### ISSUE THREAD

**Issue by vusisindane** [PHPOffice/PHPExcel#1379]
I'm not sure if there's a newer version but this refers to version 1.8.0.
Look at the file below:
PHPExcel/Calculations/functions.php... line 581.  There is a syntax error.
**'break' not in the 'loop' or 'switch' context**

**Comment by PowerKiKi** [comment]
Duplicate of #1296

**Comment by PowerKiKi** [comment]
Duplicate of #1247,  #1084, #642, #1095
