### ISSUE TITLE
PHPExcel > 1.7.8 

### ISSUE THREAD

**Issue by karthikeyan-ameex** [PHPOffice/PHPExcel#1381]
Hi,

I updated the PHPExcel library based on the status report on my drupal backend. 

Now the PHPExcel library version I'm using is - 1.8.1
PHP version - 5.6.31

I Don't understand why it is still asking me to update the version of the PHPExcel library. Can anyone please help on this ?

Thanks,
Karthikeyan K.

**Comment by PowerKiKi** [comment]
https://github.com/PHPOffice/PHPExcel/blob/1.8/README.md
