### ISSUE TITLE
How to attach the PHPExcel output as PHPMailerAttachment

### ISSUE THREAD

**Issue by JoysonAnto** [PHPOffice/PHPExcel#1397]
i have tried these but not resolved
$excelstring = $objWriter->save('//php://output');
$mail->AddAttachment($excelstring, 'myfile.xls');

**Comment by danielfelix003** [comment]
try this,

$excelstring = $objWriter->save(sys_get_temp_dir() . '/myfile.xlsx');
$mail->AddAttachment(sys_get_temp_dir() . '/myfile.xlsx', 'myfile.xls');

you can also use any other directory instead of the temp directory
