### ISSUE TITLE
use diferent path for draw diferents images

### ISSUE THREAD

**Issue by tekit0** [PHPOffice/PHPExcel#1410]
it is possible to use a variable, for example:

$objDrawing = new PHPExcel_Worksheet_Drawing();
$objDrawing->setName('My Image');
$objDrawing->setDescription('The Image that I am inserting');
$objDrawing->setPath('img/n/**HERE_MY_VARIABLE**.png');
$objDrawing->setResizeProportional(true); $objDrawing->setWidthAndHeight(50, 50);
$objDrawing->setCoordinates('H4');
$objDrawing->setWorksheet($objPHPExcel->getActiveSheet());

**Comment by MarkBaker** [comment]
PHP string concatenation 101:

```
$myVariable = 'koolKatPicture';
$objDrawing->setPath('img/n/' . $myVariable . '.png');
```

**Comment by tekit0** [comment]
Oh, I feel the stupid question, my head is saturated. Thank you mate.
