### ISSUE TITLE
How do we use the tcpdf library to render into a PDF file?

### ISSUE THREAD

**Issue by simkimsia** [PHPOffice/PHPExcel#152]
I got a PDF Rendering library has not been defined.

I already downloaded the tcpdf library.

How do I call it?

**Comment by patricmutwiri** [comment]
I can't get it to work

**Comment by gekannt** [comment]
Me too, it would be nice to have sample with already included Pdf library.
There must be some tricky detail which is hard to grasp if you are not author of it

**Comment by PowerKiKi** [comment]
@gekannt try that: https://github.com/PHPOffice/PhpSpreadsheet/blob/develop/samples/21_Pdf_TCPDF.php. And tcpdf version is declared there: https://github.com/PHPOffice/PhpSpreadsheet/blob/develop/composer.json#L36
