### ISSUE TITLE
Add charts to excel

### ISSUE THREAD

**Issue by anais1477** [PHPOffice/PHPExcel#155]
Hello,

I'm trying to put a line chart in excel.
So i tried some examples you gave (33chartcreate-line.php, 33chartcreate-line.php, ...)
Each time, the file is created, i can see the table, but the chart is not displayed.

I just changed some lines to put it in format .xls :
$objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel5');
$objWriter->setIncludeCharts(TRUE);
$objWriter->save("line.xls");

Can you help me to display charts please ?

**Comment by MacGWik** [comment]
Is there's any update on this issue ?
