### ISSUE TITLE
Reading formatted data from excel column

### ISSUE THREAD

**Issue by shalinibajjuri** [PHPOffice/PHPExcel#227]
How to read formatted text form Excel Column?In My Excel  some part of text may be in bold,text may contain anchor links, Part of text may be in different font styles. My requirement is to read all the these formattings as HTML and save it in data base.
All formattings are missing with  getValue() function.

**Comment by keshavtest** [comment]
How to read formatted text form Excel Column?In My Excel some part of text may be in bold,

Thanks in advanced.

**Comment by jackbraj** [comment]
@keshavtest  MarkBaker method works just fine, What problem do you have exactly?

**Comment by danielgp** [comment]
[test.xlsx](https://github.com/PHPOffice/PHPExcel/files/254174/test.xlsx)

Given the attached file, and below code I am still failing to read the uppercase characters inside...

`$inputFileName = basename('test.xlsx');
$inputFileType = \PHPExcel_IOFactory::identify($inputFileName);
$objReader     = \PHPExcel_IOFactory::createReaderForFile($inputFileName);
$objReader->setReadDataOnly(true); // set this, to not read all excel properties, just data
$objPHPExcel   = $objReader->load($inputFileName);
$sheet         = $objPHPExcel->getSheet(0);
$cellToRead    = ['A1', 'A2'];
$cell          = $sheet->getCell($cellToRead[0]);
$cell2         = $sheet->getCell($cellToRead[1]);
echo '<style>table { width: 100% } th { background-color: #ff0 } '
	. 'table, th, td { border: 1px solid black; border-collapse: collapse; } </style>';
echo '<table>'
	. '<thead><tr><th>Should contain uppercase chars</th><th>Should be just plain text</th></tr></thead>'
	. '<tbody><tr><td style="width:50%;">';
if ($cell->getValue() instanceof \PHPExcel_RichText) {
	$elements          = $cell->getValue()->getRichTextElements();
	$cellValueAsString = '';
	if ($element instanceof \PHPExcel_RichText_Run) {
		foreach ($elements as $element) {
			// Rich text start?
			if ($element instanceof \PHPExcel_RichText_Run) {
				if ($element->getFont()->getSuperScript()) {
					$cellValueAsString .= '<sup>';
				} else if ($element->getFont()->getSubScript()) {
					$cellValueAsString .= '<sub>';
				}
			}
			// Convert UTF8 data to PCDATA
			$cellText          = $element->getText();
			$cellValueAsString .= htmlspecialchars($cellText);
			if ($element instanceof \PHPExcel_RichText_Run) {
				if ($element->getFont()->getSuperScript()) {
					$cellValueAsString .= '</sup>';
				} else if ($element->getFont()->getSubScript()) {
					$cellValueAsString .= '</sub>';
				}
			}
		}
	}
	echo $cellValueAsString;
} else {
	echo $cell->getValue();
}
echo '</td><td style="width:50%;">';
if ($cell2->getValue() instanceof \PHPExcel_RichText) {
	$elements2          = $cell2->getValue()->getRichTextElements();
	$cellValueAsString2 = '';
	if ($element instanceof \PHPExcel_RichText_Run) {
		foreach ($elements2 as $element) {
			// Rich text start?
			if ($element instanceof \PHPExcel_RichText_Run) {
				if ($element->getFont()->getSuperScript()) {
					$cellValueAsString2 .= '<sup>';
				} else if ($element->getFont()->getSubScript()) {
					$cellValueAsString2 .= '<sub>';
				}
			}
			// Convert UTF8 data to PCDATA
			$cellText           = $element->getText();
			$cellValueAsString2 .= htmlspecialchars($cellText);
			if ($element instanceof \PHPExcel_RichText_Run) {
				if ($element->getFont()->getSuperScript()) {
					$cellValueAsString2 .= '</sup>';
				} else if ($element->getFont()->getSubScript()) {
					$cellValueAsString2 .= '</sub>';
				}
			}
		}
	}
	echo $cellValueAsString2;
} else {
	echo $cell2->getValue();
}
echo '</td></tr></tbody></table>';`

**Comment by dbykadorov** [comment]
I have same problem, in Excel file cell looks formatted (http://joxi.ru/L21jlX6F6Xp13A) but `$cell->getValue()` returns a string. Also `getType()` method returns 's' value (string). Is this problem of source excel file or this is a problem of my code?

**Comment by abbyjaze** [comment]
```
if(!isset($cellData))
                    $cellData = (string)" ";
```
add this before after foreach loop of elements, it will remove the error.
