### ISSUE TITLE
 Problem with the encoding of Polish characters

### ISSUE THREAD

**Issue by MichalJanicki** [PHPOffice/PHPExcel#274]
Hello,

I have a problem with the encoding of Polish characters when converting HTML to XLS. I do this in the following way:

``` php
require 'PHPExcel.php';

$fileLocation = "myfile.html";

$file = fopen($fileLocation, "w");

$content = "<table>
    <tr>
        <th>ążźćńółę</th>
    </tr>
    <tr>
        <td>aaaaa</td>
    </tr>
</table>";

fwrite($file, $content);
fclose($file);

$objReader = new PHPExcel_Reader_HTML();
$objPHPExcel = $objReader->load('myfile.html');

$objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel5');
$objWriter->save('myexcel.xls');

```

The result of this code is wrong display Polish characters in xls file. I tried to set the encoding using setInputEncoding () but to no avail.

I'm using the latest version of PHPExcel

What did I do wrong?

**Comment by crazyserb** [comment]
Wait, what do you mean by adding "<? Xml encoding = "UTF-8">"?

Where? How?

How does a "fixed" code in your example look like then?

Thanks.
