### ISSUE TITLE
columnIndexFromString and stringFromColumnIndex are not compatible

### ISSUE THREAD

**Issue by lorenzulrich** [PHPOffice/PHPExcel#307]
From reading their names, I would assume that the functions mentioned above would be doing the same operation, but reversed. But they don't.

```
echo(PHPExcel_Cell:columnIndexFromString('A'));
// result: 1
echo(PHPExcel_Cell:stringFromColumnIndex(1);
// result: 2, expected: 1
```

Since I'm surely not the first to find this out: Are there any reasons for that behaviour?

**Comment by joe15000** [comment]
stringFromColumnIndex is working correctly.
columnIndexFromString is working incorrectly.

As written elsewhere in PHPExcel, columns start at 0, rows at 1.

So 
stringFromColumnIndex(0) = 'A' (expected 'A', correct) 
columnIndexFromString('A') = 1 (expected 0, incorrect)

If you don't know this and did not stumble across it in this bug report, the only way you have to find this out is by debugging it (this took me about 30 minutes to find out as this function was used as part of a larger loop and drove me nuts as it should have worked but didn't until I added "-1" to the end of it)

Maybe to add a flag to columnIndexFromString for base 1 (default for legacy) or base 0?

**Comment by PowerKiKi** [comment]
@joe15000 would you be interested in submitting a PR against PhpSpreadsheet that would break BC and change the behavior (without extra flags) ?
