### ISSUE TITLE
ZipArchive::getFromName(): Invalid or unitialized Zip object

### ISSUE THREAD

**Issue by treadmill** [PHPOffice/PHPExcel#318]
When trying to unzip an Excel spreadsheet saved in xlsx format, I get the following warnings.  PHPExcel is not able to read the contents.  However, I can open this specific file in Excel 2013.

Here's a link to the file in question: http://we.tl/dbvvc0Bnqs

Any other file I create with Excel 2013 in xlsx format works just fine.

<b>Warning</b>:  ZipArchive::getFromName(): Invalid or unitialized Zip object in <b>/var/www/chpqaforms/classes/PHPExcel/Reader/Excel2007.php</b> on line <b>323</b><br />
<b>Warning</b>:  ZipArchive::getFromName(): Invalid or unitialized Zip object in <b>/var/www/chpqaforms/classes/PHPExcel/Reader/Excel2007.php</b> on line <b>326</b><br />
<b>Notice</b>:  Trying to get property of non-object in <b>/var/www/chpqaforms/classes/PHPExcel/Reader/Excel2007.php</b> on line <b>358</b><br />
<b>Warning</b>:  Invalid argument supplied for foreach() in <b>/var/www/chpqaforms/classes/PHPExcel/Reader/Excel2007.php</b> on line <b>358</b><br />
<b>Warning</b>:  ZipArchive::getFromName(): Invalid or unitialized Zip object in <b>/var/www/chpqaforms/classes/PHPExcel/Reader/Excel2007.php</b> on line <b>323</b><br />
<b>Warning</b>:  ZipArchive::getFromName(): Invalid or unitialized Zip object in <b>/var/www/chpqaforms/classes/PHPExcel/Reader/Excel2007.php</b> on line <b>326</b><br />
<b>Notice</b>:  Trying to get property of non-object in <b>/var/www/chpqaforms/classes/PHPExcel/Reader/Excel2007.php</b> on line <b>395</b><br />
<b>Warning</b>:  Invalid argument supplied for foreach() in <b>/var/www/chpqaforms/classes/PHPExcel/Reader/Excel2007.php</b> on line <b>395</b><br />
<b>Warning</b>:  ZipArchive::close(): Invalid or unitialized Zip object in <b>/var/www/chpqaforms/classes/PHPExcel/Reader/Excel2007.php</b> on line <b>1707</b><br />

**Comment by rophiroth** [comment]
did anybody workaround this?

**Comment by hirschhm** [comment]
no workaround necessary.. check file permissions.
