### ISSUE TITLE
Add support for data validation on ranges rather than single cells

### ISSUE THREAD

**Issue by Daniel15** [PHPOffice/PHPExcel#325]
I would like to add validation on whole columns. My current hacky workaround is to set the validation on single cells, output the XLSX file using PHPExcel, then do my own manipulation to `sheet1.xml` and change the `sqref` for every `dataValidation` node (eg. change "A2" to "A2:A1048576"). Support for ranges with data validation would be nice to have built-in to PHPExcel itself.

**Comment by wernerkrauss** [comment]
You can already add validation to an area of the sheet:

```
$sheet->setDataValidation($rangeString, $validationObj);
```

**Comment by PowerKiKi** [comment]
thanks for the contribution @wernerkrauss

**Comment by huang-leiming** [comment]
thanks for the contribution @wernerkrauss@Daniel15

**Comment by huang-leiming** [comment]
thanks for the contribution @wernerkrauss @Daniel15
