### ISSUE TITLE
Autoloader, using prepend parameter php >= 5.3 

### ISSUE THREAD

**Issue by doofer** [PHPOffice/PHPExcel#388]
File:
PHPExcel/Autoloader.php

Location:
58:        return spl_autoload_register(array('PHPExcel_Autoloader', 'Load'), true, true);

This breaks compatibility with php < 5.3.
http://www.php.net/manual/ro/function.spl-autoload-register.php

**Comment by BetsabethTorrres** [comment]
tengo el mismo error Fatal error: Class 'PHPExcel_Shared_String' not found in \PHPExcel\Autoloader.php on line 11 

line 11 -> PHPExcel_Shared_String::buildCharacterSets(); 

sin embargo veo que ya esta lo que comentan en la libreria, alguna otra sugerencia ? 
class PHPExcel_Autoloader
{
    /**
     * Register the Autoloader with SPL
     *
     */
    public static function register()
    {
        if (function_exists('__autoload')) {
            // Register any existing autoloader function with SPL, so we don't get any clashes
            spl_autoload_register('__autoload');
            
        }
        // Register ourselves with SPL
        if (version_compare(PHP_VERSION, '5.3.0') >= 0) {
            return spl_autoload_register(array('PHPExcel_Autoloader', 'load'), true, true);
        } else {
            return spl_autoload_register(array('PHPExcel_Autoloader', 'load'));
        }
    }
