### ISSUE TITLE
Cell cache does not work at all (php 5.5 / PHPExcel 1.8.0)

### ISSUE THREAD

**Issue by roeycohen** [PHPOffice/PHPExcel#415]
Hi,
None of the cache methods are working for me.
I am using php 5.5 with PHPExcel 1.8.0 and I'm calling PHPExcel_Settings::setCacheStorageMethod before initializing a PHPExcel object but still without success.

here's a complete code sample that fails:

``` php
<?php
require_once 'PHPExcel.php';
require_once 'PHPExcel/IOFactory.php';

ini_set("memory_limit", '2M'); // enlarging this value makes the script work...

$cacheMethod = PHPExcel_CachedObjectStorageFactory::cache_in_memory_serialized;
$cacheSettings = [];
PHPExcel_Settings::setCacheStorageMethod($cacheMethod, $cacheSettings);

$objPHPExcel = new PHPExcel();
$objPHPExcel->setActiveSheetIndex(0);

$sheet = $objPHPExcel->getsheet();
for ($row = 0; $row < 1024; $row++)
{
    for ($col = 0; $col < 5; $col++)
    {
        $sheet->setCellValueByColumnAndRow($col, $row+1, $row.':'.$col);
    }
}

$objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel2007');
$objWriter->save('php://output'); 
```

Thanks.

**Comment by bittu7861** [comment]
fdgdf

**Comment by bittu7861** [comment]
Hi,
 I have create a xlsx file which contains 51 column and  85000 row and approx size 15 MB with phpexcel using php command line but php.exe used 2GB RAM and after some time error occur with VirtualAlloc failed and php error with out of memory.
I am using all cache method excepted sqlite. Please help me to create this excel with following codes.

public function exportxlsx7($query, $path) {
        ini_set('max_execution_time', 2400);
        ini_set('memory_limit', -1);          
		$this->db->cache_on();		
        $tr = $this->db->query("SELECT COUNT(*) AS Total FROM ($query) AS ctable "); 
		$this->db->cache_off();
		$tr = $tr->first_row();
		$tr = $tr->Total;    
		include_once(APPPATH.'libraries/PHPExcel/PHPExcel.php');

		$cacheMethod = PHPExcel_CachedObjectStorageFactory:: cache_to_discISAM;
		$cacheSettings = array('dir'  => 'application/cache/excel');
		if (PHPExcel_Settings::setCacheStorageMethod($cacheMethod, $cacheSettings)) {
			echo date('H:i:s') , " Enable Cell Caching using " , $cacheMethod , " method";
		} else {
			echo date('H:i:s') , " Unable to set Cell Caching using " , $cacheMethod , " method, reverting to memory";
		}
		$this->phpexcel = new PHPExcel();
        $getActiveSheet = $this->phpexcel->getActiveSheet();
        $setActiveSheet1 = $this->phpexcel->setActiveSheetIndex(0);
        $center_bold = array(
            'alignment' => array(
                'horizontal' => PHPExcel_Style_Alignment::HORIZONTAL_CENTER,
            ),
            'font' => array(
                'bold' => true,
                'size' => 11,
            ),
            'borders' => array(
                'allborders' => array(
                    'style' => PHPExcel_Style_Border::BORDER_THIN,
                )
            ),
            'fill' => array(
                'type' => PHPExcel_Style_Fill::FILL_SOLID,
                'color' => array('rgb' => 'A5A5A5'),
            )
        );
        $start = 0;
        $pages = ceil($tr / $this->bexcelrecord);
        $cpage = 1;
        $row = 1;
        $far = array();
        $sr = 0;
        while ($cpage <= $pages) {
            $start = ($cpage - 1) * $this->bexcelrecord;			
            $nquery = " $query LIMIT {$start}, {$this->bexcelrecord} ";
			($start != 0) ? $this->db->cache_on() : '';
            $r = $this->db->query($nquery);
			($start != 0) ? $this->db->cache_off(): '';
            if ($start == 0) {
                $fields = $r->field_data();
                foreach ($fields as $col => $v) {
                    $far[$v->name] = $v->type;
                    $lastcol = PHPExcel_Cell::stringFromColumnIndex($col);
                    $getActiveSheet->getColumnDimension($lastcol)->setWidth(15);
                    $getActiveSheet->getStyle($lastcol . '1')->applyFromArray($center_bold);
                    $setActiveSheet1->setCellValueByColumnAndRow($col, $row, $v->name); //->getStyle(chr($i) . $row)->applyFromArray($center_bold);        
                }
            }
            foreach ($r->result_array() as $v) {
                $row++;
                $col = 0;
                foreach ($far as $f => $n) {
                    if ($v[$f] && $v[$f] != '0') {
                        $lastcol = PHPExcel_Cell::stringFromColumnIndex($col);
                        if ((false === stripos($f, 'time') && ($n == '12' || $n == '10')) || (FALSE != stripos($f, 'date') && FALSE === stripos($v[$f], ','))) {
                            $v[$f] = vdate($v[$f], '-', 'd-M-Y');
                            if ($v[$f]) {
                                $d = new DateTime($v[$f]);
                                $getActiveSheet->getStyle($lastcol . $row)->getNumberFormat()->setFormatCode(PHPExcel_Style_NumberFormat::FORMAT_DATE_CUSTOMDDMMMMYYYY);
                                $setActiveSheet1->setCellValueByColumnAndRow($col, $row, PHPExcel_Shared_Date::PHPToExcel($d));
                            }
                        } else {
                            if (false != stripos($f, 'time') && ($n == '12' || $n == '11')) {
                                $v[$f] = vdate($v[$f], '-', 'H:i:s');
                            }
                            $setActiveSheet1->setCellValueByColumnAndRow($col, $row, utf8_encode($v[$f]));
                        }
                    }
                    $col++;
                }               
            }
			echo "\n" . $pages.' / '.$cpage;
            $r->free_result();           
            $cpage++;
        }        
        try {
			$stime = time();
            $objWriter = PHPExcel_IOFactory::createWriter($this->phpexcel, 'Excel2007');
            $objWriter->save($path);
			$etime = time();
			echo "\n";
			echo $etime - $stime;
        } catch (Exception $e) {
			echo $e->getMessage();            
        }
}
