### ISSUE TITLE
Pie chart won't work in Excel 2013

### ISSUE THREAD

**Issue by taylorren** [PHPOffice/PHPExcel#426]
Can you check the pie chart is working in Excel 2013? The example (`33chartcreate-pie.xlsx`) and my code does not seem to work. The XLSX file always opened with an error and if I choose to continue to open the XLSX, the drawing will be deleted from the XLSX file. 

For urgent review, please.

**Comment by lode** [comment]
@taylorren, in case you were still wondering (I was), it is a bug in the example code. You should not use `PHPExcel_Chart_DataSeries::GROUPING_STANDARD` for pie charts, see https://github.com/PHPOffice/PHPExcel/pull/435.

**Comment by warden1975** [comment]
Can anyone confirm that the bugfix did work? I just tried downloading the version release 1.8.1 but it doesn't seem working. Thanks in advance.

**Comment by fiero300** [comment]
Hi, I have the same problem, someone solve this?, help please.

**Comment by necorobsd** [comment]
Same problem... https://github.com/affinitybridge/phpexcel/blob/master/Tests/33chartcreate-pie.php not working too.

**Comment by axonaris** [comment]
Unfortunately setting PlotGrouping to NULL (or any other groupping type) doesn't help in **Excel 2016** (Office 365). Still error when opening file with pie chart.

**Comment by bees4ever** [comment]
Version 1.8 solved this problem! Thank you!

**Comment by taylorren** [comment]
Finally! Can anyone test and comment on the status of a pie chart in Excel?
