### ISSUE TITLE
Cross-sheet formulae are saved without calculated values

### ISSUE THREAD

**Issue by Synchro** [PHPOffice/PHPExcel#433]
I'm using PHPExcel 1.8.0.

I'm generating a summary worksheet that shows selected values from other sheets in the workbook with code like this:

```php
$sheet->setCellValue('C9', "='$sheetname'!B9");
```

When I open the resulting `.xlsx` spreadsheet in LibreOffice, it contains the correct formula (after conversion from Excel's format, e.g. `='results1'!B9` is converted to `=$'results1'.B9`) but always shows a value of `0`. If I edit the formula, for example delete the last '9' then retype it and hit enter, the correct value is shown.

If I open a generated document in Excel 2011, save it under a different name (without editing anything) and reopen it in LibreOffice, the correct values are shown. So all the content appears correct, but the Excel files that PHPExcel is generating are somehow different from the ones that Excel generates.

To investigate a little further, I compared a PHPExcel-generated and an Excel-resaved version of the same spreadsheet from inside the xlsx bundle. I found that the original PHPExcel version had all `v` elements set to a zero value (like `<f>'results1'!B9</f><v>0</v>`), whereas the resaved version had the correct values in those elements (like `<f>'results1'!B9</f><v>8</v>`), so I have to conclude that this is a PHPExcel bug, as LibreOffice is only showing the value the file says.

I also found that Apple Numbers shows correct values, ignoring the saved zero values.

**Comment by matmattia** [comment]
The same problem exists with PHPExcel 1.8.1.

**Comment by Synchro** [comment]
That change does fix this problem for me. There's [a separate problem in LibreOffice](https://bugs.documentfoundation.org/show_bug.cgi?id=82135) caused by this bug that means it's reluctant to recalculate such formulae. Should you want a test case, I used this to demo the bug:

```php
<?php
require 'includes/vendor/autoload.php';
PHPExcel_Cell::setValueBinder(new PHPExcel_Cell_AdvancedValueBinder());
$PHPExcel = new PHPExcel;
$PHPExcel->removeSheetByIndex(0);
$sheet1 = $PHPExcel->createSheet();
$sheet2 = $PHPExcel->createSheet();
$sheet1->setTitle('sheet1');
$sheet2->setTitle('sheet2');
$sheet2->setCellValue('A1', 123);
$sheet1->setCellValue('A1', "='sheet2'!A1");
$objWriter = PHPExcel_IOFactory::createWriter($PHPExcel, 'Excel2007');
$objWriter->preCalculateFormulas = false;
$objWriter->save('exceltest.xlsx');
```
