### ISSUE TITLE
Undefined variable: options in PHPExcel/Settings.php on line 384

### ISSUE THREAD

**Issue by dinamic** [PHPOffice/PHPExcel#434]
I am receiving this error message:
```PHP Notice:  Undefined variable: options in /path/to/my/project/vendor/phpoffice/phpexcel/Classes/PHPExcel/Settings.php on line 384```

It seems it has been fixed in the `develop` branch, but it is not merged to the last stable tag - 1.8.0.

Can you advise on how to get the fix?

**Comment by bonswouar** [comment]
Hello,
Any news about the `1.8.1` release ?
We're currently using your library with [liuggio/ExcelBundle](https://github.com/liuggio/ExcelBundle), and having the `Undefined variable: options` problem.
Would be nice to have a new stable version tag to be able to make a PR on this Bundle.
Thank you for your work !

**Comment by quimcalpe** [comment]
@MarkBaker Is 1.8.1 going to happen? Do you recom mend to use master or develop branches instead?

Thanks

**Comment by GreeKatrina** [comment]
I am getting this issue as well. Is the 1.8.1 release happening soon? It's been ~6 months now.

**Comment by GreeKatrina** [comment]
Also, not sure if this is a good solution, but to anyone else who can't wait for the update. I changed the file from this:
```php
    public static function getLibXmlLoaderOptions()
    {
        if (is_null(self::$_libXmlLoaderOptions)) {
            self::setLibXmlLoaderOptions(LIBXML_DTDLOAD | LIBXML_DTDATTR);
        }
        @libxml_disable_entity_loader($options == (LIBXML_DTDLOAD | LIBXML_DTDATTR));
        return self::$_libXmlLoaderOptions;
    } // function getLibXmlLoaderOptions
```
to this:

```php
    public static function getLibXmlLoaderOptions()
    {
        if (is_null(self::$_libXmlLoaderOptions)) {
            self::setLibXmlLoaderOptions(LIBXML_DTDLOAD | LIBXML_DTDATTR);
        }
        @libxml_disable_entity_loader(self::$_libXmlLoaderOptions == (LIBXML_DTDLOAD | LIBXML_DTDATTR));
        return self::$_libXmlLoaderOptions;
    } // function getLibXmlLoaderOptions
```

**Comment by isleshocky77** [comment]
I get this as a Fatal error on the develop branch but NOT on the 1.8.1 tag.

**Comment by dinamic** [comment]
I am not working on a project that makes use of the library, so I cant test right now.
Can someone else confirm it works, so we can thank the developer and close the issue?

Thanks!

**Comment by isleshocky77** [comment]
I would say this issue shouldn't be closed yet if this error is showing on the develop branch. From what I read on their [Contributing Instructions](https://github.com/PHPOffice/PHPExcel#want-to-contribute) develop is supposed to be the working copy to branch from and should be most up to date. If that's true it means that the next tag after 1.8.1 will contain this bug again.

I didn't get to dig into what is actually happening there, but it may be something with switching from $_libXmlLoaderOptions to just $libXmlLoaderOptions. The error went away when I switched all instance of $_libXmlLoaderOptions to $libXmlLoaderOptions; however, I don't know what adverse effects this will have as I just had to do it to make a minor change to something unrelated.

**Comment by dinamic** [comment]
@MarkBaker can you advise on that?

**Comment by chordstricken** [comment]
Open up the PHPExcel_Settings class (Classes/PHPExcel/Settings.php) and see lines `368`, `379`, and `385`. Change references of this:
```
self::$_libXmlLoaderOptions
```
to this
```
self::$libXmlLoaderOptions
```
That seemed to solve the problem for me

**Comment by isleshocky77** [comment]
@chordstricken Yes, that is what I was saying; however, I was worried why the variable names changed and if merely changing those three places would effect anything else.  

After looking at that file I found the following commit 4f8c9bfc966c0b77a8353f422b8f485d035edd2a by @MarkBaker which is merely a PSR code change and seems to not catch all instances of the variable `$this->_libXmlLoaderOptions`.

This is a little scare because it makes me extremely weary of that commit and what else it may have broken.

**Comment by marcelloitallo** [comment]
Change line 379
     public static function getLibXmlLoaderOptions()
to 
     public static function getLibXmlLoaderOptions($options = null)

This worked for me!

**Comment by PowerKiKi** [comment]
The original bug was fixed in 1.8.1 which was released a while ago. The rest of the mentioned bugs were fixed in https://github.com/PHPOffice/PhpSpreadsheet develop branch

**Comment by seemas-grazitti** [comment]
Notice: Undefined variable: zipClass in /var/www/vhost/timesheet.grazitti.com/html/PHPExcel/Writer/Excel2007.php on line 227

 
Fatal error: Uncaught Error: Class name must be a valid object or a string in /var/www/vhost/timesheet.grazitti.com/html/PHPExcel/Writer/Excel2007.php:227 Stack trace: #0 /var/www/vhost/timesheet.grazitti.com/html/admin_report_specific_user.php(764): PHPExcel_Writer_Excel2007->save('/tmp/phpxltmpF0...') #1 {main} thrown in /var/www/vhost/timesheet.grazitti.com/html/PHPExcel/Writer/Excel2007.php on line 227

I am getting this issue. Please let me know solution and i am using 1.8.1 version.

**Comment by PowerKiKi** [comment]
@seemas-grazitti, please do not copy-paste your issue report in other threads.
