### ISSUE TITLE
Simple calculation in formatted date cell returns empty string

### ISSUE THREAD

**Issue by ncrypthic** [PHPOffice/PHPExcel#437]
Hi,

I have following fixed format date cell (DD-MM-YYYY)

| No | A | B | C |
| ----|----|----|--- |
| 1 | 06-09-2014 | 16-09-2014 | 26-09-2014 |

with actual cell values

- **A1** '09/06/2014'
- **B1** '=A1+10'
- **C1** '=B1+10' 

when I try to get the cell value for **B1** and **C1** using ```var_dump($cell->getValue());``` I get empty string ```''```

But when I changed the formula to **=INT(_cell_address_)+10** in cell **B1** and **C1** I get correct excel serialized date values:

- **B1**: 41908
- **C1**: 41918

Can somebody advise on how correct the calculation behavior?

Cheers,
Lim

**Comment by ncrypthic** [comment]
After digging around I found this 

When creating excel file using Ms Excel 2013, the sheet.xml looks like this
```xml
<row r="1" spans="1:2" x14ac:dyDescent="0.25">
    <c r="A1" s="1">
        <v>42095</v>
    </c>
    <c r="B1" s="1">
        <f>A1+7</f>
        <v>42102</v>
    </c>
</row>
```
While using Libreoffice Spreadsheet the sheet.xml looks this
```xml
<row collapsed="false" customFormat="false" customHeight="false" hidden="false" ht="12.1" outlineLevel="0" r="1">
    <c r="A1" s="1" t="n">
        <v>42095</v>
    </c>
    <c r="B1" s="1" t="inlineStr">
        <f aca="false">A1+7</f>
        <is>
            <t>
            </t>
        </is>
    </c>
</row>
```

The attributes ```t="inlineStr"``` in sheet.xml produces by Libreoffice spreadsheet makes PHPExcel loader read the cell as inline string and ignoring the ```<f/>``

https://github.com/PHPOffice/PHPExcel/blob/develop/Classes/PHPExcel/Reader/Excel2007.php#L850-L853

Can we check for ```<f/>``` element just to be sure before using ```inlineStr``` dataType like sample below ?

```php
case "inlineStr":
    if(isset($c->f)) {
        $this->_castToFormula($c,$r,$cellDataType,$value,$calculatedValue,$sharedFormulas,'_castToError');
    } else {
        $value = $this->_parseRichText($c->is);
    }
    break;
```

**Comment by MarkBaker** [comment]
Thanks for the fix, now implemented
