### ISSUE TITLE
Setting workbook password does not seem to work at all

### ISSUE THREAD

**Issue by adonix** [PHPOffice/PHPExcel#442]
I've searched for a while and it looks like the correct way of password protecting a file is to do this:

```
    $phpExcelObject->getSecurity()->setLockWindows(true);
    $phpExcelObject->getSecurity()->setLockStructure(true);
    $phpExcelObject->getSecurity()->setWorkbookPassword("PHPExcel");
```

However, this does not seem to work at all because when opening the file, it does not prompt for a password at all. Am I missing something here? The file gets saved and sent as a StreamResponse to the user downloading the file (using Excel2007 writer). I'm also using LibreOffice to open the file.

**Comment by cksachdev** [comment]
I am trying to achieve the same. I want entire workbook content to visible only once the right password is supplied. Is it possible with v1.8.1?
