### ISSUE TITLE
Undefined offset and getBlipType Error when loading a xls (excel5) with images in it

### ISSUE THREAD

**Issue by iboinas** [PHPOffice/PHPExcel#464]
Hello guys!

First of all, congrats for this amazing work!!

I think i found this bug. If i remove images from file, it loads ok. With any image, when
$objPHPExcel = PHPExcel_IOFactory::load( $file );
I get: ............. Undefined offset: -1 ......... On line 911 from PHPExcel\Reader\Excel5.php

That is .... 
$BSE = $BSECollection[$BSEindex - 1];  // here is the problem, value of index will be -1
$blipType = $BSE->getBlipType();

From my understading, means $BSEindex is with zero value...

Of course this will bring problem later, on method "getBlipType", that is being called on a non-object...

Is this bug, or am i undestanding something wrong??

Thanks in advance!

Wish i knew a little more, to fix it and contribute!!

iboinas

**Comment by PowerKiKi** [comment]
Should be solved in https://github.com/PHPOffice/PhpSpreadsheet/commit/b964788d5c55f9c08a2320579d33a809bfa6c1f2

**Comment by AdriWild** [comment]
Worked!!!
