### ISSUE TITLE
Conditional Formatting Error

### ISSUE THREAD

**Issue by versionii** [PHPOffice/PHPExcel#481]
I'm building a spreadsheet with conditional formatting. 

When I open the file in Open Office 4.0.1 it works as expected.

However, when I open the file in MS Excel 2007 I get the following:

Excel found unreadable content. Do you want to repair?

I clicked Yes.

Then a dialog pops up that reads, "Removed Feature: Conditional formatting from /xl/worksheets/sheet1.xml part"

Here is the Repair Log:

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<recoveryLog xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><logFileName>error081960_02.xml</logFileName><summary>

Errors were detected in file 'C:\Users\Audra Hughes\AppData\Local\Microsoft\Windows\INetCache\Content.Outlook\CGDL3OSM\participants (62).xlsx'</summary>

<removedFeatures summary="Following is a list of removed features:"><removedFeature>Removed Feature: Conditional formatting from /xl/worksheets/sheet1.xml part</removedFeature></removedFeatures></recoveryLog>

And here's the section of php code I'm using to create the conditional formatting:

//Create second sheet (locations lookup)
////////////////////////////////////////////////////////////////////////////////////////////
$sheet_name = preg_replace("/[^0-9a-zA-Z\s_]/", "", $page_labels['org_1_name']);
$sheet_name = preg_replace('/\s+/', '_', $sheet_name);

$sheet = new PHPExcel_Worksheet($objPHPExcel, $sheet_name);
$objPHPExcel->addSheet($sheet, 1);

$org_1_count = 1;

foreach ($org_1s AS $org_1){
    //$crumbs = get_parent_nodes_for_display($org_1['id']);

```
$objPHPExcel
    ->setActiveSheetIndex(1)
    ->setCellValue('A' . $org_1_count, $org_1['id'])
    ->setCellValue('B' . $org_1_count, $org_1['name']);

$org_1_count++;
```

}

//create named range
$objPHPExcel->addNamedRange( new PHPExcel_NamedRange('Org1', $objPHPExcel->getSheet(1), '!$B$1:$B$' . $org_1_count . '') );

//create condition
$objConditional1 = new PHPExcel_Style_Conditional();
$objConditional1->setConditionType(PHPExcel_Style_Conditional::CONDITION_EXPRESSION);
$objConditional1->setOperatorType(PHPExcel_Style_Conditional::OPERATOR_NONE);
$objConditional1->addCondition('IF(ISERROR(MATCH($E2,Org1,0)))');
$objConditional1->getStyle()->getFont()->getColor()->setARGB(PHPExcel_Style_Color::COLOR_RED);
$objConditional1->getStyle()->getFont()->setBold(true);

$conditionalStyles = $objPHPExcel->getSheet(0)->getStyle('E2')->getConditionalStyles();
array_push($conditionalStyles, $objConditional1);

$objPHPExcel->getSheet(0)->getStyle('E2:E20000')->setConditionalStyles($conditionalStyles);

**Comment by inyerade** [comment]
Same here.
Any solution?
