### ISSUE TITLE
undefined method PHPExcel_Reader_HTML::getPhpExcelStyleArray()

### ISSUE THREAD

**Issue by djones8520** [PHPOffice/PHPExcel#491]
At line 399 in phpoffice/phpexcel/Classes/PHPExcel/Reader/HTML.php the error in the title occurs.  My code is below.  After I create the PHP_Reader_HTML object (using either the new keyword or the factory), the error occurs when the load function is called.  

I looked through the source code both downloaded on my machine as well as on github and I don't see the function getPhpExcelStyleArray().  If I comment line 399 in the HTML.php file, it seems to work correctly.

       $tmpFile = '/Temp/' . time() . '.html';
        file_put_contents($tmpFile, $html);

        // Read the contents of the file into PHPExcel Reader class
        //$reader = new \PHPExcel_Reader_HTML();
        $reader = \PHPExcel_IOFactory::createReaderForFile($tmpFile);

        $content = $reader->load($tmpFile);

**Comment by MarkBaker** [comment]
Fixed, thanks

**Comment by huqa** [comment]
I have this same problem. Still have to comment line 399 out manually.

**Comment by MarkBaker** [comment]
So are you using the latest code from the develop branch? Because line 399 is definitely commented out - https://github.com/PHPOffice/PHPExcel/blob/develop/Classes/PHPExcel/Reader/HTML.php#L399

**Comment by huqa** [comment]
Oh sorry, I didn't notice. I'm using composer to fetch the dev-master branch. I'll switch to dev-develop then. Thanks!
