### ISSUE TITLE
Reading a XLSX-File fails

### ISSUE THREAD

**Issue by donajena** [PHPOffice/PHPExcel#50]
Hello there!

I try to read a XLSX-File with following code:
$inputFileType = PHPExcel_IOFactory::identify($inputFileName);
/*\*  Create a new Reader of the type that has been identified  **/
$objReader = PHPExcel_IOFactory::createReader($inputFileType);
/**  Load $inputFileName to a PHPExcel Object  **/
$objPHPExcel = $objReader->load($inputFileName);

It works fine for Excel2007 files if I create them with Excel.

Now I want to read XLXS files from Suunto movescount.com. You can download XLSX-Files from movescount and save them on harddisk. If I want to read them, I have to open them first with Excel and then save again.

If I do not open with Excel and save again, I can not read these files. Has anybody a solution or idea?

Thanks,
Dominik

**Comment by ultrinnan** [comment]
This is because downloaded file is in HTML format (but names as .xmlx)

**Comment by rijoshrc** [comment]
I did the following steps to fix this.

`$inputFileName = 'test.xlsx';`
`$inputFileType = PHPExcel_IOFactory::identify($inputFileName);`
`$objReader = PHPExcel_IOFactory::createReader($inputFileType);`
`$objReader->setReadDataOnly(true);`
`$objPHPExcel = $objReader->load($inputFileName);`

Install the ZipArchive if not already installed
`sudo apt-get install php7.0-zip`
`sudo service apache2 restart`
