### ISSUE TITLE
How to apply autosize on Merged Columns?

### ISSUE THREAD

**Issue by haroonabbasi** [PHPOffice/PHPExcel#504]
### Labels : Type - Question
Hi, before posting this question i try to search in existing issue. But i couldn't find any thing related to it so i am posting  this question.
> How to apply autosize on Merged Columns?

**Comment by maxgalbu** [comment]
Related: http://stackoverflow.com/questions/21333143/phpexcel-setautosize-for-merged-cells

**Comment by haroonabbasi** [comment]
@maxgalbu thanks for answer, i opened this issue while back. i guess i was able to fix it in same way described in stack-overflow answer. but thanks going to close this thread.
