### ISSUE TITLE
Undefined index warnings

### ISSUE THREAD

**Issue by robertharm** [PHPOffice/PHPExcel#507]
Probably not a big deal, anyway a user of mine sent me the following logs when trying to import new maps within Maps Marker Pro via the PHPExcel interface I built:

```Notice*: Undefined index: $ in */wp-content/plugins/leaflet-maps-marker-pro/inc/import-export/PHPExcel/Cell.php > <http://carmelcarwash.com/wp-content/plugins/leaflet-maps-marker-pro/inc/import-export/PHPExcel/Cell.php>* on > line *777* > > *Notice*: Undefined index: $ in */wp-content/plugins/leaflet-maps-marker-pro/inc/import-export/PHPExcel/Cell.php > <wp-content/plugins/leaflet-maps-marker-pro/inc/import-export/PHPExcel/Cell.php>* on > line *780*```

It worked despite this message - anyway as I did not change core PHPExcel files for my integration, I just wanted to let you now. Unfortunately I cannot reproduce this issue on my server. If it is just someting minor in your opinion, please close this ticket.

**Comment by MarkBaker** [comment]
It's possible that your script may be referencing a PHPExcel_Cell cell reference from a variable that you've used in single quotes (`'$cellref'`) rather than double quotes (`"$cellref"`) or unquoted (`$cellref`). That could cause a problem.

Alternatively it could be an absolute refererence (`$A$1`) rather than (`A1`), though that should be handled by PHPExcel

**Comment by robertharm** [comment]
thanks for the info - will have a look!

**Comment by rm-fixeads** [comment]
I have the same problem. This error occurs before I execute any of my code.
Here is an example:
```
require 'vendor/autoload.php';

$xlsFile = __DIR__ . '/translations.xlsx';
$sheetName = 'SITE Translations';

$objReader = PHPExcel_IOFactory::createReader('Excel2007');
$objPHPExcel = $objReader->load($xlsFile);
```
The moment I execute `$objReader->load()` it throws this error:
```
PHP Notice:  Undefined index: $ in /home/path/translations/vendor/phpoffice/phpexcel/Classes/PHPExcel/Cell.php on line 809
PHP Stack trace:
PHP   1. {main}() /home/path/translations/index.php:0
PHP   2. PHPExcel_Reader_Excel2007->load() /home/path/translations/index.php:15
PHP   3. PHPExcel_Worksheet_AutoFilter->setRange() /home/path/translations/vendor/phpoffice/phpexcel/Classes/PHPExcel/Reader/Excel2007.php:1012
PHP   4. PHPExcel_Cell::rangeBoundaries() /home/path/translations/vendor/phpoffice/phpexcel/Classes/PHPExcel/Worksheet/AutoFilter.php:131
PHP   5. PHPExcel_Cell::columnIndexFromString() /home/path/translations/vendor/phpoffice/phpexcel/Classes/PHPExcel/Cell.php:729
PHP Notice:  Undefined index: $ in /homepath/translations/vendor/phpoffice/phpexcel/Classes/PHPExcel/Cell.php on line 809
PHP Stack trace:
PHP   1. {main}() /home/path/translations/index.php:0
PHP   2. PHPExcel_Reader_Excel2007->load() /home/path/translations/index.php:15
PHP   3. PHPExcel_Worksheet_AutoFilter->setRange() /home/path/translations/vendor/phpoffice/phpexcel/Classes/PHPExcel/Reader/Excel2007.php:1012
PHP   4. PHPExcel_Cell::rangeBoundaries() /home/path/translations/vendor/phpoffice/phpexcel/Classes/PHPExcel/Worksheet/AutoFilter.php:131
PHP   5. PHPExcel_Cell::columnIndexFromString() /home/path/translations/vendor/phpoffice/phpexcel/Classes/PHPExcel/Cell.php:730
```

**Comment by kamwoz** [comment]
@rm-fixeads My xlsx file had collapsed rows, when I expanded them, error dissapeared
