### ISSUE TITLE
trailing white space

### ISSUE THREAD

**Issue by pgee70** [PHPOffice/PHPExcel#510]
Hi
using a cool tool to find php white space - http://fossil.include-once.org/phptags/index  i found that your project has trailing white space in a file:

phpoffice/phpexcel/Classes/PHPExcel/Shared/PCLZip/pclzip.lib.php: TRAILING whitespace ("?>\r\n")

regards

Pete

**Comment by MarkBaker** [comment]
Thanks, fixed
