### ISSUE TITLE
PHPExcel fills some cells with FALSE

### ISSUE THREAD

**Issue by izanev** [PHPOffice/PHPExcel#514]
Okay, this is going to be a weird one. It happens in a very specific set of circumestances (and I'm not sure if planet alignments are also involved in this :) ).

What happens?

The Writer fills in some cells with the FALSE value, even though these cells contain valid UTF-8 texts.

Details:

Composer:
Installing phpoffice/phpexcel (dev-develop 31aa953)

For input, I use the HTML reader:
		$reader = new \PHPExcel_Reader_HTML(); 

I'm using the Excel2007 writer for output like so:
		$objWriter = PHPExcel_IOFactory::createWriter($content, 'Excel2007');

I wanted to see what's the origin of this problem and decided to have a go with it. I found that the Reader makes a preg replace. If I turn off the preg replace, everything works fine:

//                $domText = preg_replace('/\s+/', ' ', trim($child->nodeValue));
$domText = $child->nodeValue;

This is located in the _processDomElement function of the PHPExcel_Reader_HTML class.

I have also made a small HTML file which can be used to reproduce the problem. I don't know how to attach it to the issue though. Let me know.

**Comment by MarkBaker** [comment]
Unfortunately, github doesn't yet support attaching files to issues, though you can still attach files against [issue #10749](http://phpexcel.codeplex.com/workitem/10749) on the old codeplex site.

Alternatively, try adding the `u` (UTF-8) switch to the regular expression

```php
$domText = preg_replace('/\s+/u', ' ', trim($child->nodeValue));
```

If you can upload a file to demonstrate the problem though, it would allow me to test it myself

**Comment by izanev** [comment]
Sure thing, Mark.

The 'u' modifier successfully resolved the issue! Thank you ;)

This is the file name: cell_value_sometimes_false_utf8_preg_whitespace.html

The last cell will be FALSE.
