### ISSUE TITLE
How to add inline class name to table

### ISSUE THREAD

**Issue by derekang** [PHPOffice/PHPExcel#523]
Hi, 

$objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'HTML');
$objWriter->save('example.html');

I successfully generated the html file. May i know how can i add a class name attribute to the table tag?

**Comment by MarkBaker** [comment]
PHPExcel doesn't provide any method to modify the generate html at all, you'd need to either modify the HTML Writer, or use DOM to modify the generated markup
