### ISSUE TITLE
Undefined variable: contents in PHPExcel/Shared/ZipArchive.php:173

### ISSUE THREAD

**Issue by mokaton** [PHPOffice/PHPExcel#535]
subj

**Comment by sakibulalam** [comment]
any solution to this?

**Comment by MarkBaker** [comment]
What branch? Because I can't see anything in the script that would cause this error, and line 173 doesn't even exist in that file (it's only 163 lines long)

**Comment by Holisollogistics** [comment]
Hi guys please help me out in this issue...
the following code returns the error in some cases...

Code::
\Excel::load(public_path() . '/calculator/' . $name, function($results) { });

Error ::
ErrorException in ZipArchive.php line 173:
Undefined variable: contents

**Comment by PowerKiKi** [comment]
Install PHP zip extension if not done yet, and before any PHPExcel use, do:

```php
PHPExcel_Settings::setZipClass(PHPExcel_Settings::ZIPARCHIVE);
```

**Comment by Holisollogistics** [comment]
I have already done this...

**Comment by PowerKiKi** [comment]
Double-check when/where you set the settings. If done properly the class you have an error in is never even used at all.

**Comment by Holisollogistics** [comment]
Yeah Thanks @PowerKiKi.....It's working now...
