### ISSUE TITLE
Reader->load() causes fatal error due to 'undefined method' getID()

### ISSUE THREAD

**Issue by redcuillin** [PHPOffice/PHPExcel#545]
Recently switched to using PHPExcel via Composer. However the following very straightforward code (copied straight out of documentation) causes a fatal error

Fatal error: Call to undefined method PHPExcel::getID() in path_to/vendor/phpoffice/phpexcel/Classes/PHPExcel/Calculation.php on line 1729

     $reader = PHPExcel_IOFactory::createReaderForFile($filename);
     $reader->setReadDataOnly(true);
     $spreadsheet = $reader->load($filename);

Any ideas what's going on here, and whether there is a workaround if this is a bug?

**Comment by MarkBaker** [comment]
It sounds like a confusion to me: the `getID()` method for the PHPExcel object definitely exists, though I'm not sure why the loader should be trying to access it.... I'll have to create a test case to try and see what it's doing, but I can't understand why it should give an error

**Comment by redcuillin** [comment]
Ok - I've worked it out. This will have been caused by a clash between the Composer-included versions, and a call to the old PEAR library that still existed in the code. Apologies for wasting your time.
