### ISSUE TITLE
Style Bug: getCellByColumnAndRow()->getStyle() ->applyFromArray 

### ISSUE THREAD

**Issue by fkoch1980** [PHPOffice/PHPExcel#551]
Code Example:
$blueBold = array( "font" => array("bold" => true,"color" => array("rgb" => "0000ff"),),);
$greenNotBold = array("font" => array("bold" => false,"color" => array("rgb" => "00ff00"),),);

What is happening: Cells 1,1 and 2,1 are always formatted with which ever style is applied last. When the cells are added in this order.

$workbook->getActiveSheet()->getCellByColumnAndRow(1,1)->getStyle()->applyFromArray($blueBold)
$workbook->getActiveSheet()->getCellByColumnAndRow(2,1)->getStyle()->applyFromArray($greenNotBold)

then they are green and not bold. When they are added in this order

$workbook->getActiveSheet()->getCellByColumnAndRow(2,1)->getStyle()->applyFromArray($greenNotBold)
$workbook->getActiveSheet()->getCellByColumnAndRow(1,1)->getStyle()->applyFromArray($blueBold)

they are blue and bold

What should happen:
Cell 1,1 should be blue and bold. Cell 2,1 should be green and not bold.

This bug is related to another bug that was fixed around Sept. 2014:
$worksheet->setCellValue("A1", "blue, bold", true)->getStyle()->applyFromArray($blueBold);

Details of previous fixed bug:
http://stackoverflow.com/questions/25754144/phpexcel-cell-getstyle-applyfromarray

**Comment by MarkBaker** [comment]
This issue has already been fixed

**Comment by rahmat1996** [comment]
are you sure? so how we can insert style(like bold or something) into getCellByColumnAndRow.
thank's.

**Comment by MarkBaker** [comment]
There's a whole [lot of documentation on how to set cell styles](https://github.com/PHPOffice/PHPExcel/blob/develop/Documentation/markdown/Overview/08-Recipes.md#styles)
