### ISSUE TITLE
Whitespace after toRichTextObject() + fix

### ISSUE THREAD

**Issue by Xairoo** [PHPOffice/PHPExcel#554]
Using toRichTextObject() to encode a HTML string:

```<strong>bold</strong>, <em>italic</em>, <strong><em>bold+italic</em></strong>```

becomes:
**bold** , *italic* , ***bold+italic***

I fixed this for me:
@PHPExcel/Classes/PHPExcel/Helper/HTML.php
```php
    protected function parseElementNode(DOMElement $element) {
        $callbackTag = strtolower($element->nodeName);
        $this->stack[] = $callbackTag;

        $this->handleCallback($element, $callbackTag, $this->startTagCallbacks);

        $this->parseElements($element);
        $this->stringData .= ' ';
        array_pop($this->stack);

        $this->handleCallback($element, $callbackTag, $this->endTagCallbacks);
    }
```
Should be:
```php
        $this->stringData .= ''; // whitespace removed
```

**Comment by MarkBaker** [comment]
This space is necessary in some cases, simply removing it may merge words together.... e.g. in the 42richText.php example, it removes the space between `h2so4` and `is` and between `2<sup>3</sup> and `equals`.
