### ISSUE TITLE
Excel2003XML Without Styles throws warning

### ISSUE THREAD

**Issue by isleshocky77** [PHPOffice/PHPExcel#558]
I have encountered an Excel2003XML file which does not contain styles at all. Due to this the reader throws a warning when trying to iterate over the styles array.

> Warning: Invalid argument supplied for foreach() in /vendor/phpoffice/phpexcel/Classes/PHPExcel/Reader/Excel2003XML.php on line 411

**Comment by markdegrootnl** [comment]
Can we merge this or submit a PR?

**Comment by PowerKiKi** [comment]
Please submit a PR against [PhpSpreadsheet](https://github.com/PHPOffice/phpspreadsheet#phpexcel-vs-phpspreadsheet-) develop branch.

**Comment by dnmange** [comment]
I am getting this issue, is there any work around to slve this, please let me know i am running on a deadline to deliver this my module any help is appreciated

**Comment by isleshocky77** [comment]
This is two year old issue which wasn't even looked at until now. I've added the [PR](https://github.com/PHPOffice/PhpSpreadsheet/pull/331) for the PHPOffice/PHPExcel against the develop branch; but that's about all I'm prepared to do on this.

It's pretty obvious this issue will not be updated and the PR will not be merged, so I'm closing both.
