### ISSUE TITLE
Unicode normalization

### ISSUE THREAD

**Issue by rubenarslan** [PHPOffice/PHPExcel#569]
I think PHPexcel does not deal with [NFD characters](https://tex.stackexchange.com/questions/94418/os-x-umlauts-in-utf8-nfd-yield-package-inputenc-error-unicode-char-u8%CC%88-not) gracefully?
I.e. it gives out something like this \xCC\x88\xC3\x9F which then leads to an exception when trying to put it in the DB? Those can be pretty annoying to search for, as I discover now.

I used the below bash script to generate a failure. The third line gets garbled. I think ideally it would be normalised instead.

```bash
(
  echo 'type,name,label'
  echo -e 'note,nfc,"UTF-8-NFC: \xc3\xa5\xc3\xa4\xc3\xb6\xc3\xbc\xc3\x85\xc3\x84\xc3\x96\xc3\x9c\xc3\x9f.'
  echo -e 'note,nfd,"UTF-8-NFD: \x61\xcc\x8a\x61\xcc\x88\x6f\xcc\x88\x75\xcc\x88\x41\xcc\x8a\x41\xcc\x88\x4f\xcc\x88\x55\xcc\x88\xc3\x9f'
) > test.csv
```

**Comment by nik045** [comment]
same here

**Comment by rubenarslan** [comment]
Sorry, I realised this is really something for me to deal with, not PHPExcel.
