### ISSUE TITLE
Getting hyperlinks from worksheets

### ISSUE THREAD

**Issue by Rogier076** [PHPOffice/PHPExcel#580]
Hi,

I've just recently started using PHPExcel. MY primary use is reading a excel product price list file supplied by one of my suppliers to import into magento. Since this supplier only provides xlsx files, I have been working with PHPExcel on this matter.
Now all works great except for one thing; One column (I) contains the word 'details', which has a hyperlink  to my supplier's website. Since I want to grab the product its image from the page supplied in this hyperlink, I really would like to get the hyperlink behind it. However, the function getCell() (in worksheet class) only returns a cell object that only contains a  string ('details') and not a link. trying function hasHyperlink(I**) returns false. Using the function hasHyperlink() on the object returned by getCell() also returns false. (not strange since it returns hasHyperlink() from the object its parent as I've seen in code).

I suppose the hyperlink functions should work, but they don't. If I open the worksheet in Excel (2010) all these cells clearly have hyperlinks. 

By the way; I found these hyperlink functions by working myself through the code (I didn't find a topic on it in the documentation).

Here is some of my code:

```php
public function readXlsx($file = false){
		if(!$file){
				die('no file supplied!');
		}
		$this->xr = PHPExcel_IOFactory::createReaderForFile($file);
		$this->xr->setReadDataOnly(true);
		$excel = $this->xr->load($file);
		$objWorksheet = $excel->getSheetByName('category sheet');
		// Get the highest row number and column letter referenced in the worksheet
		$highestRow = $objWorksheet->getHighestRow(); // e.g. 10
		$highestColumn = $objWorksheet->getHighestColumn(); // e.g 'F'
		// Increment the highest column letter
		$highestColumn++;

		for ($row = 2; $row <= $highestRow; ++$row) {
			$status = $objWorksheet->getCell('R' . $row);
			$brand = (string) $objWorksheet->getCell('E' . $row);
			if(strpos(strtolower($brand),brand name') !== false && strtolower($status) != 'sell-out'){
				$part = (string) $objWorksheet->getCell('B' . $row);
				//var_dump($this->getProduct($part)); //function gets product information based on part number
				$test = $objWorksheet->getCell('I' . $row)->hasHyperlink();
				var_dump($test); //always returns false!!
			}
			
		}


	}//function readXlsx(){
```

I am using PHPExcel 1.8.1 . I tried 1.9 first, but there was no documentation available for it, hence I ended up using 1.8.1.

I hope you can help me out. If required, I can supply the price list, but not publicly since it is confidential.

Thanks in advance.

Edit: The list is supplied as xlsx (excel 2007) format.

**Comment by Rogier076** [comment]
Fixed the issue after five minutes after posting by setting
```php
$this->xr->setReadDataOnly(true);
```
to
```php
$this->xr->setReadDataOnly(false);
```
Thanks anyway :)

**Comment by proliv** [comment]
That's it, and what's the function you use to show the hyperlink?

**Comment by proliv** [comment]
Oh, i found the solution :)
$url = $sheet->getHyperlink('E' . $row)->getUrl();
