### ISSUE TITLE
Can date be formatted automatically?

### ISSUE THREAD

**Issue by Serhioromano** [PHPOffice/PHPExcel#584]
I am using this example.

```php
$rowArray = array('Value1', 'Value2', 'Value3', 'Value4');
$objPHPExcel->getActiveSheet()
    ->fromArray(
        $rowArray,   // The data to set
        NULL,        // Array values with this value will not be set
        'C3'         // Top left coordinate of the worksheet range where
                     //    we want to set these values (default is A1)
    );
```

And one of the values is date. I do not want to access every cell. In fact document is complex and that would be problematic. 

Is there any string format like ISO8601 that would be automatically formatted as date? For instance if string matches `2015-05-22T15:38:46+00:00` then it is date format.

Possible?

**Comment by MarkBaker** [comment]
Why not just apply the advanced value binder, which can recognise dates, percentages, fractions, etc and set appropriate styling..... and if you don't want fractions, percentages, etc, or want a slightly different format to be applied then create your own value binder

**Comment by Serhioromano** [comment]
Would you please refer me to advanced binders example?

**Comment by MarkBaker** [comment]
In the `/Examples`folder, `29advancedvaluebinder.php` uses the Advanced Value binder that we provide as an example, which is defined in [/Classes/PHPExcel/Cell](https://github.com/PHPOffice/PHPExcel/blob/1.8/Classes/PHPExcel/Cell/AdvancedValueBinder.php)

This is covered in the documentation [here](https://github.com/PHPOffice/PHPExcel/blob/develop/Documentation/markdown/Overview/08-Recipes.md#write-a-date-or-time-into-a-cell)
