### ISSUE TITLE
Conditional formatting bugs

### ISSUE THREAD

**Issue by Sogl** [PHPOffice/PHPExcel#598]
Hi,

Bugs:
1. If I load excel file with conditional formatting, all "check if true" become unchecked. Only load and save, without manipulations.
2. White and without colour conditions sometimes becomes yellow.
3. Format of each condition becomes "General". No matter if you use without format or something special. All my dates with conditions becomes numbers.

I can't use my conditional formatting at all with all of this problems.

More info here: http://stackoverflow.com/questions/31130071/how-to-copy-full-conditional-formatting-with-phpexcel

**Comment by PowerKiKi** [comment]
@Khigashiguchi you should try PhpSpreadsheet and see if it still happens

**Comment by Khigashiguchi** [comment]
@PowerKiKi Thank you for your information, phpspreadsheet can work in PHP5.3?

**Comment by PowerKiKi** [comment]
No, it cannot. PHP 5.6 minimum.
