### ISSUE TITLE
Empty the buffer before you export Excel documents

### ISSUE THREAD

**Issue by wxb** [PHPOffice/PHPExcel#610]
I export Excel file to local when I reference `01simple-download-xlsx.php` file, Unable to open the Excel file.
![2015-07-21_130819](https://cloud.githubusercontent.com/assets/7111495/8793518/b24767c4-2faa-11e5-8c7e-3a7ea7d277ed.png)

Fortunately, I have solved the problem，I use function `ob_end_clean()--Clean (erase) the output buffer and turn off output buffering` in php. 
So I suggest that we should use this function when exporting files to empty the buffer，It avoids some inexplicable error and do no wrong。

like this
```php
    ob_end_clean();  //  Clean (erase) the output buffer and turn off output buffering
    header('Content-Disposition: attachment;filename="'.$fileName.'.xlsx"');
    header('Cache-Control: max-age=0');
    $objWrite = PHPExcel_IOFactory::createWriter($objPHPExcel, $excelType);
    $objWrite->save('php://output');
    exit;
```

**Comment by MarkBaker** [comment]
Generally it means that your script is outputting something else to the browser. Using ob_end_clean() to flush the browser is a workround; your best solution is to identify what is being sent to the browser and fix it

**Comment by wxb** [comment]
@MarkBaker Thank you !
I just use `require` include a php file, the file difine a array!
