### ISSUE TITLE
Excel2007 Writer : Could not close zip file php://output

### ISSUE THREAD

**Issue by MHAPRR** [PHPOffice/PHPExcel#624]
Hello,

I got 2 versions of PHPExcel : 1.8 and an older version that doesn't allow chart creation.
With the older version, 01simple-download-xlsx.php is working correctly (01simple-download-xls.php and 01simple.php are also working)

But with the 1.8 version, I'm able to create charts and save files locally but I failed at running 01simple-download-xlsx.php (01simple-download-xls.php and 01simple.php are working BUT not 01simple-download-ods.php)

I don't understand why this is not working, and I have tested several solutions (change PHP version, create a temp folder for sessions, give total control on all files, to everyone, etc...)

The error message I get (edited the result .xlsx file with notepad++) is : 
<br />
<b>Fatal error</b>:  Uncaught exception 'PHPExcel_Writer_Exception' with message 'Could not close zip file php://output.' in C:\Program Files\Autodesk\Autodesk Infrastructure Web Server Extension 2013\www\Classes\PHPExcel\Writer\Excel2007.php:400
Stack trace:
#0 C:\Program Files\Autodesk\Autodesk Infrastructure Web Server Extension 2013\www\Examples\01simple-download-xlsx.php(89): PHPExcel_Writer_Excel2007-&gt;save('php://output')
#1 {main}
  thrown in <b>C:\Program Files\Autodesk\Autodesk Infrastructure Web Server Extension 2013\www\Classes\PHPExcel\Writer\Excel2007.php</b> on line <b>400</b><br />

So, Is this a bug ? Or maybe there is something i'm missing...

I'm using PHP version 5.3.8-win64 with IIS 7

**Comment by ucheng** [comment]
Does the folder has write permission? This solve my problem: http://stackoverflow.com/questions/21436949/phpexcel-writer-exception-with-message-could-not-close-zip-file-php-output

**Comment by MHAPRR** [comment]
Hey,

Thx for the reply. I played a lot with folders permissions but did not managed to get better results.

I have found a workaround by working on another server ( older IIS version and php version) and It worked correctly. 
Regards
