### ISSUE TITLE
Is 1.9 autoloader compatible with Yii 1 ?

### ISSUE THREAD

**Issue by realtebo** [PHPOffice/PHPExcel#626]
I'm using old 1.8 version from PHPExcel on CodePlex.

I'm supposing that this is the SAME tool. Is it right? There is none type of alert on codeplex about project migration to github, sigh... so I see only today this project.

If yes, Now I'd like to upgrade to 1.9. I see that directory structure is changed, and it's changed the autoloader.

Do you know if this autoload is compatible with Yii 1.1.*?

**Comment by MarkBaker** [comment]
Yes, it is the same project.

The notification about switching to github is one the front page of the [codeplex site](http://phpexcel.codeplex.com/):

 > __2012-06-19 PHPExcel Moves to github!__
The source repository for PHPExcel, together with its sister projects PHPWord and PHPPowerPoint under the auspices of PHPOffice. The repository can be found at https://github.com/PHPOffice/PHPExcel, and the latest working development code is in the develop branch.
 > This is the first part of series of changes in our development process which we believe will make it easier for us to do more frequent releases of better quality code. The next step will be CI integration for running automated unit testing against PHP 5.2, 5.3 and 5.4 using TravisCI.
 > We shall be maintaining the CodePlex SVN Source repository in parallel for a time, but the github repository should be considered the definitive source.

with a subsequent reminder posted a year later:

> __2013-05-22 We are on Github!__
Please remember that we have been using github as our source repository for nearly a year now.... source code has not been maintained here on Codeplex in all that time. 
 > If you want to contribute, you can fork it. We do accept Pull Requests.


However, the 1.9 branch is not yet fully working, and should be considered highly unstable and subject to change without notice until it is officially released.

**Comment by realtebo** [comment]
I started using this project only in January of 2014, so I've not noticed this migrations alert. Also, you should close issue logging and update codeplex home page to be even more clear that source code REALLY is no more updated. In fact 1.8 version was updated also on code plex, so I was opening issues, and waiting for fixes on this site, and not here on github. 

No problem. I upgraded to 8.1
