### ISSUE TITLE
Unable to insert a new column

### ISSUE THREAD

**Issue by realtebo** [PHPOffice/PHPExcel#627]
Simple code

```
 $inputFileType = PHPExcel_IOFactory::identify($file_path);
 $objReader = PHPExcel_IOFactory::createReader($inputFileType); 
 $objReader->setReadDataOnly(false);
 $objPHPExcel = $objReader->load($file_path);

 $cacheMethod    = PHPExcel_CachedObjectStorageFactory::cache_to_phpTemp;
 $cacheSettings  = array( 'memoryCacheSize' => '128MB');
 $cacheEnabled   = PHPExcel_Settings::setCacheStorageMethod($cacheMethod);

 $sheet          = $objPHPExcel->setActiveSheetIndex(0);
 $sheet->insertNewColumnBeforeByIndex($column_number+$inserted+1,1);
```

When outputting the file, no new column is inserted. I echoed the vars to be sure that index was right and indexes were right. 

Also, I tried to set cell value in the header cell of the "new column" and I can see that the new header is written but it overrides the old column, because this old column is not shifted to the right as I expected.

Starting point 

```
A    B     C
```

I insert before '2'  and set cell value to 'new'

Exprected

```
A  new  B  C
```

I got 

```
A  new  C
```

What error am I doing?

NOTE: this happens only when usign cache, disabling the cache all is working well

**Comment by shijuubaid** [comment]
Hi realtebo,

How did you resolve this issue???
