### ISSUE TITLE
Bulleted list inside cell

### ISSUE THREAD

**Issue by oroalej** [PHPOffice/PHPExcel#630]
Hello, How can I make this possible? I try to look for it in the  getStyle, getFonts and PHPExcel_RichText() but i found nothing. Does PHPExcel supported this formatting?

Thank you

**Comment by MarkBaker** [comment]
Excel doesn't have any magical style setting to do this: you simply want a string containing newline characters and your bullets, and then to set the cell to wrap

```php
$value = "• Foo\n• Bar";
$objPHPExcel->getActiveSheet()
    ->setCellValue('A10', $value);
$objPHPExcel->getActiveSheet()
    ->getRowDimension(10)
    ->setRowHeight(-1);
$objPHPExcel->getActiveSheet()
    ->getStyle('A10')
    ->getAlignment()
    ->setWrapText(true);
```
