### ISSUE TITLE
PHPExcel_IOFactory::load() converts 0.0632 to 0.06320000000000001

### ISSUE THREAD

**Issue by tomaszozga** [PHPOffice/PHPExcel#632]
It sounds pretty unbelievable, however if the excel file that I do upload a cell with value `0.0632` is inserted then it's magically read as `0.06320000000000001`. It does not happen to any other value. If in the same cell I'll put `0.0631` then output is `0.0631`.

I tried it with few versions of library.

The same happens if I use `toArray` or `$phpExcelObject->getActiveSheet()->getCell('G2')->getCalculatedValue()`

**Comment by MarkBaker** [comment]
[Floating Point Accuracy Problems](https://en.wikipedia.org/wiki/Floating_point#Accuracy_problems)
