### ISSUE TITLE
After upgrade from 1.8 to 1.8.1 every Excel I generate is 'corrupted'

### ISSUE THREAD

**Issue by realtebo** [PHPOffice/PHPExcel#633]
I recently upgraded from 1.8 to 1.8.1.

Since that day, every Excel I create or modify into my app is 'corrupted'. Excel opens them with a warning, asking the permission to recovery. I'm not able to understand WHAT is the problem, because I'm using this library to create about 100 different excel files into my app and EVERY ONE now is corrupted. 

How can I diagnose the cause?

**Comment by mdemori** [comment]
just a quick tips, open damaged file with an editor capable to handle binary files (to see the hex version of the file) so you can check if there is something wrong with output file created from your tool with the new library version.
I think that can be something related to some error or warning triggered by new library version. If there are errors these will be written at beginning of the files before the real binary excel file and you can receive the error described.

**Comment by firegate666** [comment]
Or use register error and exception handler and write errors, warnings and notices to a log file.

**Comment by realtebo** [comment]
@mdemori , @firegate666 : thanks for the idea. 

This is the logged error (that was written at the very end of the .xlsx file)

    <b>Notice</b>:  Undefined property:  PHPExcel_Calculation::$_savedPrecision in
    <b>vendor/PHPExcel/Calculation.php</b> on line <b>1743</b>

I'm quite sure that I've fight against this problem even in the 1.8, but actually I cannot find a track about the patch I've done to the lib. If I'll find, I'll send a PR about it.

**Comment by realtebo** [comment]
See this Issue I opened in may of 2014, because I've not understand that project has been moved here yet: https://phpexcel.codeplex.com/workitem/20797
