### ISSUE TITLE
PHP 7 Compatability

### ISSUE THREAD

**Issue by tracerrx** [PHPOffice/PHPExcel#642]
Has anyone tested under PHP 7 yet?  I do see some ereg calls in the pclzip.lib.php

**Comment by MarkBaker** [comment]
If you're running PHP7, then you shouldn't need to use pclzip at all anyway

**Comment by MarkBaker** [comment]
But yes, I have been running tests against PHP7, without identifying any specific issues that can't be eliminated (such as dropping the use of pclzip) anyway

**Comment by blasto333** [comment]
php excel version 1.8.0 php 7 rc 4

Fatal error: 'break' not in the 'loop' or 'switch' context in /Applications/MAMP/htdocs/phppos/PHP-Point-Of-Sale/application/libraries/PHPExcel/PHPExcel/Calculation/Functions.php on line 581
A PHP Error was encountered

Severity: Compile Error

Message: 'break' not in the 'loop' or 'switch' context

Filename: Calculation/Functions.php

Line Number: 581

Backtrace:

**Comment by doniking82** [comment]
not sure what the break; on line 581 is for after an return statement.
I would just remove it.

**Comment by MarkBaker** [comment]
That is old code..... 1.8.1 is the latest release, and has been available since April, and the develop branch has been fixed to eliminate that break

**Comment by tomzx** [comment]
Duplicated by #716.

**Comment by jorddyrojas** [comment]
Estoy usando php 7 y me esta dando el mismo problema con respecto a la linea 581 y pues no se como solucionarlo quizas alguien me brinde algun ejemplo en el que pueda estudiarlo!
Soy estudiante y estoy haciendo mi proyecto y lo que necesito es exportar datos desde postgresql a excel mediante phpexcel.

**Comment by PowerKiKi** [comment]
This has been solved a while ago. Upgrade to latest PHPExcel.

**Comment by jorddyrojas** [comment]
Ya e resuelto con la version de PhpExcel 1.8.1 thank´s!

**Comment by thilina19** [comment]
<b>Fatal error</b>: Class 'PHPExcel Writer Excel 2013' not found in <b>C:\xampp\htdocs\excel\Classes\PHPExcel\IOFactory.php</b> on line <b>141</b><br />

**Comment by PowerKiKi** [comment]
@thilina19 you should not have space in a class name, ever. This is unrelated to PHP 7.

I am locking this thread, because **PHPExcel 1.8.1 is compatible with PHP 7**.
