### ISSUE TITLE
Excel2007 Merged Cell Parsing Error

### ISSUE THREAD

**Issue by pappastech** [PHPOffice/PHPExcel#643]
I'm using the following code to parse an Excel file and have found that when PHPExcel encounters a merged cell, is returns the contents of the merged cell but then returns a blank as though it's really parsing two cells.

Let's say that columns C and D are merged, column 2 in the $data array below would have the contents of the merged cell and column 3 in the $data array below would have 20 empty elements.

I think I'm using this correctly and believe this to be a bug, but I have been able to locate where the code for this is located to attempt to submit a bugfix.

Tom

```php
$inputFileType = 'Excel2007';
$inputFileName = $argv[1];

/**  Create a new Reader of the type defined in $inputFileType  **/
$objReader = PHPExcel_IOFactory::createReader( $inputFileType );

/**  Load $inputFileName to a PHPExcel Object  **/
$objPHPExcel = $objReader->load( $inputFileName );

/** Select the appropriate worksheet **/
$objPHPExcel->setActiveSheetIndex( 1 );

/** Read the header row **/
$idx = 0; $row = 0; $header = array();
for ( $col = 0; $col < 20; $col++ )
{
  for ( $row = 0; $row < 20; $row++ )
  {
    $data[$col][$row] = $objPHPExcel->getActiveSheet()->getCellByColumnAndRow( $col, $row )->getValue();
  }
}
```

**Comment by MarkBaker** [comment]
Well as you're trying to read from every individual cell of the merge range, what do you expect PHPExcel to do?

If you've merged cells A1 and B1, then cell A1 holds the value, so what should PHPExcel do when you call getCell() on B1? What do you think should happen? Should it throw an exception for you to handle in your code? Should it return a null value? Should it return the value of the top-left cell of the merge range?

This isn't a bug, this is PHPExcel's behaviour.

If you need to test whether a cell is part of a merge range before getting the value for that cell, then you can do so.
```
// ignore merge cell unless it's the top-left cell in the merge range
if (!$objPHPExcel->getActiveSheet()->getCellByColumnAndRow( $col, $row )->isInMergeRange() ||
    $objPHPExcel->getActiveSheet()->getCellByColumnAndRow( $col, $row )->isMergeRangeValueCell()) {
    // Cell is one that we're interested in reading
} else {
    // Cell is part of a merge-range that we're not interested in reading
}
```
