### ISSUE TITLE
Call to undefined method PHPExcel_Calculation::_getMatrixDimensions()

### ISSUE THREAD

**Issue by bharlow** [PHPOffice/PHPExcel#651]
I am using PHPExcel 1.8.1 and ran into an undefined method error. After testing, I narrowed it down to the following Excel calculation which throws the error.

``` php
$countif = '="Playing in " & ROWS(A3:A4918)';
$objSheet->setCellValue('A4919', $countif);
```

When I run it I receive the following error message:

Fatal error: Call to undefined method PHPExcel_Calculation::_getMatrixDimensions() in C:\inetpub\wwwroot\mysite\thirdparty\phpexcel\PHPExcel\Calculation\LookupRef.php on line 244

**Comment by enfoqueNativo** [comment]
Could this be a typo or is it missing a wrapper function?, there is a private method _getMatrixDimensions_ in PHPExcel_Calculation. Same fatal error when using **COLUMNS** functions as well.

**Comment by PowerKiKi** [comment]
The [line 244 in PHPExcel 1.8.1 is a blank line](https://github.com/PHPOffice/PHPExcel/blob/372c7cbb695a6f6f1e62649381aeaa37e7e70b32/Classes/PHPExcel/Calculation/LookupRef.php#L244). So either the error message is wrong, or you don't have the latest version.

Please provide a [Minimal, Complete, and Verifiable example](http://stackoverflow.com/help/mcve) of code that exhibits this issue with latest version. That way there will be more chance for the issue to be solved.

**Comment by enfoqueNativo** [comment]
@PowerKiKi  You're right.. i'm on 1.8.x-dev(forgot to mentiion it). Requested code example:
```
<?php
$objPHPExcel = new PHPExcel();
$objPHPExcel->getActiveSheet()->setCellValue('A1', 'Range #1')
                              ->setCellValue('A2', 3)
                              ->setCellValue('A3', 7)
                              ->setCellValue('A4', 13)
                              ->setCellValue('A5', '=SUM(A2:A4)');

$objPHPExcel->getActiveSheet()->setCellValue('B1', 'Range #2')
                              ->setCellValue('B2', 5)
                              ->setCellValue('B3', 11)
                              ->setCellValue('B4', 17)
                              ->setCellValue('B5', '=SUM(B2:B4)');

$objPHPExcel->getActiveSheet()->setCellValue('C7', 'Total range:');
$objPHPExcel->getActiveSheet()->setCellValue('D7', '=ROWS(A2:B5)');

$objPHPExcel->setActiveSheetIndex(0);
$objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel5');
$objWriter->save('example.xls');
```

Regards

**Comment by PowerKiKi** [comment]
This works. Please downgrade to a stable release, or if you really need bleeding edge, upgrade to [PhpSpreadsheet](https://github.com/PHPOffice/phpspreadsheet#phpexcel-vs-phpspreadsheet-).

![image](https://cloud.githubusercontent.com/assets/72603/21535362/536c927c-cdb7-11e6-82ba-66bb9b4d28f2.png)
