### ISSUE TITLE
Class 'PHPExcel_Writer_csv' not found in IOFactory.php

### ISSUE THREAD

**Issue by combatx007** [PHPOffice/PHPExcel#653]
When i use this bundle (ver. 1.8.1) on debian, i have that error:

Fatal error:  Class 'PHPExcel_Writer_csv' not found ../vendor/phpoffice/phpexcel/Classes/PHPExcel/IOFactory.php on line 141

There are not any errors when i use windows

**Comment by MarkBaker** [comment]
What are you doing to try and use the csv Writer?
Are you perhaps doing something like:

```
$objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'csv');
```

The Writer names are case-sensitive
so you'd need to specify the Writer name correctly as 'CSV' rather than 'csv'

```
$objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'CSV');
```

**Comment by combatx007** [comment]
Case-sensitive, of course! Thank you very much!! My problem is solved now!
