### ISSUE TITLE
Export of chart to PDF does not work when installed from composer

### ISSUE THREAD

**Issue by wpsgit** [PHPOffice/PHPExcel#654]
Hi

It seems if I install PHPExcel via composer and try to output chart in PDF it does not work. However if I manually download the files from github and replace them in the folder the same code seems to be exporting the chart in PDF.

Let me know if this is something related to code or my computer related problem.

Thanks

**Comment by MarkBaker** [comment]
There do appear to be some problems with the PDF rendering engines handling embedded images, which may or may not be affecting you

**Comment by wpsgit** [comment]
ok thanks for quick response, what is confusing is code works great if installed manually and if installed through composer it does not output graph. Anyways I will continue with the manual step for now.

**Comment by scando1993** [comment]
Is this solved? or which engine works best?  I'm using dompdf and I can't get to render the graphs
