### ISSUE TITLE
Sorting table: is stille not possible?

### ISSUE THREAD

**Issue by realtebo** [PHPOffice/PHPExcel#657]
I've enable autofilter to allow our users to custom sort the data table.

We'd like to serve our file yet sorted by the first column, A to Z. But I read in the wiki that it's not supported. Is still not possible?

Ref: https://github.com/PHPOffice/PHPExcel/blob/develop/Documentation/markdown/Features/Autofilters/06-Autofilter-Sorting.md

**Comment by MarkBaker** [comment]
I've looked at this task before when I did the original work on autofilters, and it really is a major piece of work, with a large memory and execution overhead. Excel doesn't simply display the rows in a different order, it actually moves the rows themselves.

As such, it's not a piece of work that I'm willing to do

**Comment by realtebo** [comment]
@MarkBaker Thanks for the honest reply.
I totally agree with you. If something is a near totally a waste of time and memory, the task must be killed!
I just released my code with a note for users: "After opening the file, click on the filter icon on the column P and the order A to Z"  
It has been approved, so I'm happy anyway. 
Closed.
