### ISSUE TITLE
"hacked by" source comments lead to false identification as hacker credits by VaultPress

### ISSUE THREAD

**Issue by robertharm** [PHPOffice/PHPExcel#660]
I use PHPExcel as import tool in my WordPress plugin Maps Marker Pro. A user now reported the following issue:

-
VaultPress detected a new security issue on one of your sites, zoneski.com/reseau. Our security scanners found 1 new security threats since the last email notification (6 weeks ago). Please visit the VaultPress security page for more details. 
Suspicious Code Our security scanners detected the following possible security issues. We recommend that you review the affected files. PHP.Generic.Hacker.Credits Sometimes hackers like to leave a calling card behind on sites they attack. 
This code appears to contain a calling-card, and should be checked for potential hacks. 
/PHPExcel/Reader/Excel5.php 
/PHPExcel/Shared/OLERead.php 
Please visit your VaultPress security page for more details. If you have any questions, feel free to contact us at https://vaultpress.com/contact/. At VaultPress, we are constantly updating our security scanners to help keep your sites safe from all the latest threats. 

-

To prevent further false detections like that, I would suggest changing the source code comment from "hacked by" to "credits by"

**Comment by rdoursenaud** [comment]
IMHO You should rather contact vaultpress for them to flag this false positive.

**Comment by robertharm** [comment]
I also contacted VaultPress, thought I also let you know...
