### ISSUE TITLE
Cache directory for DiscISAM cache storage cannot be set

### ISSUE THREAD

**Issue by AndreKR** [PHPOffice/PHPExcel#67]
In https://github.com/PHPOffice/PHPExcel/blob/develop/Classes/PHPExcel/CachedObjectStorageFactory.php#L103-104 the `dir`parameter of the DiscISAM method is set to `NULL`. 

In https://github.com/PHPOffice/PHPExcel/blob/develop/Classes/PHPExcel/CachedObjectStorageFactory.php#L199-204 only parameters for which `isset()` is true are set. `isset(NULL)`is false, so the `dir` parameter can never be set.

**Comment by dalecosp** [comment]
Thanks Andre and Mark!  Was definitely causing an issue in some backend production systems here at OMBE.
