### ISSUE TITLE
Formula only works sometimes

### ISSUE THREAD

**Issue by bnelson01** [PHPOffice/PHPExcel#681]
I have a formula as follows:

=IF((OR(E2="",D2="")),0,IF((E2<D2),((E2-D2)*24)+24,(E2-D2)*24))

Am using it to figure out elapsed time. Here is the problem:

First row: D1 = 8:00 PM, E1 = 3:00 AM
Second row: D2 = 10:00 PM, E2 = 3:00 AM

The result for F1 = 7, which is correct however the result for F2 = -19, which is not correct it should be 5.

**Comment by MarkBaker** [comment]
If you are having problems with formulae, then PHPExcel allows you to do some debugging to see exactly how the engine is evaluating your formula - you can read about it [here](https://gist.github.com/MarkBaker/5908357)

**Comment by MarkBaker** [comment]
But this doesn't look like a valid formula:

```
=IF((OR(E2="",D2="")),0,IF((E2<D2),((E2-D2)24)+24,(E2-D2)24))
```

What is `(E2-D2)24` supposed to do?
