### ISSUE TITLE
PHPExcel not working with PHP 7.0

### ISSUE THREAD

**Issue by Ajtak** [PHPOffice/PHPExcel#716]
Hi.
Is possible fix PHPExcel for working with PHP 7.0?

In actual version is error:

    Fatal error: 'break' not in the 'loop' or 'switch' context in <mypath>\PHPExcel\PHPExcel\Calculation\Functions.php on line 581

Please fix this. Thank you.

**Comment by MarkBaker** [comment]
It will be fixed before the release of PHP7

**Comment by niklas-heer** [comment]
Since PHP7 is officially released now and out of interest - does it now work?

**Comment by MarkBaker** [comment]
I've been running tests against the develop branch, and the only things not working are those related to external libraries (jpgraph and various pdf rendering libraries), although phan is still picking up a few warnings about syntax that won't break anything, but still need cleaning up.

**Comment by iainfogg** [comment]
Hi @MarkBaker - just wondered if there are any more timescales for a release containing the PHP7 work that you've done?

**Comment by iainfogg** [comment]
Hi @MarkBaker - are you able to give any update on this please?

It'd be helpful to know if the PHP7 changes have made their way into the 1.8 branch, and also whether you feel it's all there now.

**Comment by tomzx** [comment]
I've been using 1.8.1 with PHP7 without any issues so far. I'm not using jpgraph nor any pdf rendering libraries though.

If you want more specific details about PHP7, I think it would be great to specify which features of PHPExcel you're making use of.

**Comment by Kelvinco** [comment]
Just delete the break on line 581, it has worked for me.

**Comment by iainfogg** [comment]
Thanks @tomzx and @Kelvinco 

In truth, the application is huge, and has a lot of usages of PHPExcel which, in truth, I'm not familiar with.

I appreciate the tweak suggested and your feedback about what you've used successfully, I was just hoping that @MarkBaker or someone could provide an update as to the developers' view of whether it's now compatible, and ideally sorted that line deletion that @Kelvinco suggested rather than me doing my own hacks.

Otherwise, I have to do loads of digging myself into an application which is big and not that pretty!

**Comment by iainfogg** [comment]
PS the application I was referring to is ours, the one that uses PHPExcel - not slating PHPExcel!

**Comment by naturekzw** [comment]
where is the phpexcell 1.8.1? @tomzx

**Comment by MarkBaker** [comment]
@naturekzw - under the tagged releases - [PHPExcel 1.8.1](https://github.com/PHPOffice/PHPExcel/tree/1.8.1)

**Comment by NazarenoMarzetti** [comment]
Hi.

I've a problem with the command
$objWriter->save('php://output');

not working in php7.

The same code workin in php5.5 but when i changed the version, the program die at this row.

Thanx.

Nazareno

**Comment by efantinij** [comment]
Hi NazarenoMarzetti,

on Line 581 of file PHPExcel/Classes/PHPExcel/Calculation/Functions.php there is a " break" , simply comment.

**Comment by PowerKiKi** [comment]
This is solved in latest version of PHPExcel, 1.8.1.

**Comment by apurv195** [comment]
Just **comment** the "break;" statement in functions.php file on Line No 581.

**Comment by xuxiaowenstyle** [comment]
not working with PHP 7.0.22 too,please tell me why?

**Comment by Toooooony** [comment]
@xuxiaowenstyle, I have no idea why. But a workaround is to go back to PHPExcel 1.8.0 and apply the manual fix on Functions.php.

**Comment by naturekzw** [comment]
@Toooooony PHPExcel 1.8.0 word well in PHP 7.1.9 at my project

**Comment by Toooooony** [comment]
@naturekzw Thanks, will keep it in mind. for now I have a site on AWS and some people has reported issues after updating to PHP7.1.x. So whatever works :)

**Comment by PowerKiKi** [comment]
It **is** broken on PHP 7.1, and was only fixed in https://github.com/PHPOffice/PhpSpreadsheet/commit/5df662e1a36d6363cc63e7d83cc48610769de792, not in PHPExcel.

**Comment by sideshowtoma** [comment]
okay guys i found a fix its dirty but it works,
go to Classes/PHPExcel/Writer/Excel2007.php

comment out the following lines, php 7 has a wierd return date type so doing this will enable php excel to work in php 7 pronto. any way

 $saveDateReturnType = PHPExcel_Calculation_Functions::getReturnDateType();
PHPExcel_Calculation_Functions::setReturnDateType(PHPExcel_Calculation_Functions::RETURNDATE_EXCEL);
PHPExcel_Calculation_Functions::setReturnDateType($saveDateReturnType);

to 

 //$saveDateReturnType = PHPExcel_Calculation_Functions::getReturnDateType();
//PHPExcel_Calculation_Functions::setReturnDateType(PHPExcel_Calculation_Functions::RETURNDATE_EXCEL);
//PHPExcel_Calculation_Functions::setReturnDateType($saveDateReturnType);

worked for me.

**Comment by orcinus** [comment]
**PHP Excel 1.8.1**
`Classes/PHPExcel/Worksheet/AutoFilter/Column.php`
Lines 384 and 386

`$this->$key[$k]`
should be replaced with
`$this->{$key[$k]}`

to ensure backwards and forwards compatibility (5.x vs. 7.0).
See http://php.net/manual/en/migration70.incompatible.php, **Changes to the handling of indirect variables, properties, and methods**

**Comment by orcinus** [comment]
**PHP Excel 1.8.1**
`Classes/PHPExcel/Writer/HTML.php`
Line 1453

`list($cells, )`
should be replaced with
`list($cells, $dummy)`

to ensure backwards and forwards compatibility (5.x vs. 7.0).
See http://php.net/manual/en/migration70.incompatible.php, **Changes to list() handling**

**Comment by orcinus** [comment]
**PHP Excel 1.8.1**
`Classes/PHPExcel/Reader/Gnumeric.php`
Line 310

`list(,$attrName)`
should be replaced with
`list($dummy, $attrName)`

to ensure backwards and forwards compatibility (5.x vs. 7.0).
See http://php.net/manual/en/migration70.incompatible.php, **Changes to list() handling**

**Comment by orcinus** [comment]
**PHP Excel 1.8.1**
`Classes/PHPExcel/Shared/OLE.php`
Lines 230, 242, 254

`list(, $tmp)`
should be replaced with
`list($dummy, $tmp)`

Line 517
`list(, $high_part)`
should be replaced with
`list($dummy, $high_part)`

Line 518
`list(, $low_part)`
should be replaced with
`list($dummy, $low_part)`

to ensure backwards and forwards compatibility (5.x vs. 7.0).
See http://php.net/manual/en/migration70.incompatible.php, **Changes to list() handling**

**Comment by UBEX** [comment]
Thats right! how we can resolve it? Finally i Think we shoud find an alternative to PHPExcel. Something declared full 100% compatible with PHP 7.0 or heighter (even better).

Any Idea?

**Comment by PowerKiKi** [comment]
@UBEX you are looking for https://github.com/PHPOffice/PhpSpreadsheet

**Comment by UBEX** [comment]
@PowerKiKi Thanks. It is better in performance?

**Comment by PowerKiKi** [comment]
It is next version of PHPExcel, so don't expect huge changes, but PHP 7 should give you a nice boost anyway.

**Comment by crscaballero** [comment]
I had the same problem, and i downloaded de 1.8.1 version, i chanched the header, and it's work!

    $objWriter = new PHPExcel_Writer_Excel2007($excel);
    header('Content-Type: application/vnd.openxmlformats-officedocument.spreadsheetml.sheet');
    header("Content-Disposition: attachment;filename=report.xlsx");
    header('Cache-Control: max-age=0');
    $objWriter->save('php://output');

**Comment by sharadinfo** [comment]
hello guys.. i have php ci application. there import functionality. its work on local but not work on live.
 php v7.1.9

**Comment by ngogiang270593** [comment]
update PHPExcel :  https://github.com/PHPOffice/PHPExcel.
Its Good.

**Comment by siQuang** [comment]
I just upgrade to PHP 7.1 and ran into this issue. Fix with installing zip.so, on centos 7 install "php-pecl-zip" extension and everything works for me. I'm on CentOS 7.5, PHP 7.1 with PHPExcel 1.8.1.

**Comment by PowerKiKi** [comment]
PHPExcel **is broken** on PHP 7.1 and will **never be fixed**.

If you want to use PHP 7.1, you must migrate to PhpSpreadsheet or another project.

I am locking this thread to prevent users from giving incorrect/incomplete advice about PHP 7.1.
