### ISSUE TITLE
Call to undefined method PHPExcel_Writer_Excel2007_Rels::_writeRelationShip()

### ISSUE THREAD

**Issue by jangxx** [PHPOffice/PHPExcel#726]
Happens when I try to write a *.xlsm file. The full message is:

    Fatal error:  Call to undefined method PHPExcel_Writer_Excel2007_Rels::_writeRelationShip() in
    <directory>/PHPExcel/Writer/Excel2007/Rels.php on line 165

**Comment by Gemorroj** [comment]
#709
