### ISSUE TITLE
make a copy of a sheet 

### ISSUE THREAD

**Issue by titom59280** [PHPOffice/PHPExcel#737]
Hello,

I have a excel template file with two sheets inside let say (Sheet 1 and Sheet 2) and I wanted to know if it is possible to create a Sheet 3 with the same content of Sheet 2).

I it is how can I do that?

Thanks for your reply

**Comment by MarkBaker** [comment]
Create a copy of the worksheet you want using either the worksheet's `copy()` method (for a shallow clone), or a PHP clone (which creates a deep clone) and then use the PHPExcel object's `addSheet()` method

**Comment by titom59280** [comment]
is it a new \PHPExcel_Worsheet with the activeSheet in paramater that I need to do

**Comment by titom59280** [comment]
Never mind I figured it out.

Thanks for your time
