### ISSUE TITLE
Retrieving version number?

### ISSUE THREAD

**Issue by infojunkie** [PHPOffice/PHPExcel#74]
Is there a way to programmatically retrieve the version number of the library? This would be useful to maintain backward compatibility.

**Comment by fengkaijia** [comment]
1.8.1 downloaded from Github is unversioned. But PHPExcel on Codeplex is still 1.8.0. So anywhere to download a versioned 1.8.1?

**Comment by MarkBaker** [comment]
I really am trying to kill off the codeplex site.

The 1.8.1 download from here is tagged, and directly accessible to pull with the tag, or to install via composer
