### ISSUE TITLE
How do we load a file with a remote database?

### ISSUE THREAD

**Issue by christianbundy** [PHPOffice/PHPExcel#743]
Our database is on a remote server, when `$objReader->load($inputFileName);` executes SQL like `COPY "filename" FROM '/path/to/filename.csv' WITH DELIMITER ',' CSV HEADER encoding 'windows-1251';` it ends up throwing errors, seeing as how the database doesn't have access to the file.

What's the recommended workaround for those who aren't hosting their application and database on a shared filesystem? Thanks!

**Comment by MarkBaker** [comment]
Recommendation is to write a script that uses PHP's fgetcsv() function to read each row from the file and use your PHP SQL driver to insert that record into the database..... not really a PHPExcel question at all

**Comment by christianbundy** [comment]
Just to be clear, this is the code we're running:

``` php
PHPExcel_Cell::setValueBinder( new OurLeadingZeroValueBinder() );
$objReader = PHPExcel_IOFactory::createReader('CSV')->setDelimiter(',')
  ->setEnclosure('"')
  ->setLineEnding("\r\n")
  ->setSheetIndex(0);
$objReader->setReadDataOnly(true);
$readFilter = new csvPreviewReadFilter();
$objReader->setReadFilter($readFilter);
$objPHPExcelFromCSV = $objReader->load($this->getFullUploadFilePath());
$objWorksheet = $objPHPExcelFromCSV->getActiveSheet();
```

We're using XLXS for some files and CSV for others, so it would be great to be able to use the same library instead of using a similar workflow for both file types.

**Comment by MarkBaker** [comment]
Well logically you'd just iterate over the rows from the $objWorksheet object (see `Examples/28iterators.php`) for an example, and then use your database interface to insert the values from that row into your database

**Comment by christianbundy** [comment]
Sorry, this is all me. I misread our code and thought our database bug was being thrown from PHPExcel code. Nope.

Thanks for putting up with me, cheers!
