### ISSUE TITLE
Excel2007 does not honor new lines in cells

### ISSUE THREAD

**Issue by Tulvan** [PHPOffice/PHPExcel#744]
We are using v 1.8.0 and creating Excel2007 xlsx files. Any cell with multiple lines has issues. In Microsoft Office Excel Starter 14.0.7128.5000, the cell contents shows up on one line. If I edit the cell (click into it) and then end editing (click out), the content wraps correctly. The same file opened with OpenOffice 4.0.1 Calc shows the contents on multiple lines correctly, but duplicates the contents multiple times. I am unable to determine what controls how many times the content is duplicated. I opened the sharedStrings.xml and sheet1.xml and they seem to indicate the correct strings are being placed in the correct locations. To make this more confusing, if the file is < 15 rows, the duplication does not happen. 

I've attached basic examples. The NoDuplication.xlsx is the max lines (15) of data that can be included before cells start getting duplicated in OpenOffice. Duplication.xlsx shows adding one more row causes the duplication. MoreDuplication.xlsx shows if you continue to add more lines, the same cells get duplicated repeatedly. Lastly, CreateExcel2007.php is as basic a PHP file as I could make it and reproduce the problem.

(I had to change all extensions to txt to get them to upload)
[Duplication.txt](https://github.com/PHPOffice/PHPExcel/files/39208/Duplication.txt)
[MoreDuplication.txt](https://github.com/PHPOffice/PHPExcel/files/39209/MoreDuplication.txt)
[NoDuplication.txt](https://github.com/PHPOffice/PHPExcel/files/39210/NoDuplication.txt)
[CreateExcel2007.txt](https://github.com/PHPOffice/PHPExcel/files/620186/CreateExcel2007.txt)

**Comment by MarkBaker** [comment]
I don't see anywhere that you're setting the cell alignment to wrap in that code..... this has to be set explicitly, it is not the default style

```php
$objPHPExcel->getActiveSheet()->getStyle('A10')->getAlignment()->setWrapText(true);
```

**Comment by Tulvan** [comment]
I apologize Mark. In my zealous trimming, I removed that for the demonstration. It IS in my code and the example I created still has the same issue when I add it in there.

**Comment by Tulvan** [comment]
I know its been forever, but I wanted to see if there has been a solution to this problem. We have since updated to PHPExcel 1.8.1 and the problem still exists. I updated my original post attachments with Mark's comment to reflect the actual code I'm running and still seeing the problem.

**Comment by PowerKiKi** [comment]
The file generated by CreateExcel2007.txt shows correctly in Excel 2016. Is this not what you expected ?

![image](https://cloud.githubusercontent.com/assets/72603/20736885/c99bdb24-b6ec-11e6-8002-df3096dd5598.png)

(it will show incorrectly in LibreOffice 5 though, but I believe it is a known issue from LibreOffice)

**Comment by Tulvan** [comment]
I didn't find the bug you refer to, but you are correct. In the current version of Microsoft Office (Mac and PC), it does open correctly. That's good enough for my purposes. Thanks.
