### ISSUE TITLE
PHPExcel_Calculation globally set precission

### ISSUE THREAD

**Issue by EugeniyPetrov** [PHPOffice/PHPExcel#753]
Hello,

When using PHPExcel I've got very strange behaviour when working with floats.

```php
require_once 'vendor/autoload.php';
var_dump(802.94); // double(802.94)
new PHPExcel();
var_dump(802.94); // double(802.9400000000001)
var_dump(round(802.94, 2)); // double(802.9400000000001)
```

The reason is because of the following code in PHPExcel_Calculation::__construct
```php
$setPrecision = (PHP_INT_SIZE == 4) ? 14 : 16;
$this->_savedPrecision = ini_get('precision');
if ($this->_savedPrecision < $setPrecision) {
    ini_set('precision',$setPrecision);
}
```

What's the reason to set it globally? Can we avoid this, because it causes a hard to fix problems outside of library.

**Comment by MarkBaker** [comment]
The reason was that failing to do so returned too many invalid results for too many functions with older versions of PHP. It has now been removed in the latest develop branch because I'm fed up with people complaining all the time

**Comment by kantsverma** [comment]
I am getting the same issues Error: Class 'PHPExcel_Calculation' not found. Firstly i was getting error of failed to open stream: No such file or directory [ROOT/vendor/PHPExcel/PHPExcel.php, line 5] i just comment it and then get this issues. Can we define it in the same class ?
