### ISSUE TITLE
Read XLSB format file

### ISSUE THREAD

**Issue by Vlad-73** [PHPOffice/PHPExcel#773]
Please tell when Phpexcel read files format xlsb?
This format to become popular

**Comment by bangdingow** [comment]
+1 clients are sending XLSB files and it would be nice to be able to work with them in PHPExcel

**Comment by PowerKiKi** [comment]
This is very unlikely to happen in the foreseeable future unless somebody from the community step up and provides an implementation. And if somebody actually want to do that, it should be done in PhpSpreadsheet.
