### ISSUE TITLE
Can't install a PDF Writer

### ISSUE THREAD

**Issue by paedae93** [PHPOffice/PHPExcel#789]
Hi
it try to use your PHPExcel and it works good. But I don't really understand, how to use these external PDF libraries. I read your documentation and was searching in internet but nothing worked. So the situation:
I work on a Apache Server on Windows. I have my project on the top folder. Everything works but not PDF creation.
![folder_structure](https://cloud.githubusercontent.com/assets/5691568/12297617/4c71340e-ba0e-11e5-852d-d3a472f39c5c.PNG)

Now, so i understand, your example 21pdf.php should work without any changes, because the folder structure is the same!
![code](https://cloud.githubusercontent.com/assets/5691568/12297688/8e4f1396-ba0e-11e5-87fb-f8f7fe7bdc71.PNG)

What else i should change? Thanks for your support.

**Comment by paedae93** [comment]
Sorry I found the solution.

**Comment by tuanth89** [comment]
@paedae93 
How to resolve this solution ??

**Comment by paedae93** [comment]
The problem was that I used the wrong folder structure. The structure has to be like in the documentation. You can send me a Screenshot of your folderstructure than I could help you.
