### ISSUE TITLE
excel5 only to column IV

### ISSUE THREAD

**Issue by Golovior** [PHPOffice/PHPExcel#792]
Creating excel files in excel5 format only gives columns to IV. I would like to create column beyond that.  
This is a record in the changelog on 2011-02-27 (v1.7.6).  
Is there a way I can change this value to more columns?

**Comment by MarkBaker** [comment]
Then I'm afraid you'll have to have a word with Microsoft and get them to change it.... because I'm afraid that it's MS Excel itself that imposes this limit for BIFF-format xls files.... Once you've persuaded Microsoft to make that change, then I'll modify PHPExcel to work with it

**Comment by Golovior** [comment]
Ahh.. In that case it will probably be best to use the Excel2007 option.  
Now gonna try to make that work. Changing Excel5 to Excel2007 and changing the header element gives an error of "file format or file extension not valid".  
  
Thank you.

**Comment by Golovior** [comment]
Found the reason for this (not working of excel2007). XMLWriter isn't installed on this CentOS server.
