### ISSUE TITLE
After using insertNewColumnBefore whole excel file content is deleted 

### ISSUE THREAD

**Issue by anushkamahesh** [PHPOffice/PHPExcel#798]
Hi,

I am using PHPExcel 1.8.0 and I faced a big issue. I used 
``` php
$objReader = PHPExcel_IOFactory::createReader('Excel5');
$objPHPExcel = $objReader->load("tempalate.xls");
$objPHPExcel->getActiveSheet()->insertNewColumnBefore('AD', 1);
```
whole excel file content is deleted and saved as empty excel file. Am I doing it wrong or Is it a issue?

**Comment by MarkBaker** [comment]
Please provide actual code that demonstrates this problem, because I am unable to replicate

**Comment by anushkamahesh** [comment]
I have done this. 
```
$objReader = PHPExcel_IOFactory::createReader('Excel5');
$objPHPExcel = $objReader->load("tempalate.xls");
$objPHPExcel->getActiveSheet()->insertNewColumnBefore('AD', 1);
$objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel5');
$objWriter->save(str_replace('.php', '.xls', __FILE__));
```
I can't attach the file, it is not supported by github Sorry 
![screenshot from 2016-01-26 22 59 03](https://cloud.githubusercontent.com/assets/1327120/12588811/7162fad2-c480-11e5-9f21-64b8ed29ec6c.png)

Template look like above

**Comment by MarkBaker** [comment]
Do some basic diagnostics, check that the template file is loading correctly, check whether a cell like Z4 is populated with any value

**Comment by anushkamahesh** [comment]
Issue with excel file
