### ISSUE TITLE
"Sheet index is out of bounds." Exception

### ISSUE THREAD

**Issue by dbonsch** [PHPOffice/PHPExcel#80]
Especially if you have more than one sheet this error message does not really help to much. 

Please add the requested $pIndex and the actual amount of sheets to the error message. That would help to find errors faster.

**Comment by huanggaoyuan2016** [comment]
Completely ignorant than

**Comment by huanggaoyuan2016** [comment]
Completely ignorant than

**Comment by iamMarkchu** [comment]
i use 1.7.4 version ,   the only way to solve 'Sheet index is out of bounds' this problem is to updated phpexcel?

**Comment by PowerKiKi** [comment]
1.7.4 was released on the 2010-08-26, almost 7 years ago. You should absolutely upgrade.
