### ISSUE TITLE
 PHPExcel version    1.7.8 on PHP 5.6

### ISSUE THREAD

**Issue by chandrakanthi07** [PHPOffice/PHPExcel#803]
We are Using PHPExcel version    1.7.8 on PHP 5.6
Will this not work on PHP 5.6?
Because the generated excel file does not open in LibreOffice.
The error received is "Version  Incompatibility. Incorrect file version."
Please let me know how this can be resolved

**Comment by MarkBaker** [comment]
We don't support older versions of PHPExcel
