### ISSUE TITLE
CSV being interpreted as HTML?

### ISSUE THREAD

**Issue by rohan-deshpande** [PHPOffice/PHPExcel#806]
So I am passing a CSV file to get identified by 

`PHPExcel_IOFactory::identify()`

The file array looks like this

```
Array
(
    [name] => myfile.csv
    [type] => application/vnd.ms-excel
    [tmp_name] => /tmp/phpTn6yNM
    [error] => 0
    [size] => 267726
)
```

The result of the `identify` method is `HTML`. Is this behaving as intended?

**Comment by MarkBaker** [comment]
Without knowing what your CSV file contains, how can I guess what PHPExcel thinks of it. Look at your file, look at the PHPExcel code, work out why PHPExcel thinks it might be an HTML file..... unless I can see your csv file, I can't do that for you

**Comment by rohan-deshpande** [comment]
There's no valid HTML markup in the csv at all. Some stuff is in there that is in a tag like format, but it isn't valid HTML. The tags look like `<MTH>stuff</MTH>` for example. 

Nuovo Reader reads it just fine, PHPExcel doesn't, because Nuovo does a file extension check as well as a file type check. I would prefer to use one library though.

**Comment by MarkBaker** [comment]
OK, so the PHP checker for HTML is ___too___ simple because it's based on ___anything that looks like markup___ (e.g. tags) being accepted as HTML markup..... so I'm open to suggestions on how to improve that for the rare case of a csv file that contains markup of some description

**Comment by rohan-deshpande** [comment]
But if you check the file type AND the extension have you not got basically two step verification that the file is a CSV?

**Comment by Calorus** [comment]
Would it not be best to use the extension as the type, then check the markup to validate it?
People understand file extensions, and importantly, if you had a text file with an .xls extension, it would be invalid anyway?

**Comment by MarkBaker** [comment]
For precisely the reasons I've specified, namely misnamed files which are very common, No..... look at the identify() code..... it actually checks the extension to use for its initial "check", but only if the extension isn't csv..... I'lll take a look at changing this, but not while I'm in the work that actually gives me an income

**Comment by Quix0r** [comment]
createReaderForFile() uses pathinfo() and then 'extension' from the resulting array. That should work (maybe worth to rewrite to OOP-ed way with SplFileInfo class but not needed so much).

Maybe you can move that pathinfo() stuff in another (public?) method to get a more encapsulated code? Just an idea as I would do it.

**Comment by kamazee** [comment]
I tried a naive approach that barely changes anything but addresses my specific issue: https://github.com/PHPOffice/PhpSpreadsheet/pull/34

I'll be glad to hear some feedback and backport it into this project it it's OK.

**Comment by PowerKiKi** [comment]
@kamazee thanks for your work. Don't need to backport anything, because PHPExcel will not be updated anymore.
