### ISSUE TITLE
MemoryDrawing not working in HTML writer

### ISSUE THREAD

**Issue by Tomino2112** [PHPOffice/PHPExcel#808]
Hi,

I am processing base64 image strings into Excel and HTML outputs. 

This is the code: 

```
$data = base64_decode(explode(',', $b64data)[1]);                   
                    $objDrawing = new PHPExcel_Worksheet_MemoryDrawing();
                    $objDrawing->setName('Sample image');
                    $objDrawing->setDescription('Sample image');
                    $objDrawing->setImageResource(imagecreatefromstring($data));
                    $objDrawing->setRenderingFunction(PHPExcel_Worksheet_MemoryDrawing::RENDERING_JPEG);
                    $objDrawing->setMimeType(PHPExcel_Worksheet_MemoryDrawing::MIMETYPE_DEFAULT);
                    $objDrawing->setWidth(200);
                    $objDrawing->setHeight(200);
                    $objDrawing->setCoordinates($coord);
                    $objDrawing->setWorksheet($excelOb->getActiveSheet());
```

If I use Excel writer, image displays fine, but if I use HTML writer the image just doesnt bet processed. I had a little dig around the code, and found:

`HTML.php:575`

`if ($drawing instanceof PHPExcel_Worksheet_Drawing) {`

So obviously it seems that HTML writer ignores MemoryDrawings.

Is that correct? I could create pull request with fix when I have time, just want to make sure

Thanks

**Comment by Tomino2112** [comment]
Created pull request #839

**Comment by MarkBaker** [comment]
Merged manually, thank you for the PR
