### ISSUE TITLE
Uninitialized string offset

### ISSUE THREAD

**Issue by titansupport** [PHPOffice/PHPExcel#811]
Hi,

As a start thanks for your fantastic code, saved us a lot of hassle countless times.

I am receiving the following error when reading a simple excel file (just 4 cells with text values no equations no formatting) : 
PHP Notice:  Uninitialized string offset: 134217730 in Classes/PHPExcel/Shared/OLERead.php on line 316 

Attached is 2 copies of the file we are reading, one is corrupted and causes a hard crash as it goes in an infinite loop with the above error, while the other is how the file was before getting corrupted.

We are still investigating why it got corrupted, but would like to know if there is a way PHPExcel can identify this as a corrupted file, because currently it passes all the validation checks within PHPExcel

[Files.zip](https://github.com/PHPOffice/PHPExcel/files/118992/Files.zip)

**Comment by brad13x** [comment]
I have this same error but the file is not corrupted as far as I know. It does have 30k+ rows.

**Comment by titansupport** [comment]
@MarkBaker would it be possible to get your opinion on the above?

**Comment by titansupport** [comment]
No response received for more than 2 months, closing and opening a new issue

**Comment by TheRinseM** [comment]
Is someone still having this issue?

**Comment by brad13x** [comment]
Yes

**Comment by TheRinseM** [comment]
@brad13x  I managed to fix it.

I removed the "=" strings from the .csv file, and then, it parsed.

**Comment by ilyago** [comment]
Notice: Uninitialized string offset: -1298297751 in /Classes/PHPExcel/Reader/Excel5.php on line 7562
Notice: Uninitialized string offset: -1298297750 in /Classes/PHPExcel/Reader/Excel5.php on line 7562
Notice: Uninitialized string offset: -1298297753 in /Classes/PHPExcel/Reader/Excel5.php on line 7562
Notice: Uninitialized string offset: -1298297752 in /Classes/PHPExcel/Reader/Excel5.php on line 7562
Loops......

**Comment by TheRinseM** [comment]
@ilyago  Do you have "=" signs in your CSV?

**Comment by ilyago** [comment]
@TheRinseM Its large trx report. No "=" sign.
