### ISSUE TITLE
Missing/Broken Code

### ISSUE THREAD

**Issue by aqeel-legalinc** [PHPOffice/PHPExcel#849]
Hi, I just found that in your master Branch there is a missing/Broken Code issue on 
https://github.com/PHPOffice/PHPExcel/blob/1.8/Classes/PHPExcel/Shared/Date.php#L191

Please have a look on this, and replace 

$retValue = self::stringToExcel($dateValue)
To 
$retValue = self::stringToExcel($dateValue);
}

Thanks!

**Comment by MarkBaker** [comment]
Apologies, fixed

**Comment by aqeel-legalinc** [comment]
Oh No problem, I just wanted to get your attention on this. Thanks a lot.
