### ISSUE TITLE
ZipClass PCLZIP - Fatal error: Uncaught Error: Class 'ZIPARCHIVE' not found in PHPExcel/Reader/Excel2007.php:314

### ISSUE THREAD

**Issue by marcoflorian** [PHPOffice/PHPExcel#852]
Set the ZipClass to PCLZIP.

`PHPExcel_Settings::setZipClass(PHPExcel_Settings::PCLZIP);`

Try to read an Excel file.

`$php_excel = PHPExcel_IOFactory::load($excel_file);`

Fatal error.

`Fatal error: Uncaught Error: Class 'ZIPARCHIVE' not found in PHPExcel/Reader/Excel2007.php:314`

[At line 315 in Reader/Excel2007.php](https://github.com/PHPOffice/PHPExcel/blob/1.8/Classes/PHPExcel/Reader/Excel2007.php#L315) I did a change.

```
// Apache POI fixes
$zipClass = PHPExcel_Settings::getZipClass();
if ($zipClass == 'ZipArchive') {
    $contents = $archive->getFromIndex(
        $archive->locateName($fileName, ZIPARCHIVE::FL_NOCASE)
    );
    if ($contents === false) {
        $contents = $archive->getFromIndex(
            $archive->locateName(substr($fileName, 1), ZIPARCHIVE::FL_NOCASE)
        );
    }
}
else {
    $contents = $archive->getFromIndex($archive->locateName($fileName));
}
```

It is now working fine. Did I fix it correctly?

**Comment by neuro-sys** [comment]
@marcoflorian Thanks, your fix has worked for me.

**Comment by marcoflorian** [comment]
https://github.com/PHPOffice/PHPExcel/pull/1097

**Comment by shaheenhashinclude** [comment]
I got an error
Message: Class 'ZipArchive' not found
Filename: Reader/Excel2007.php
Line Number: 86

Any help

**Comment by rcarvello** [comment]
Tnx..This worked form me. PHP 5.2

**Comment by rckjairath** [comment]
I am getting error in above code in $archive->getFromIndex
Undefined variable: archive in 
Call to a member function getFromIndex() on null in
