### ISSUE TITLE
Maximum function nesting level

### ISSUE THREAD

**Issue by ArtisanTinkerer** [PHPOffice/PHPExcel#855]
Hi,

Trying to import a spreadsheet and am getting this.

PHP Fatal error:  Maximum function nesting level of '256' reached, aborting! in /var/www/html/selection/vendor/phpoffice/phpexcel/Classes/PHPExcel/Calculation/Functions.php on line 663, referer: 

Any ideas?

**Comment by ArtisanTinkerer** [comment]
I only want a couple of columns from the first sheet, is there a way I can limit what I load?

Do I need to this:

Excel::load('file.xls', function($

});

before I can use;

$reader->first();

**Comment by MarkBaker** [comment]
You can limit the data that you import by using a read filter

**Comment by ArtisanTinkerer** [comment]
Ahhh.

Yes, sorry. I am using this:

https://github.com/Maatwebsite/Laravel-Excel

**Comment by ArtisanTinkerer** [comment]
I have this working now with your package! It is incredible, thank-you!
