### ISSUE TITLE
how to sort columns by header

### ISSUE THREAD

**Issue by adminmoodle** [PHPOffice/PHPExcel#864]
hi to every
i want to sort excel columns using phpexcel, any idea?

**Comment by MarkBaker** [comment]
This option is not available from within PHPExcel, because the overhead of sorting is excessively high

**Comment by adminmoodle** [comment]
:( what can i do?, i really need to do, any suggestion

**Comment by MarkBaker** [comment]
If you're building a spreadsheet, then you need to ensure that the data is sorted before you start building it (e.g. in a database query or similar). If you're reading a spreadsheet, then read it to an array or temporary database table, and sort it there.

**Comment by adminmoodle** [comment]
ok, its what i had planned to do, but first wanted to try with phpexcel 

thanks

**Comment by Hak4Kidz** [comment]
Hi Everyone,

Has there been an update to PHPExcel or PHPSpreadsheet that can handle reading a CSV, sorting the data, and writing it to a template XLSX file?

BTW, great work here at PHPOffice!

TIA!
Dave

**Comment by MarkBaker** [comment]
No! Sorting within PHPExcel is a big overhead, which is why it has never been implemented
