### ISSUE TITLE
Cell caching appears to be leaking to other cells?

### ISSUE THREAD

**Issue by KOGI** [PHPOffice/PHPExcel#865]
I'm not quite sure how to explain what's going on. In the below code, I'm saving references to cells for later use, and then fetching their calculated values, but they're not coming back correctly. I've distilled the code to the minimum to reproduce this error. Notice the final output with duplicated values in all cells with a formula.

The input file is a very simple xlsx file with the following contents:
![Input File](http://i.imgur.com/btlDchX.png)

However, the output has duplicated, cached values:

```js
{
	"direct": {
		"one": 1,
		"two": 2,
		"three": 3,
		"four": 4,
		"five": 5,
		"six": 6
	},
	"referenced": {
		"one": 1,
		"two": 2,
		"three": 3, // <--- duplicated
		"four": 3,  // <--- duplicated
		"five": 3,  // <--- duplicated
		"six": 6
	}
}
```

And the code:

```php
<?php

require_once( './vendor/autoload.php' );

$aliases = [
	'one'   => 'A1',
	'two'   => 'A2',
	'three' => 'A3',
	'four'  => 'A4',
	'five'  => 'A5',
	'six'   => 'A6'
];

// ======== Load File
$inputFileName = './test.xlsx';
$inputFileType = PHPExcel_IOFactory::identify( $inputFileName );

$objReader = PHPExcel_IOFactory::createReader( $inputFileType );
$objReader->setReadDataOnly( true );

$objPHPExcel = $objReader->load( $inputFileName );
PHPExcel_Calculation::getInstance( $objPHPExcel )->setCalculationCacheEnabled( true );
$worksheet = $objPHPExcel->getActiveSheet();

// ======== Inspect Cell Values

// ======== Direct Access
$direct = [];
foreach( $aliases as $name => $address ) {
	$direct[$name] = $worksheet->getCell( $address )->getCalculatedValue();
}

// ======== Referenced Access
// -------- resolve aliases to actual cells
$cells = [];
foreach( $aliases as $name => $address ) {
	$cells[$name] = $worksheet->getCell( $address );
}

// PHPExcel_Calculation::getInstance( $objPHPExcel )->clearCalculationCache();
$referenced = [];
foreach( $cells as $name => $cell ) {
	// PHPExcel_Calculation::getInstance( $objPHPExcel )->clearCalculationCache();
	$referenced[$name] = $cell->getCalculatedValue();
}

header( 'Content-Type: application/json' );
echo json_encode( compact( 'direct', 'referenced' ));
```

**NOTE:** Uncommenting line 40 (`clearCalculationCache()`) will *not* resolve this problem, but uncommenting line 43 *will*.

**This is using PHPExcel v1.8.1 installed via Composer (phpoffice/phpexcel).**

**Comment by MarkBaker** [comment]
That's how cell caching works, only a single cell is "active" in memory at any one time.... if you reference that, and then change the active cell, you'll be pointing to the current "active" cell, which will be the last cell that you accessed..... don't use references to cells
