### ISSUE TITLE
getHighestDataRow incorrect return value for columns with drop-down list and no data

### ISSUE THREAD

**Issue by PowerGamer1** [PHPOffice/PHPExcel#874]
Example: define a drop-down list (see https://support.office.com/en-us/article/Create-a-drop-down-list-7693307a-59ef-400a-b769-c5402dce407b) for cells A1:A10. Enter data only into cell A3 leaving all other cells empty. Calling `getHighestDataRow` for column A will incorrectly return 10 instead of 3.

**Comment by MarkBaker** [comment]
If cell A10 contains a dropdown list, then this is cell content, whether you have actively selected an entry from that list or not; therefore row 10 is the highest data row because row 10 contains a dropdown

**Comment by PowerGamer1** [comment]
In my opinion `getHighestDataRow` should check for an actual "data" in the cell, not a "non-data content", because there is already a `getHighestColumn` method to check for "non-data content".

**Comment by MarkBaker** [comment]
The problem then is we end up with several more getHighest* methods, all reporting different things, and having to work in different ways.... having two methods already feels bad enough, and there's enough confusion about them.... and there's a big difference between getHighestColumn() (calculated purely during the file load) and getHighestDataColumn() (calculated when called based on the actual cell list).... but your request would not only require testing whether a cell existed, but also testing the value of that cell, an even bigger overhead

**Comment by PowerGamer1** [comment]
```PHP
    /**
     * Get highest worksheet row
     *
     * @param   string     $column     Return the highest data row for the specified column,
     *                                     or the highest row of any column if no column letter is passed
     * @return int Highest row number
     */
    public function getHighestRow($column = null)

    /**
     * Get highest worksheet row that contains data
     *
     * @param   string     $column     Return the highest data row for the specified column,
     *                                     or the highest data row of any column if no column letter is passed
     * @return string Highest row number that contains data
     */
    public function getHighestDataRow($column = null)
```


Nothing in the naming and description (PHPDoc comment) of  `getHighestRow` and `getHighestDataRow` suggests there is a difference based on when it is calculated (during file load or not - why would there be any difference like that anyway?). But instead the current method naming and description suggests that the difference between two methods is in what they check - for any (non-data) content of cell or for actual data within a cell.

So no wonder there is a confusion - which is yet another reason to do something about it. For example, change the methods to behave as named and described.

**Comment by MarkBaker** [comment]
So perhaps I should write and document 20 different versions:

 - getHighestRowAsReadFromFileThatIsReferencedByAnything() 
 - getHighestRowWhereACellActuallyExists()
 - getHighestRowWhereCellExistsAndIsNonBlank()

etc
You say "do something about it".... do what? Change the methods to work differently (and break backward compatibility), change them to work how? As you want them to work?

The difference is historic..... getHighestRow() has always existed, and always worked from loading the file; it never changed whatever was done to the data, so adding or deleting rows left it unchanged. getHighestDataRow() was added much more recently, and works by testing whether there is an entry in the cell collection. As nulls or empty strings are still data, they will still be reported, because the a cell containing those values still exists.

**Comment by PowerGamer1** [comment]
Since you will not break backward compatibility this cannot be fixed nicely and the only thing that should be done - is properly document the methods in PHPDoc comments - mentioning there stuff like `AsReadFromFileThatIsReferencedByAnything` and `WhereACellActuallyExists`.

**Comment by derekrprice** [comment]
I understand what @MarkBaker is saying about backwards compatibility, but I have to agree with @PowerGamer1 (and a number of StackOverflow and other net users), that what `getHighestDataRow` actually does is practically useless.  I don't care if I've applied formatting to the row, I want an efficient way to grab the last one that contains non-blank data without calling getCell 1000 x 26 times myself.  I want the row that a user opening the spreadsheet and just visually looking at it would say is the last row.

Surely there is an efficient way to do this.  At load time, you must already know if each cell is blank or not, so increment a `MAXNONEMPTYROW` entry appropriately there.  Also easy to update when setting a cell's data.  When clearing cell data, it's a little trickier.  Perhaps set a `RECHECKMAXNONEMPTYROW` flag and lazily calculate a new value for `MAXNONEMPTYROW` when `RECHECKMAXNONEMPTYROW` is set and `getHighestNonEmptyRow` is called?  And similar for `getMaxNonEmptyColumn`, of course.

**Comment by derekrprice** [comment]
I copied my last comment to the more recent, still open issue #1302, which is basically about the same problem.
