### ISSUE TITLE
Bug in file PHPExcel/Reader/CSV.php

### ISSUE THREAD

**Issue by Verevival** [PHPOffice/PHPExcel#879]
This line redefines the delimiter and the file is not read correctly
    protected function checkSeparator()
    {
...
        $this->delimiter = substr($line, 4, 1);  // line 174
    }

**Comment by MarkBaker** [comment]
In what way does it misread it? What is the separator defined as in your file? What is it being set to?

**Comment by MarkBaker** [comment]
If a defined separator lie is

```
sep=;
01234
```

then 
```
$this->delimiter = substr($line, 4, 1);
```
should read 1 character from offset 4, which should be `;`

**Comment by Verevival** [comment]
Not defined separator in file :)
[46.zip](https://github.com/PHPOffice/PHPExcel/files/215536/46.zip)

**Comment by MarkBaker** [comment]
Then the problem isn't with the line that reads `$this->delimiter = substr($line, 4, 1);` but with any logic that allows it to drop through to that line if no `sep=x` line exists in the file

**Comment by Verevival** [comment]
Perhaps more correctly be so?
    protected function checkSeparator()
    {
        $line = fgets($this->fileHandle);
        if ($line === false) {
            return;
        }
        if ((strlen(trim($line)) == 5) && (strpos(trim($line), 'sep=') === 0)) {
            $this->delimiter = substr($line, 4, 1);
        } else {
            return $this->skipBOM();
       }
    }
