### ISSUE TITLE
ExcelWriter not working on php7

### ISSUE THREAD

**Issue by zecho** [PHPOffice/PHPExcel#885]
Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalThrowableError: "Fatal error: Class 'ZipArchive' not found" at .../vendor/phpoffice/phpexcel/Classes/PHPExcel/Writer/Excel2007.php line 227 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Fatal error: Class 'ZipArchive' not found at .../vendor/phpoffice/phpexcel/Classes/PHPExcel/Writer/Excel2007.php:227)

Version tested on:
PHP 7.0.5-3

Same is working on PHP5.

**Comment by MarkBaker** [comment]
So which version of PHPExcel are you having this problem with? Because 227 is a blank line in the latest develop branch of the library

**Comment by MarkBaker** [comment]
And has your PHP7 been built without the zip library?

**Comment by zecho** [comment]
Sorry, my fault. The extension was installed only on php5. Close the issue. Thank you!
