### ISSUE TITLE
Undefined offset: -1 in Excel5.php:918

### ISSUE THREAD

**Issue by ivokund** [PHPOffice/PHPExcel#887]
When reading a seemingly normal xls file

Line 918 in `phpexcel181/Classes/PHPExcel/Reader/Excel5.php`

``` php
// get index to BSE entry (1-based)
$BSEindex = $spContainer->getOPT(0x0104);
$BSECollection = $escherWorkbook->getDggContainer()->getBstoreContainer()->getBSECollection();
$BSE = $BSECollection[$BSEindex - 1];
$blipType = $BSE->getBlipType();
```

Adding the following right before line 918 fixes this problem, although I'm not sure what else could break because of that, or what was the reason for this error. 

``` php
if (!isset($BSECollection[$BSEindex - 1])) {
    break;
}
```

**Comment by ivokund** [comment]
It seems that the error occurs if filter is applied to the worksheet.

**Comment by antoinedeschenes** [comment]
Same issue here: https://github.com/PHPOffice/PHPExcel/issues/464

$BSEindex can be 0, which can reference to $BSECollection[-1], which is invalid.

**Comment by dmelk** [comment]
Also sometimes BstoreContainer is null and getBSECollection() method produce fatal error. Another workaround is:

```
$BSEindex = $spContainer->getOPT(0x0104);
if ($escherWorkbook->getDggContainer()->getBstoreContainer() == null) {
    break;
}
$BSECollection = $escherWorkbook->getDggContainer()->getBstoreContainer()->getBSECollection();
$BSE = $BSECollection[$BSEindex - 1];
$blipType = $BSE->getBlipType();
```

**Comment by PowerKiKi** [comment]
Should be solved by https://github.com/PHPOffice/PhpSpreadsheet/commit/b964788d5c55f9c08a2320579d33a809bfa6c1f2
