### ISSUE TITLE
PHP7: ErrorException: Methods with the same name as their class will not be constructors in a future version of PHP; PclZip has a deprecated constructor

### ISSUE THREAD

**Issue by InstanceOfMichael** [PHPOffice/PHPExcel#890]
```
ErrorException: Methods with the same name as their class will not be constructors in a future version of PHP; PclZip has a deprecated constructor
1
File "/srv/www/client1/vendor/phpoffice/phpexcel/Classes/PHPExcel/Shared/PCLZip/pclzip.lib.php" line 190 in handleError
2
File "/srv/www/client1/vendor/phpoffice/phpexcel/Classes/PHPExcel/Shared/ZipArchive.php" line 31 in require_once
3
File "/srv/www/client1/vendor/phpoffice/phpexcel/Classes/PHPExcel/Shared/ZipArchive.php" line 31 in require
4
File "/srv/www/client1/vendor/phpoffice/phpexcel/Classes/PHPExcel/Autoloader.php" line 86 in Load
```

**Comment by MarkBaker** [comment]
Of course, pclzip.lib.php is an external library

**Comment by InstanceOfMichael** [comment]
Looks like its an internal library to me.

**Comment by MarkBaker** [comment]
It might look like an "internal" library, because we include it directly in the distribution; but it' actually [this library](https://github.com/ivanlanin/pclzip) which has finaly made its way onto github and packagist

**Comment by MarkBaker** [comment]
Of course, if your version of PHP is high enough, it isn't even needed because ZipArchive is built-in as standard by default

**Comment by InstanceOfMichael** [comment]
My issue was actually solved by something like ``sudo apt-get install zip`` if anyone else stumbles upon this. Thank you!

**Comment by eko3alpha** [comment]
I'm seeing this same issue.  I'm using composer and PHPOffice v1.8.1

    Deprecated: Methods with the same name as their class will not be constructors in a future version of PHP; PclZip has a deprecated constructor in /media/psf/Local/vendor/phpoffice/phpexcel/Classes/PHPExcel/Shared/PCLZip/pclzip.lib.php on line 190

Even though Im using v 1.8.1 in my project, the code from composer differs from the one available as a zip file.  If you download the zip you will see that this has been fixed.  However in composer it has not.

**Comment by kamal250** [comment]
as

**Comment by jamesexperts** [comment]
Just update
PHPExcel_Settings::setZipClass(PHPExcel_Settings::PCLZIP);
to
PHPExcel_Settings::setZipClass(PHPExcel_Settings::ZIPARCHIVE);
