### ISSUE TITLE
PHPExcel overrides the PHP INI floating-point precision

### ISSUE THREAD

**Issue by Julien-Marcou** [PHPOffice/PHPExcel#905]
I recently had a problem where my generated Excel File had wrong values in the cells.

e.g : 8.2 was displayed as 8.199999999999999

You can reproduce the bug by doing this
```php
// displays : float 8.2
var_dump(8.2);

$excel = new \PHPExcel();

// displays : float 8.199999999999999
var_dump(8.2);
```

Which is equivalent to
```php
// displays : float 8.2
var_dump(8.2);

ini_set('precision', 16);

// displays : float 8.199999999999999
var_dump(8.2);
```

To solve my problem I had to do
```php
// displays : float 8.2
var_dump(8.2);

$defaultPrecision = ini_get('precision');
$excel = new \PHPExcel();
ini_set('precision', $defaultPrecision);

// displays : float 8.2
var_dump(8.2);
```

My configuration is :
OS : Debian GNU/Linux 8.4 (jessie)
PHP version : 5.6.20-0+deb8u1
PHP_INT_SIZE : 8
PHP INI precision: 14
PHPExcel version : 1.8.1 (dated to "2015-05-01 07:00:55")

**Comment by MarkBaker** [comment]
This has long been resolved in the development branch

**Comment by gmsantos** [comment]
@MarkBaker is possible to generate a new tag with that fix ? The last stable tag have more than a year (v1.8.1) and I think that a lot more bugs has fixed.

**Comment by gvanbeck** [comment]
+1

**Comment by jeroencornelissen** [comment]
+1

**Comment by Kleppo** [comment]
+1

**Comment by MichielDilissen** [comment]
+1
