### ISSUE TITLE
PHPExcel_Shared_Date::PHPToExcel does not work with objects implementing DateTimeInterface

### ISSUE THREAD

**Issue by cvoysey** [PHPOffice/PHPExcel#907]
When attempting to use `PHPExcel_Shared_Date::PHPToExcel` with a `DateTimeImmutable` false is being returned rather than the converted value.

```
<?php
$date = new DateTime();
$excel_date = PHPExcel_Shared_Date::PHPToExcel($date);
var_dump($excel_date);

$date = new DateTimeImmutable();
$excel_date = PHPExcel_Shared_Date::PHPToExcel($date);
var_dump($excel_date);
?>
```

The above code will output:
```
double(42517.61150463)
bool(false)
```

It appears that the method uses `instanceof DateTime` rather than `instanceof DateTimeInterface`.

**Comment by PowerKiKi** [comment]
This has been done in https://github.com/PHPOffice/PhpSpreadsheet/commit/850594c#diff-495ca961ee5a4a2ab5ae21e6a550a384L229 and more generally in `DateTimeInterface` are introduced in the context of  https://github.com/PHPOffice/PhpSpreadsheet/issues/7
