### ISSUE TITLE
Encoding on HTML file

### ISSUE THREAD

**Issue by kamyweb** [PHPOffice/PHPExcel#924]
Html loads ignore internal encoding

One solutions maybe to replace line 478 on file Classes/PHPExcel/Reader/HTML.php with this:
`$loaded = $dom->loadHTML(mb_convert_encoding($this->securityScanFile($pFilename), 'HTML-ENTITIES', $this->_inputEncoding));`

**Comment by fitorec** [comment]
[:+1: This feature is already implemented.](https://github.com/PHPOffice/PHPExcel/blob/1.8/Classes/PHPExcel/Reader/HTML.php#L495)

```php
$loaded = $dom->loadHTML(mb_convert_encoding($this->securityScanFile($pFilename), 'HTML-ENTITIES', 'UTF-8'));
```
