### ISSUE TITLE
Password requested to open the Excel file

### ISSUE THREAD

**Issue by DavidGarciaCat** [PHPOffice/PHPExcel#942]
Hello there,

I have been looking for issues related with password protection, these 2 are the most interesting:
- Setting workbook password does not seem to work at all #442
- Worksheet Protection not working in Open Offfice #480

However I cannot find (easily) how I can create a PHP Excel file that requires a Password to open the spreadsheet. I need to export some data - from the database to an Excel file - but given those details may contain sensitive data Excel should ask for a password to open the document.

Is this function already implemented - I cannot find the related docs - or is not implemented yet?

Thanks for your time,

**Comment by Quix0r** [comment]
Maybe this will help?
https://github.com/PHPOffice/PHPExcel/blob/7d1c140974a4988f8a9739d167335d24fb59955e/Examples/41password.php

**Comment by DavidGarciaCat** [comment]
@Quix0r That may help, yes, thanks for the link.
I'll run some tests, and let's see if is enough for our CEO.

Cheers,

**Comment by DavidGarciaCat** [comment]
I have been testing this feature, based on the example file, but unfortunately is not working: shen we generate the Excel file, this one is not asking for the Password to open the file and display all details. Any other idea to solve this problem? Thanks,

**Comment by johnkary** [comment]
The [Open Document Format for Office Applications (OpenDocument) Version 1.2 Specification](http://docs.oasis-open.org/office/v1.2/OpenDocument-v1.2.html) contains [Section 3.4 Encryption](http://docs.oasis-open.org/office/v1.2/os/OpenDocument-v1.2-os-part3.html#__RefHeading__752811_826425813) which appears to outline how this feature could be implemented by a developer.

As of 1.8.1 it doesn't look like PHPExcel supports this functionality, and this ticket should be its feature request.

**Comment by ranieresantos** [comment]
Olá, 

Sabem me responder quando a nova versão estará disponível para download ?

**Comment by LauraBa** [comment]
Hi,
something new about this functionality?

**Comment by DavidGarciaCat** [comment]
Hi @LauraBa given the ticket is still open and there are no comments from a PHPOffice/PHPExcel member team about this implementation we must assume it's still pending.

**Comment by RubenMartins** [comment]
Any updates on this feature?

**Comment by PowerKiKi** [comment]
@RubenMartins nothing at all, except it [has now been documented](http://phpspreadsheet.readthedocs.io/en/develop/references/features-cross-reference/). Nowadays most features are implemented by contributors, you guys, not the team. If nobody step up, it will never be available. If you do implement it, please target PhpSpreadsheet instead of PHPExcel.
