### ISSUE TITLE
When remove last column, last cell value remain

### ISSUE THREAD

**Issue by sirio3mil** [PHPOffice/PHPExcel#945]
**UPDATED**

I was using 1.7.1 version, it was fixed on 1.8.1 version.

I got this excel

![2016-07-06 11_45_50](https://cloud.githubusercontent.com/assets/13035468/16614103/a4b18be2-436f-11e6-9d54-c3cfd4f8460b.jpg)

But when I remove some columns with this code

```
$myWorkSheet->removeColumn("D", 1);
$myWorkSheet->setCellValue("C{$row}", "=SUM(C2:C{$last})");
$myWorkSheet->removeColumn("B", 1);
$myWorkSheet->setCellValue("A{$row}", "=SUM(A2:A{$last})");
```

I get this

![2016-07-06 11_46_24](https://cloud.githubusercontent.com/assets/13035468/16614104/a4b1ea38-436f-11e6-9478-db1569f6ef3b.jpg)

Last cell value remain.

**Comment by johnkary** [comment]
Hi @sirio3mil. Thanks for updating your ticket that the problem was fixed in a later version. This will probably help someone in the future! What would you think about closing this issue since it has been fixed?
