### ISSUE TITLE
when i trying to save excel file i got an error

### ISSUE THREAD

**Issue by arammarm** [PHPOffice/PHPExcel#953]
Fatal error: Class 'ZipArchive' not found in /home/rtgautomotive/public_html/ebay/tecDocOutput/includes/Classes/PHPExcel/Writer/Excel2007.php on line 227

**Comment by MarkBaker** [comment]
The php_zip extension is a dependency for PHPExcel. If you don't have that dependency, then you can use the built-in PCLZip instead

```
PHPExcel_Settings::setZipClass(PHPExcel_Settings::PCLZIP);
```

but at a significant cost in performance
