### ISSUE TITLE
PHP Excel Radar and Scatter charts won't open in Excel 2007 

### ISSUE THREAD

**Issue by petehenshall** [PHPOffice/PHPExcel#956]
Running the default origin/1.8 develop/1.8 example file 33-createdchart-radar.php from linux PHP 5.6, windows PHP 5.6 and macos PHP5.6 and PHP7 throws an error. 
All these environments at least create an error in Excel when opening the file:

"Excel found unreadable content in'file.xlsx'.  Do you want to recover the contents of this workbook?"
If you click Yes you get the result of another error: 
"Repaired records: Drawing from /xl/drawings/drawing1.xml part (drawing shape). 
When the xlsx file open ups you get the "Test Radar Chart" from 0 to 1.5 but with no data points plotted.

The file opens correctly on Open Office.

The log files for the repairs is as follows:
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<recoveryLog xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><logFileName>error087680_01.xml</logFileName><summary>Errors were detected in file 'C:\Users\Pete\Sites\File.xlsx'</summary><repairedRecords summary="Following is a list of repairs:"><repairedRecord>Repaired Records: Drawing from /xl/drawings/drawing1.xml part (Drawing shape)</repairedRecord></repairedRecords></recoveryLog>

Any assistance appreciated.  All the files you will need to reproduce this issue are in the origin/1.8 as long as you open on Excel 2007 you will see the problem.  There are various reports on stackover flow to this problem but none present a solution.

Extra info: I tried useing jpgraph to create the radar chart but it errors with a:
"JPGraph Error: 25044 = Cannot use auto scaling since it is impossible to determine a valid min/max value of the y axis (only null values)."
unless I output the chart first into the worksheet in which case it will then run.

**Comment by petehenshall** [comment]
Similar to this issue: but that reports that it is fixed but it isn't for Excel 2007.

**Comment by petehenshall** [comment]
https://github.com/PHPOffice/PHPExcel/issues/645

**Comment by TheoBaart** [comment]
I  was experiencing the same issues with my scatterplots. I think I found a solution to it:

In `33chartcreate-scatter.php` building the dataseries is given as follows:
``` php
$series = new PHPExcel_Chart_DataSeries(
	PHPExcel_Chart_DataSeries::TYPE_SCATTERCHART,	// plotType
	NULL,											// plotGrouping (Scatter charts don't have any grouping)
	range(0, count($dataSeriesValues)-1),			// plotOrder
	$dataSeriesLabels,								// plotLabel
	$xAxisTickValues,								// plotCategory
	$dataSeriesValues,								// plotValues
	NULL,											// smooth line
	PHPExcel_Chart_DataSeries::STYLE_LINEMARKER		// plotStyle
);
```

However, if you look in the source code `PHPExcel/Chart/DataSeries.php` shows that the constructor for a `PHPExcel_Chart_DataSeries` has an extra element (`$plotDirection`) between `$plotValues` and `$smootLine`
``` php
public function __construct(
    $plotType = null, 
    $plotGrouping = null, 
    $plotOrder = array(), 
    $plotLabel = array(),
    $plotCategory = array(), 
    $plotValues = array(), 
    $plotDirection = null, 
    $smoothLine = null, 
    $plotStyle = null)
    {
   /* The constructor code */
}
```

So if you update your `$series` to look as follows it should work:
```php
$series = new PHPExcel_Chart_DataSeries(
	PHPExcel_Chart_DataSeries::TYPE_SCATTERCHART,	// plotType
	NULL,											// plotGrouping (Scatter charts don't have any grouping)
	range(0, count($dataSeriesValues)-1),			// plotOrder
	$dataSeriesLabels,								// plotLabel
	$xAxisTickValues,								// plotCategory
	$dataSeriesValues,								// plotValues
    NULL,											// plotDirection
	NULL,											// smooth line
	PHPExcel_Chart_DataSeries::STYLE_LINEMARKER		// plotStyle
);
```

I quickly looked at `33chartcreate-radar.php` and it is also missing the `$plotDirection` field, so I believe the same fix should work for radar plots as well.

**Comment by petehenshall** [comment]
Great stuff @TheoBaart can't believe I missed that!  I burnt about 8 hours looking in the end.. frustratingly it was opening in OpenOffice so I was looking way deeper than just the example in the source code file being fundamentally wrong!  
I can't thank you enough sir.  
Kind regards!

**Comment by petehenshall** [comment]
p.s. to anyone else reading this obviously change:

$series = new PHPExcel_Chart_DataSeries(
    PHPExcel_Chart_DataSeries::TYPE_SCATTERCHART,   // plotType

to 

$series = new PHPExcel_Chart_DataSeries(
    PHPExcel_Chart_DataSeries::TYPE_TYPE_RADARCHART,   // plotType

If you want a RADAR chart.

then include the extra NULL in the constructor before 
    PHPExcel_Chart_DataSeries::STYLE_LINEMARKER     // plotStyle

as thoebaart pointed out.

Then it should all work.

**Comment by MarkBaker** [comment]
Thanks for identifying that problem; I've fixed it in the develop branch on github
