### ISSUE TITLE
DomPDF include file is renamed in 0.7

### ISSUE THREAD

**Issue by germansokolov13** [PHPOffice/PHPExcel#958]
In Writer/PDF/DomPDF.php there are lines:

``` php
$pdfRendererClassFile = PHPExcel_Settings::getPdfRendererPath() . '/dompdf_config.inc.php';
if (file_exists($pdfRendererClassFile)) {
    require_once $pdfRendererClassFile;
} else {
    throw new PHPExcel_Writer_Exception('Unable to load PDF Rendering library');
}
```

`getPdfRendererName()` is ignored and `dompdf_config.inc.php` is hardcoded.
And it appears `dompdf_config.inc.php` was renamed to `autoload.inc.php` in dompdf 0.7. So now it's impossible to include dompdf 0.7 in PHPExcel.

**Comment by pavankumarkatakam** [comment]
I too changed the file path but after that it is saying another error.

**Comment by pavankumarkatakam** [comment]
Dom pdf lib with 0.7.0 version is not compatible with this package.

**Comment by ellej16** [comment]
@pavankumarkatakam with regards to your another error I think it has something to do with this issue ..?

Encountered this snag while playing around with maatwebsites export to pdf too:
https://github.com/dompdf/dompdf/issues/636

**Comment by lubberscorrado** [comment]
if you don't want to fork PhpExcel just to fix that and have Dompdf also included via composer, i solved it by creating file "dompdf_config.inc.php" manually somewhere in your own repo-folder (not within the dompdf composer package)  and set the $rendererLibraryPath to my foleder where that file resides. 

```php
<?php
//it's just here to make the composer package of phpexcel work with the composer package of dompdf flawlessly

//php excel has Uppercase class hardcoded ...
class DOMPDF extends \Dompdf\Dompdf{

}

```
