### ISSUE TITLE
missing borders

### ISSUE THREAD

**Issue by mmiat** [PHPOffice/PHPExcel#959]
with 1.8.0 all works, with the last version (downloading the PHPExcel-1.8.zip) borders are missing
1.8 is update 9 days ago, 1.8.0 2 years ago, 1.8.1 1 year ago, 1.9 2 months ago. I don't understand which is the lastest and best version....

however, I use:

`$workbook->getActiveSheet()->getStyle("F".$k)->getBorders()->getTop()->setBorderStyle(PHPExcel_Style_Border::BORDER_HAIR);`

**Comment by JanGalek** [comment]
I have too this problem, but when you use AllBorders, you will have bordered aside cell only.

**Comment by Squee3P0** [comment]
I've found the source of this problem and a workaround you can use until it is fixed.  See issue #1094 for details.
