### ISSUE TITLE
Why would become like this When imported into？excel

### ISSUE THREAD

**Issue by peas-ant** [PHPOffice/PHPExcel#963]
https://segmentfault.com/img/bVzIGQ

https://segmentfault.com/img/bVzIHb

**Comment by MarkBaker** [comment]
Explain your problem!!! Simply showing two images doesn't make an issue report

**Comment by grey5659** [comment]
sorry,I imported more than 1 thousand data, but some of the data is wrong, what is the reason for it?

**Comment by MarkBaker** [comment]
Wrong in what way? What data is wrong?

**Comment by grey5659** [comment]
I put the Excel data into the database, most of them are correct, but some of the data error, as shown in the picture, the sixth line of data is not always correct, thank you for your reply.

**Comment by grey5659** [comment]
The first picture is the data in the excel, the second picture is the data in the database after import ,thank you~

**Comment by MarkBaker** [comment]
I can't see any difference in the sixth line of data in those pictures:
|---|---|---|---
| 0 | 17130.36 | 22919.95

**Comment by grey5659** [comment]
sorry，Is the fifth line
-1930.50|0.00|借|40050.31
Become this way after import
0.00|-1930.50|0|0

**Comment by grey5659** [comment]
Strangely, most of the data are correct.

**Comment by grey5659** [comment]
Have done，Thank you

**Comment by ValentinNikolaev** [comment]
@MarkBaker I'm sorry to disturb you again (I sent u email but still no response....). Will 1.9 branch be maintained? No repsonse from the whole team for a month. I'm confused little bit. Cant contact with anybody.

**Comment by peas-ant** [comment]
close the issue please,I have resolved this problem, Thank you very much@MarkBaker
