### ISSUE TITLE
IOFactory::identify() has sometimes trouble with double extensions?

### ISSUE THREAD

**Issue by Quix0r** [PHPOffice/PHPExcel#970]
I have written a "daemon" that handles blacklisting. It works in the background while over Windows shares and a website files can be handled over to the daemon for checking/processing. The daemon uses PHPExel for reading lot's of different file types (Excel, ODF, CSV) for checking each row of all files if it is blacklisted (somewhy).

Sometimes it does detect a valid XSLX (Excel 2007 format) as CSV because the file has a double extension like: some_foo_file.csv_incoming.xlsx This way is very easy for me to produce "outgoing" files (they must be all converted to XLSX for later usage). Also sometimes CSV is being detected as HTML. I have now written a small wrapper that uses SplFileInfo to get file extension and checks with a hard-coded switch block (as you have in createFileReader() or so, in IOFactory class) on some known extensions (like .csv which is being used very often here).

But I see that only as a work-around and not fix as it works around a bug (in my oppinion) in PHPExcel's "detection" method.

You can try to repduce it by naming files like I do and provide a valid file (content) then.

**Comment by PowerKiKi** [comment]
It seems you have a good idea on how to fix this. Would you like to submit a PR for that ? possibly covering it with unit tests ?

**Comment by Quix0r** [comment]
Sorry, short on hands here. :-(

**Comment by Gigabyte1979** [comment]
Hi,
Thank you, All, for your Help!
Everything works fine!

Have a nice day!

**Comment by PowerKiKi** [comment]
@Gigabyte1979 I am not sure why you intervened here. Are you working with @Quix0r ? Or do you happen to have the same issue on a different context ?

**Comment by Quix0r** [comment]
No, he is not working with me on it.

**Comment by PowerKiKi** [comment]
As you [can see here](https://github.com/PHPOffice/PHPExcel/blob/1.8/Classes/PHPExcel/IOFactory.php#L225), PHPExcel itself use a detection based on file extension too. It seems unlikely that this would not work, unless it is not used correctly.

I tried to reproduce what you described with the following code and attached file [some_foo_file.csv_incoming.xlsx](https://github.com/PHPOffice/PHPExcel/files/440437/some_foo_file.csv_incoming.xlsx), but it works as expected. So I am closing this, unless you can give us a reproducible case.

This code:
```php
<?php

require 'Classes/PHPExcel.php';

$filename = 'some_foo_file.csv_incoming.xlsx';
$workbook = PHPExcel_IOFactory::load($filename);
$value = $workbook->getActiveSheet()->getCell('A1')->getValue();

var_dump($value);
echo 'PHPExcel version: ' . `git describe --always`;
```

Will correctly output:
```
string(8) "it works"
PHPExcel version: 1.8.1
```
