### ISSUE TITLE
PHP Excel autoloader is called multiple times in 1.8, change classes to use require_once instead of require

### ISSUE THREAD

**Issue by NoMan2000** [PHPOffice/PHPExcel#978]
Profiled with Blackfire.io

Here's the original:

![screenshot 2016-08-17 15 35 49](https://cloud.githubusercontent.com/assets/812215/17752216/6991e92a-6490-11e6-9e3a-3d07e90a070c.png)

Notice that it's taking 2.8 seconds.  Here's what happens when PHPExcel/Autoloader.php is changed to use require_once.

![screenshot 2016-08-17 15 54 25](https://cloud.githubusercontent.com/assets/812215/17752784/02e0669a-6493-11e6-9e0a-203ef7646d99.png)

With that one change, 2 seconds are dropped off.  It appears what is happening is that the autoloader is called multiple times from PHPExcel_IOFactory::load when it checks to see if it can read different files.

**Comment by PowerKiKi** [comment]
While I generally agree that `require_once` should often be preferred over `require`, I can't reproduce a case where `PHPExcel_Autoloader::load()` is called more than once with the same class name, hence `require` or `require_once` should not make any difference. Maybe there is something else going on that could be a bug.

Would you mind sharing the code you used for profiling and/or the list of class names you see in `PHPExcel_Autoloader::load()` ?

**Comment by NoMan2000** [comment]
Just so you can close this issue out, the issue was that the file was being delivered via stream, so it is only in PHPs temp storage.  This has no data for what file type, the name will be one of PHPs like `tmp/foo`, so without an extension, the `PHPExcel_Autoloader::load()` went through a loop trying to check everything to see what it could load successfully.  

The solution for us was simply to append the file type as a separate field before sending it to process like this.

```
    /**
     * @param  FileUploader $file
     * @return ImportUsers
     */
    public function setReader(FileUploader $file)
    {
        $extension = mb_strtolower(array_get(pathinfo($file->getNewName()), 'extension'));
        if ($extension) {
            $this->reader = $this->checkExtensionBeforeLoading($extension, $file->getRealPath());
        }
        if (!$this->reader) {
            $this->reader = PHPExcel_IOFactory::load($file->getRealPath());
        }
        return $this;
    }

/**
     * @param  $extension
     * @param  $file
     * @return null|PHPExcel
     */
    public function checkExtensionBeforeLoading($extension, $file)
    {
        $extensionType = $reader = null;
        switch ($extension) {
            case 'xlsx': //    Excel (OfficeOpenXML) Spreadsheet
            case 'xlsm': //    Excel (OfficeOpenXML) Macro Spreadsheet (macros will be discarded)
            case 'xltx': //    Excel (OfficeOpenXML) Template
            case 'xltm': //    Excel (OfficeOpenXML) Macro Template (macros will be discarded)
                $extensionType = 'Excel2007';
                break;
            case 'xls': //    Excel (BIFF) Spreadsheet
            case 'xlt': //    Excel (BIFF) Template
                $extensionType = 'Excel5';
                break;
            case 'ods': //    Open/Libre Offic Calc
            case 'ots': //    Open/Libre Offic Calc Template
                $extensionType = 'OOCalc';
                break;
            case 'slk':
                $extensionType = 'SYLK';
                break;
            case 'xml': //    Excel 2003 SpreadSheetML
                $extensionType = 'Excel2003XML';
                break;
            case 'gnumeric':
                $extensionType = 'Gnumeric';
                break;
            case 'htm':
            case 'html':
                $extensionType = 'HTML';
                break;
            case 'csv':
                // Do nothing
                // We must not try to use CSV reader since it loads
                // all files including Excel files etc.
                break;
            default:
                $extensionType = null;
                break;
        }

        if (null !== $extensionType) {
            $testReader = PHPExcel_IOFactory::createReader($extensionType);
            // Let's see if we are lucky
            if (isset($testReader) && $testReader->canRead($file)) {
                $reader = $testReader->load($file);
            }
        }
        return $reader;
    }
```
