### ISSUE TITLE
Problem with usage of getCellByColumnAndRow inside cellIterator

### ISSUE THREAD

**Issue by ajoah** [PHPOffice/PHPExcel#982]
Hi :)

Since i have updated phpexcel from 1.7.7 to 1.8.1, the following code doesn't work anymore
```php
$objReader = new PHPExcel_Reader_Excel5( 'Excel5' );
$objReader->setReadDataOnly( true );
$objPHPExcel          = $objReader->load( $file );
$objWorksheetIterator = $objPHPExcel->getWorksheetIterator();
foreach ( $objWorksheetIterator as $objWorksheet ) {
	$rowIterator = $objWorksheet->getRowIterator();
	foreach ( $rowIterator as $row ) {
		$cellIterator = $row->getCellIterator();
		foreach ($cellIterator as $cell) {
			$colIndex = PHPExcel_Cell::columnIndexFromString($cell->getColumn());
			var_dump( 'before:'.$cell->getCoordinate() );
			$myValue = $objWorksheet->getCellByColumnAndRow($colIndex-1,6)->getValue();
			var_dump( 'after:'.$cell->getCoordinate() );
			exit();
		}
	}
}
```
Output :
1.7.7 :
> before: A1
> after: A1

1.8.1
> before: A1
> after: A6

(apparently $cell is overriden by the cell returned by `getCellByColumnAndRow`)

And if the cell from `getCellByColumnAndRow` doesn't exist:
1.7.7 :
> before: A1
> after: A1

1.8.1
> before: A1
> Fatal error: Uncaught Error: Call to a member function getCurrentAddress() on null in [...]\vendor\phpoffice\phpexcel\Classes\PHPExcel\Cell.php on line 168

This is a bug or it is no longer possible to use `getCellByColumnAndRow` inside a CellIterator ?

**Comment by MarkBaker** [comment]
It's perfectly possible, but you no longer get a cell object returned, you get a "pointer" to the ___current___ cell object, and there is only ever a single "current" cell object at any one time. Getting a different cell will reset that pointer to point to the latest accessed cell instead.

**Comment by ajoah** [comment]
Thank you for your answer.
But there is a way to get a cell value without modify the pointer ? Why it worked on 1.7.7 version ?

**Comment by MarkBaker** [comment]
Because 1.7.7 was a different version.... between then and the current version 1.8.1 we introduced cell caching as a way of reducing the memory footprint of a spreadsheet, and that introduced the principle of having a pointer to a current active cell rather than making every cell directly available in memory.

There is no way of bypassing that. Why do you need to hold individual cells in memory anyway?

**Comment by ajoah** [comment]
Because i need a value which is in a lower cell compared to cell from iterator to know if i must save it or no.

**Comment by MarkBaker** [comment]
Save the cell address so you can retrieve that cell subsequently and get its value (though of course that will then become the current cell); or save the value

**Comment by ajoah** [comment]
Yes that's what I'll do. Thank you for taking the time to answer me :)
