### ISSUE TITLE
Getting mismatchtoken error on laravel when processing too many data

### ISSUE THREAD

**Issue by bevss** [PHPOffice/PHPExcel#983]
Exporting to excel is working using only few data but when data got bigger it gives me TokenMismatchException. How did that happen? By the way Im using Laravel.

**Comment by Lemoney** [comment]
How much data are you dealing with? I can go into 6 figures no problem. Perhaps you aren't configuring the object fully?

**Comment by bevss** [comment]
Im using Ajax post to generate and export excel. My data could range up to 2000+ records. I ended up letting the Route to not check the Csrf in my Laravel and now it is working.
