### ISSUE TITLE
PHPExcel and xlsm files

### ISSUE THREAD

**Issue by dan0203** [PHPOffice/PHPExcel#986]
Hello,
maybe this issue has already been released but I can't find any solution to this problem so I'll ask it.

How can I add data to an Excel file that contains macros without losing the macros ?

Thanks a lot for your input. If PHPExcel doesn't support it (that's what I keep reading on the internet, but the posts are old) maybe you have another way of doing it ?

I don't need to use or modify the macros, I just need to keep them in the file.

Have a great day everyone !

**Comment by githubjeka** [comment]
Any news?

**Comment by dan0203** [comment]
I'm not sure, it was a long time ago... But from what I remember, I have an .xslm file containing the macro and parameter 'Excel2007' in this line :

$objWriter = PHPExcel_IOFactory::createWriter($objPHPExcel, 'Excel2007');

Hope this helps.

**Comment by githubjeka** [comment]
Ok, macros have been saved. 
But running of macros by hotkey is available only. Shapes with macros and images doesn't work.

REF #928

**Comment by dan0203** [comment]
Sorry I can't help you, I have no idea... Open your own topic. Someone will help you.
