### ISSUE TITLE
Apostrophes in my sheet name

### ISSUE THREAD

**Issue by rudyZanotti** [PHPOffice/PHPExcel#988]
I have to edit some XLSX but when my sheet name contains an apostrophe (ex : "Feuille d'action") an issue occurs. 

Here is the PHP error :
`Uncaught exception 'PHPExcel_Exception' with message 'Invalid cell coordinate 'FEUILLE D'A1' in ../lib/PHPExcel-1.8.1/Classes/PHPExcel/Cell.php:590`

From my point of view, it should work.

**Comment by rudyZanotti** [comment]
I just found a similar issue : https://github.com/PHPOffice/PHPExcel/issues/740

**Comment by PowerKiKi** [comment]
Closing as duplicate of #740. Let's continue the discussion in the older issue please.
