### ISSUE TITLE
PHPExcel and Yii 1.1 Autoloaders

### ISSUE THREAD

**Issue by alexlcdee** [PHPOffice/PHPExcel#994]
## The problem
Yii framework v1.1 has it's own autoloader and its autoloader throws an error, when it can't find class. When this library initializes, it register its own autoloader, but places it at the end of autoload queue. So when I use library with Yii 1.1, I just face an error:
`include(PHPExcel_Shared_String.php): failed to open stream: No such file or directory`
'cause Yii's autoloader runs first and tries to include class file directly.

## Solution
Just register PHPExcel's autoloader at the top of autoload queue, by setting the third parameter of `spl_autoload_register` to **true**:

`PHPExcel/Autoloader.php line No.62:`
`return spl_autoload_register(array('PHPExcel_Autoloader', 'Load'), true, true);`

As it mentioned in `spl_autoload_register` documentation, the third parameter set the position of this loader in autoload queue:
> bool $prepend [optional]
> If true, spl_autoload_register will prepend the autoloader on the autoload queue instead of appending it.

**Comment by PowerKiKi** [comment]
I assume you mean it should be `true` and not the default value of `false`, right ?

**Comment by alexlcdee** [comment]
Rigth. Corrected.

**Comment by PowerKiKi** [comment]
This is now fixed for next version in https://github.com/PHPOffice/PhpSpreadsheet/commit/c3bb4245b3d911adf82c2593a52495f01f1b3f7d.

Thanks for your clear bug description.

**Comment by MarkBaker** [comment]
This was something we'd originally implemented in PHPExcel, except that it created problems with earlier versions of PHP that rejected the additional arguments for `pl_autoload_register()` so it had to be removed. Thanks for resubmitting for PHPSpreadsheet now that the version restriction no longer applies
