### ISSUE TITLE
Return current object on next() and prev() methods

### ISSUE THREAD

**Issue by jbinfo** [PHPOffice/PHPExcel#997]
In this file PHPExcel/Classes/PHPExcel/Worksheet/RowCellIterator.php
It would be useful if next() and prev() methods return current object for chaining to call getCurrent

**Comment by Quix0r** [comment]
According to [documentation](http://php.net/manual/en/class.iterator.php) the next() method returns nothing (void) and prev() seems to be no default method. In my view, PHPExcel's iterator should behave as expected, like the generic interface and not make own version.

**Comment by jbinfo** [comment]
@Quix0r You're right, thank you.

**Comment by Quix0r** [comment]
@jbinfo welcome. :-)
